### ISSUE TITLE
Decide what to display on collections home page (pre-search)

### ISSUE THREAD

**Issue by miriamschroers** [ycba-cia/blacklight-collections2#101]

**Comment by miriamschroers** [comment]
Ed will talk to Matthew for guidance

**Comment by edgartdata** [comment]
Show 100 objects: 20 paintings, 20 sculptures, 20 drawings, 20 prints/photographs, 20 rare books & manuscripts.  The curatorial departments will send in their highlights.
It would be great if they could show in a random order in this page of highlights, but that might need to be finessed later this summer.
A stop gap solution would be to have these 100 objects show in the same order for now until/if randomness is possible.

**Comment by edgartdata** [comment]
@EdwardTown1 will curate a random order for the 100.

**Comment by edgartdata** [comment]
@yulgit1 to add one new image from the Library Court. @mxgold to give the image to Eric.

**Comment by flapka** [comment]
Maybe this one: https://britishart.yale.edu/gallery/building-conservation-project

**Comment by flapka** [comment]
@EdwardTown1 mentioned in passing yesterday that he had concerns about the appearance of the image on home page (pre-search). 

As I look at it more, I wonder if it's too much rug and sofa.

**Comment by EdwardTown1** [comment]
We spoke about cropping the image, but might even think about something
different. Although I am mindful that suggesting a single object in the
collections could start WWIII.

**Comment by edgartdata** [comment]
@EdwardTown1 Can you please advise on how to proceed with this?

**Comment by edgartdata** [comment]
@EdwardTown1 Maybe a photo of the Long Gallery, or a shot of the P&D Study Room showing a sculpture and a painting?
