### ISSUE TITLE
Deploy production blacklight to Heroku

### ISSUE THREAD

**Issue by yulgit1** [ycba-cia/blacklight-collections2#107]

**Comment by edgartdata** [comment]
@yulgit1 Done?

**Comment by yulgit1** [comment]
The endpoint exists:
https://ycba-collections-prod.herokuapp.com

But it doesn't have production configuration yet, so leave this issue open. Shouldn't take more than a couple days to configure, and it should be load tested.  Waiting until closer to go live date so as to save $.

**Comment by yulgit1** [comment]
heroku certs:info -a ycba-collections-prod
heroku certs -a ycba-collections-prod

https://help.heroku.com/J2R1S4T8/can-heroku-force-an-application-to-use-ssl-tls
https://devcenter.heroku.com/articles/automated-certificate-management
https://devcenter.heroku.com/articles/ssl#manually-uploading-certificates-and-intermediaries

**Comment by yulgit1** [comment]
heroku domain added for collections.britishart.yale.edu
found private key on bac6-prod and uploaded certificates to heroku
DNS change made by ITS on July 24 to heroku specified server
using test and prod pipeline within heroku
