### ISSUE TITLE
Data refresh for testing purposes

### ISSUE THREAD

**Issue by edgartdata** [ycba-cia/blacklight-collections2#113]
@yulgit1 How heavy is the data refresh process? For testing purposes of the data through the BlackLight interface, it would be great to have data that is up to date. Would it be possible sometime soon without hindering your progress?

**Comment by yulgit1** [comment]
@edgardata - currently running a refresh, should be available tomorrow, I've set up crons, how often should it be refreshed (daily? weekly?)

@flapka - @KraigBinkowski - how often should Marc be refreshed (daily? weekly?)

It takes several hours, so the longer between refreshes the better as far as processing is concerned.

**Comment by flapka** [comment]
@edgartdata @KraigBinkowski @yulgit1 

When we go in to production with Blacklight, we should have a daily refresh from MARC.

During testing & development, daily would be useful as well. But if that's onerous, weekly would do.

**Comment by edgartdata** [comment]
I agree wtih @flapka: when Blacklight is in production, it needs to be refreshed daily to reflect the changes in the source databases.
For now, however, I think weekly on weekend (so that we start every week with updated data) would be helpful. Thanks Eric!

**Comment by KraigBinkowski** [comment]
agreed

**Comment by yulgit1** [comment]
current settings:
marc harvest running 6:00PM Sat (~10 minutes)
marc and lido ingest running 6:30PM Sat  (lido done in <1hr, marc 15hrs)

2019-03-16T22:30:02.305Z (start marc/lido)
2019-03-16T23:08:20.436Z (last marc)
2019-03-17T13:33:01.731Z (last lido)

cron=0+0+22+?+*+SAT
cron=0+30+22+?+*+SAT

**Comment by EdwardTown1** [comment]
@yulgit1 I appreciate that this is a big ask given the number of indices entailed in the new collections search, but please may @edgartdata and I make a petition for a daily data/index refresh - this is the high standard that we aspire to, although we shall take your lead as to how best to go about creating schedule for presenting the latest knowledge of the collection. Might it be possible to return to this question to return to after the dust settles on the launch in July?

**Comment by yulgit1** [comment]
@EdwardTown1 - I Understand. We've been putting in place the framework to allow this to happen as @flapka is well aware.  Basically we've now got indexing time down from ~16 hrs to < 2 hours.  I've also set a cron where it takes a few seconds to copy over the indexing done on test to production which will run shortly after indexing, which can be disabled in case post-launch-development needs to occur. My goal is to run daily indexing by the time of launch.

**Comment by EdwardTown1** [comment]
That’s amazing. Thanks Eric.

Have a good weekend.

E T

**Comment by yulgit1** [comment]
Daily Data refresh schedule as of now:

marc OAI-PMH harvest 5PM (0+0+21) (~ 1h15m)
LIDO&MARC ingest processing to test 6:30PM(0+30+22) (~1h45m)
copy test index to prod 10PM (0 2 * * *) (~10 sec)
weekly log rollovers 11PM (0 3 * * TUE)
daily log rollovers 11:15PM (15 3 * * *)

Documented here:
https://git.yale.edu/ermadmix/camel_collections2/wiki/camel_collections2-log-rollover

**Comment by edgartdata** [comment]
Heroku PROD drops every so often.

**Comment by yulgit1** [comment]
Misunderstanding from meeting. Heroku DEV not, PROD

2020-06-05T14:03:17.389851+00:00 heroku[web.1]: Process running mem=696M(136.0%)
2020-06-05T14:03:17.392025+00:00 heroku[web.1]: Error R14 (Memory quota exceeded

temporary resolution:
heroku restart -a ycba-collections-dev

looks into alerts and rolling restarts in production configuration
https://devcenter.heroku.com/articles/ruby-memory-use

**Comment by edgartdata** [comment]
@yulgit1 for clarification for us all, can you please restate here what BL link we should keep an eye on to alert you of problems? thanks.

**Comment by yulgit1** [comment]
https://ycba-collections-dev.herokuapp.com
