### ISSUE TITLE
Formatting of fields & text in detailed records

### ISSUE THREAD

**Issue by edgartdata** [ycba-cia/blacklight-collections2#115]
We talked about how the text is not on the same line as the fields but just one line below. 
Suggestion: push the text further to the right, and bring it to the same level as the field labels,
New design options will need to work for mobile version.
@EdwardTown1 please weigh in on the new options.

**Comment by edgartdata** [comment]
@yulgit1 to provide screen shots of different option for the 4/9 meeting.

**Comment by yulgit1** [comment]
<img width="1157" alt="Screen Shot 2019-04-02 at 5 10 35 PM" src="https://user-images.githubusercontent.com/2125400/55438048-8c4b0100-556e-11e9-987c-0f8b1f6bfaaa.png">

**Comment by yulgit1** [comment]
<img width="1148" alt="Screen Shot 2019-04-02 at 5 25 43 PM" src="https://user-images.githubusercontent.com/2125400/55438106-b3a1ce00-556e-11e9-817d-f421a75be5a8.png">

**Comment by yulgit1** [comment]
<img width="474" alt="Screen Shot 2019-04-02 at 5 44 41 PM" src="https://user-images.githubusercontent.com/2125400/55438261-23b05400-556f-11e9-849b-fb5d7059f061.png">

**Comment by yulgit1** [comment]
<img width="468" alt="Screen Shot 2019-04-02 at 5 45 11 PM" src="https://user-images.githubusercontent.com/2125400/55438290-3165d980-556f-11e9-9625-de557107ac76.png">

**Comment by yulgit1** [comment]
Please see above (label text on different line vs label on same line) shown for both browser and mobile, and add a comment with your preference.

**Comment by flapka** [comment]
I most like the second screenshot. It might be improved still by:
* Adding a little bit of space (padding?) between each line/row
* Making the field labels (title, creator, etc.) right-justified, as in this example from YUL's Quicksearch.

![image](https://user-images.githubusercontent.com/7634899/55478666-374cd080-55ea-11e9-89b1-462945624b29.png)

**Comment by yulgit1** [comment]
Per Francis's suggestions above (padding and right justified labels):
<img width="1159" alt="Screen Shot 2019-04-03 at 9 32 20 AM" src="https://user-images.githubusercontent.com/2125400/55482904-7d5a6200-55f3-11e9-8615-7dabeccd5936.png">
<img width="472" alt="Screen Shot 2019-04-03 at 9 34 14 AM" src="https://user-images.githubusercontent.com/2125400/55483030-c0b4d080-55f3-11e9-879b-84796ad4662c.png">

**Comment by yulgit1** [comment]
Looked like a big improvement so went ahead and pushed these changes. Should be available now at 10.5.96.187:3000
Resolution: https://github.com/ycba-cia/blacklight-collections2/commit/d2703f99e83937718b930602d06434d124e53c19

**Comment by edgartdata** [comment]
@yulgit1 I really like this new look too!
