### ISSUE TITLE
Develop IIIF manifest procedures for RB material

### ISSUE THREAD

**Issue by flapka** [ycba-cia/blacklight-collections2#119]
Francis will get in touch with Rebecca Hirsch (Beinecke)

**Comment by edgartdata** [comment]
Eric has devised a process for creating IIIF manifests for Rare Books & Manuscripts.
@flapka Laura is going through RB images to make sure that they have the appropriate CDS level (only 17 goes to IIIF). In the meantime BlackLight will show whatever RB currently has as 17. 

@mxgold All to meet on June 5 to decide on Rights and Links sections of the manifests.

Eric has also created a process for generating Activities Streams for the Center.  CCD will use AS to harvest our IIIF manifests and our data updates.

**Comment by edgartdata** [comment]
This is dependent on the new CDS to be in production, which will not happen until December.

**Comment by edgartdata** [comment]
@yulgit1 has feedback from @flapka and @KraigBinkowski 
ITS requires JSON for RB material, not MARC.

**Comment by flapka** [comment]
@yulgit1 @edgartdata Is Eric working on the JSON requirement? Is anything needed from me?

**Comment by yulgit1** [comment]
@flapka yes, the marc mapping questions I emailed you and Kraig last week were related to when the plan was to just give them marc and mappings.  Last week it was decided for the units to provide json for any formats other than lido.  ITS (Seong) will provide the json requirements, and once these were ready, I will work on these and may have additional questions.

**Comment by flapka** [comment]
@yulgit1 Could you remind me where things stand on this issue? Is there anything needed from me?

**Comment by yulgit1** [comment]
@flapka - what Emmanuelle said on July 26 (see above).  Although December is come and gone, and haven't heard from CDS people, but I image something will be coming soon.

**Comment by edgartdata** [comment]
@yulgit1 @flapka Would it be helpful to reach out to Song and Jeff at this point in time? I imagine Courtney might want to see all images of all YCBA items made available in the same in our online catalog. I think CIA is meeting with her this month.

**Comment by yulgit1** [comment]
@edgartdata @flapka , all: Seong responded - end of April.

**Comment by edgartdata** [comment]
@yulgit1 Thanks Eric. 
@flapka Do you have a sense of what metadata your collection will share in the IIIF manifests?

**Comment by flapka** [comment]
The attached shows the intended MARC-to-IIIf mapping, when last discussed in late September.

[ycba_marc_iiif_FL-comments (002).txt](https://github.com/ycba-cia/blacklight-collections2/files/4016967/ycba_marc_iiif_FL-comments.002.txt)

**Comment by yulgit1** [comment]
Since September, rather than doing a MARC->iiif mapping, I changed over to using blacklight json->iiif as the mappings are much simpler.  Below is the script that generated the cds json that I sent to Seong.  You can check the blacklight source of any object by appending ".json" to any blacklight item page, ex:

http://10.5.96.187:3000/catalog/orbis:11676593.json

[cds-iiif-marcjson copy.txt](https://github.com/ycba-cia/blacklight-collections2/files/4017189/cds-iiif-marcjson.copy.txt)

**Comment by flapka** [comment]
@yulgit1 @edgartdata Thanks, Eric, using a blacklight json->iiif mapping makes good sense. 

I have several small changes to suggest, as captured in the comments of this file: 

[cds-iiif-marcjson_FL-comments_2020-01-03.docx](https://github.com/ycba-cia/blacklight-collections2/files/4019450/cds-iiif-marcjson_FL-comments_2020-01-03.docx)

Let me know what you think.

**Comment by edgartdata** [comment]
@mxgold Let's schedule time to look at the RBM manifest structure with you?

**Comment by flapka** [comment]
@yulgit1 Where do things stand now with the tech piece of the puzzle for iiif + RB/IA.

**Comment by yulgit1** [comment]
Should roll out with CDS2 when that gets delivered in 2021. From YCBA, once that's in place, arrange for metadata updates via the activity stream process.

**Comment by flapka** [comment]
@yulgit1 @mxgold It sounds like CDS2 rollout is near. In a separate discussion this afternoon, Melissa mentioned that the plan is to (eventually) provide iiif manifests for *all* images, regardless of rights status. 

If that's the eventual course of action, does that mean that all images, even thumbnails for works in copyright, would be displayed in the openseadragon viewer in Blacklight?

**Comment by yulgit1** [comment]
Yes.  Objects in CDS1 that were displayed as thumbnails will show up in CDS 2 IIIF viewer as images max pixels 480.

**Comment by flapka** [comment]
@yulgit1 Now that we have real examples in development with the Mirador 3 viewer (related to issue #56 ), I see one aspect of the manifest specification that I'd like to modify, if possible.

The IIIF "label" field has intermittent wonkiness due to MARC punctuation syntax. Could we normalize the title_short_ss data that forms a part of the "label" in a way that imitates the normalization that takes place above the image in our current catalog? That is: delete entirely any occurrence of “ : “ “ /“ or “.“ at the end of the title_short_ss field. Examples:
* Where we want to delete " :": http://10.5.96.187:3000/catalog/orbis:8994205
* Where we want to delete " /": http://10.5.96.187:3000/catalog/orbis:3786305
* Where we want to delete ".": http://10.5.96.187:3000/catalog/orbis:9452785

Aside from that, the manifest outcomes look good so far. Thanks!

**Comment by yulgit1** [comment]
@flapka  - the punctuation should now be fixed in the activity stream, will ask Seong about updating the manifests

https://ycba-cds-iiif.s3.amazonaws.com/ycba/orb/8994205.json
https://ycba-cds-iiif.s3.amazonaws.com/ycba/orb/3786305.json
https://ycba-cds-iiif.s3.amazonaws.com/ycba/orb/9452785.json

**Comment by flapka** [comment]
Thanks @yulgit1 . In the json, outcomes in the revised labels look good.

**Comment by edgartdata** [comment]
Sorry, I may have entered my comment in the wrong issue! I meant to ask about our request to Seong on the masonry images for sketchbooks. Can we close 119?
