### ISSUE TITLE
Subjects in full record view (from MARC) -- remove pipes

### ISSUE THREAD

**Issue by flapka** [ycba-cia/blacklight-collections2#120]
In the full item view for material in RB, REF, and IA, we can remove the pipes between subject terms, because the line break is sufficient. 

Currently Blacklight displays this:

Actresses -- Great Britain. | 
Chocolate candy -- Great Britain. | 
Chocolate candy containers -- Specimens. | 
Chocolate industry -- Great Britain. | 
Elsie, Lily, 1886-1962 -- Portraits. | 
Fall, Leo, 1873-1925. Dollarprinzessin. English. | 
J.S. Fry & Sons. | 
Theater -- Great Britain.

We want this:

Actresses -- Great Britain.
Chocolate candy -- Great Britain.
Chocolate candy containers -- Specimens.
Chocolate industry -- Great Britain.
Elsie, Lily, 1886-1962 -- Portraits.
Fall, Leo, 1873-1925. Dollarprinzessin. English.
J.S. Fry & Sons.
Theater -- Great Britain.

**Comment by yulgit1** [comment]
resolved: https://github.com/ycba-cia/blacklight-collections2/commit/c5be0be951fe00a1ad7d228fc4db77dcfcecd7b9
