### ISSUE TITLE
Filter out (do not map) "Chron." subjects

### ISSUE THREAD

**Issue by flapka** [ycba-cia/blacklight-collections2#121]
Records in RB collections include data such as this: 690 $a Chron. $y 1748.

The 690 is one of many that map to Blacklight's topic (subject) field. 

We'd like to adjust the marcxslt to that any 690 field that contains the string "Chron." (or "Chron") is *not mapped* to Blacklight. I.e., omit the entire 690 field when it contains Chron.

**Comment by flapka** [comment]
At least half of RB records have this field. Here's one example (among thousands):
http://10.5.96.187:3000/catalog/orbis:3336554

**Comment by edgartdata** [comment]
@flapka Can you check please? Fresh data on Monday!

**Comment by flapka** [comment]
Looks fixed. Thanks!

**Comment by edgartdata** [comment]
Yeah! let's close this issue.
