### ISSUE TITLE
Adjust MARC mapping to creator (author) field -- removing subfield $e - add URIs

### ISSUE THREAD

**Issue by flapka** [ycba-cia/blacklight-collections2#122]

**Comment by flapka** [comment]
Currently our marcxslt maps the entirety of the 100/110/111 fields to author (creator). We'd like to modify the mapping so that subfield $e is not include. 

Example data:
* 100 $a Smith, John, $d 1721-1782, $e engraver.
* 110 $a Brown & Company, $e publisher.

Details:

1. In the search results screen and in the creator facet, we do not want the information in subfield $e to appear. Presumably the easiest way to do this is to adjust the marcxslt mapping.

2. When we remove the subfield $e data from the creator's name in search results and in the creator facet, we also need to normalize the ending punctuation. That is: after removing subfield $e, if the string ends in a comma (e.g., ... 1782,) or a period, we want to remove the comma or period.

3. In the full record/item view, we want the creator name to appear with the subfield $e information. For example: Smith, John, 1721-1782, engraver.

**Comment by yulgit1** [comment]
resolved:https://github.com/ycba-cia/blacklight-collections2/commit/22749f2c28de2dc5266b8388009f3a5e6c41b228
and
https://git.yale.edu/ermadmix/ycba_xslts/commit/5af58a5806ec3dd61d212ebb8291b00c2d6e8a76
and
https://git.yale.edu/ermadmix/camel_collections2/commit/4419dfded0e5eb557455a5d824e789471d2b3b67
for orbis:9049663
full reindexing over weekend
