### ISSUE TITLE
Revise the "If you have information about this object ..." text

### ISSUE THREAD

**Issue by flapka** [ycba-cia/blacklight-collections2#123]
@yulgit1 @EdwardTown1 

Based on today's discussion:

1. Move the text "If you have information about this object that may be of assistance please contact us." so that it appears right after the "Export" row, perhaps aligned with (directly under) "XML | RDF"

2. Adjust the formatting for the words "contact us" so that it is clear that this is a hyperlink (opens email).

3. For art collections, the hyperlink should remain as is (email to ycba.online@yale.edu).

4. For RB material, the link should create an email to ycba.rarebooks@yale.edu

4. Kraig does not want the text/link for Ref collections.

**Comment by yulgit1** [comment]
addressed:https://github.com/ycba-cia/blacklight-collections2/commit/2b264c8fee043b5dd73438f839ca2d613152393d

art collections example:
http://10.5.96.187:3000/catalog/tms:5005

RB example:
http://10.5.96.187:3000/catalog/orbis:3388920

ref example:
http://10.5.96.187:3000/catalog/orbis:159753
