### ISSUE TITLE
Image count under the image at top of detailed record

### ISSUE THREAD

**Issue by edgartdata** [ycba-cia/blacklight-collections2#124]
@EdwardTown1 @mxgold I wonder if the image count (image 1 of 2, image 2 of 2...) right under the image at top of detailed record is necessary, especially for copyrighted works for which we are only making one small image available in the catalog? Even for the large images, it seems to be pushing the descriptive metadata further away from the main image.

Also, are we interested in considering putting the image view description (ex.: cropped to image, recto, unframed) and the object rights type on the same line rather than one below the other?

**Comment by EdwardTown1** [comment]
Agreed, it seems superfluous in those instances; and it would be good to
have the descriptions - in fact it might be necessary for the sake of
accessibility.

Thanks for raising this
E T

**Comment by yulgit1** [comment]
resolved:https://github.com/ycba-cia/blacklight-collections2/commit/bb7412555a165642cbcf014e79dfe369fe720811
