### ISSUE TITLE
Limit number of results shown under each facet?

### ISSUE THREAD

**Issue by edgartdata** [ycba-cia/blacklight-collections2#125]
1. Do we want to limit how many results are shown under each facet? 
Right now we can end up with having to scroll quite a bit to get to the end of the results shown and to the next facet.

2. If yes to question 1, can we have different limits for different facets?
Right now in the Associated People facet for P&S, we go from Shakespeare (has 40 works associated) directly to David Garrick (has 6 works associated with him), and having this facet only show terms that have more than 20 works associated with them would only leave Shakespeare in this facet.
![Associated People facet](https://user-images.githubusercontent.com/4093644/56051005-5c90bb80-5d1b-11e9-9b1c-aac310919696.png)

**Comment by flapka** [comment]
I think a limit could be useful, giving the first x number (perhaps 10). After the 10th, you can click on something that allows you to see the rest. This is what YUL's Quicksearch does. See screenshot.

![image](https://user-images.githubusercontent.com/7634899/56060488-003a9580-5d35-11e9-8e6b-42f88fa01602.png)

**Comment by edgartdata** [comment]
Limit all facet results to 20.

**Comment by yulgit1** [comment]
resolved: https://github.com/ycba-cia/blacklight-collections2/commit/23057d96f507f3055327777027997bea6644c39f
