### ISSUE TITLE
Date relevance 

### ISSUE THREAD

**Issue by edgartdata** [ycba-cia/blacklight-collections2#126]
@yulgit1  please have the dates in ascending order

**Comment by yulgit1** [comment]
@edgardata, with asc all the undated get sorted to the top, is this ok?

**Comment by edgartdata** [comment]
Unfortunately not, if possible.

**Comment by yulgit1** [comment]
@edgartdata I don't understand your response, should dates be asc? desc? or rethink this?

**Comment by edgartdata** [comment]
@yulgit1 dates should be ascending only where there are dates. If a work is not dated, then it should not be included in this sorting logic since it is a date sort.

**Comment by yulgit1** [comment]
@edgartdata - I will experiment with adding a custom field type with a sortMissingLast parameter that will move undated last, this seems to be the closest thing to this

https://www.drupalconnect.com/blog/articles/how-control-sorting-nodes-missing-values-sort-field-apache-solr

**Comment by edgartdata** [comment]
@yulgit1 Hi Eric, let me know when I can test this.

**Comment by yulgit1** [comment]
@edgartdata - this issue has opened up a Pandora's box which I've been working on the past 2 days.  A lot of data isn't in dddd format, and noticed other related ingest errors, as well as some cleanup to do with deleted items.  I will continue working on this this week and hopefully have things in place for the ingest run this weekend.

**Comment by edgartdata** [comment]
Let me know what I can do on my side if I can help?
