### ISSUE TITLE
Display short title only (for library collections) in search results view

### ISSUE THREAD

**Issue by flapka** [ycba-cia/blacklight-collections2#130]
Following Elisabeth's suggestion today, it would be better, in search results, to show only the primary (or beginning) portion of each title for library collections -- because some are absurdly long. 

This change would mean using only MARC 245 subfield $a -- as opposed to the entire 245. Given that we want the full title (the entire 245) to display in the detailed record view, do we need to create a new Blacklight field for short title? The marc-preblacklight XSLT already has a correct template for "title_short_ss" -- but that field isn't in our list of Blacklight implemented fields.

**Comment by yulgit1** [comment]
@flapka - yes there is a title_short_ss for the picking, available for TMS and well as library objects, should I use?

http://10.5.96.187:3000/catalog/orbis:11621093.json

**Comment by flapka** [comment]
Yes, if the existing title_short_ss fulfills all objectives, makes sense to use it.

**Comment by flapka** [comment]
Sorry, forgot to add: The challenge with the shorter title is that it may leave us with wonky punctuation at the end of 245 subfield $a -- frequently a " : " or a " / " -- which we don't want to display. Could we normalize so that any space-colon-space or space-forward-slash-space is removed from the short title?

**Comment by yulgit1** [comment]
Resolved.
All: OK?

**Comment by flapka** [comment]
Looks great. Thanks!
