### ISSUE TITLE
In search results display Creator (first), then Title, then Date

### ISSUE THREAD

**Issue by flapka** [ycba-cia/blacklight-collections2#131]
Elisabeth and Matthew request that the creator's name appears on the top line, followed by the title and date -- the title to be displayed in bold. 

(Sorry if this issue is reported elsewhere; I don't see it.)

**Comment by flapka** [comment]
If we make this creator/title swap on the image-centric view of search results, we need to do the same (I assume) on the library/list view, e.g.: http://10.5.96.187:3000/?q=dore&search_field=all_fields&view=list

If in that view creator also appears before title, I think it no longer makes sense to have any of the textual information starting on the left hand side (in the way that the title appears now). I'm keen to see how the appearance compares when all text is in that 2nd column.

**Comment by yulgit1** [comment]
Resolved.
All: OK?

**Comment by flapka** [comment]
Looks good in the "masonry" view. Do we want to make a parallel change in the "list" view: http://10.5.96.187:3000/?search_field=dummy_range&view=list
