### ISSUE TITLE
Display thumbnail captions

### ISSUE THREAD

**Issue by flapka** [ycba-cia/blacklight-collections2#132]
I believe I heard a request from Elisabeth (if not others) to reinstate the thumbnail captions -- of the sort "recto" or "page 212"

**Comment by yulgit1** [comment]
@flapka 

Here's an example of a very large caption:
http://10.5.96.187:3000/catalog/orbis:146545

https://deliver.odai.yale.edu/info/repository/YCBA/object/146545/type/1

We'll probably need to cap to caption length when reinstating with the thumbnail.

**Comment by flapka** [comment]
@yulgit1 @mxgold 

Indeed in that example -- and any like it -- the caption is unwieldy. I think this is actually a data issue in NetX. For a number of RB objects, data that should be in the NetX credit line field has instead been put in the caption field. So we have some data clean-up to do (in NetX).

**Comment by edgartdata** [comment]
The image display keywords/caption will appear under each image in the image ribbon.

**Comment by flapka** [comment]
@flapka will schedule a meeting with Melissa et al as first step to cleaning up the data in the image display keywords/caption field for RB material -- a necessary precursor to implementing the changes described above

**Comment by yulgit1** [comment]
@flapka @edgartdata can you provide an example object with long captions and more than 1 image?

**Comment by edgartdata** [comment]
http://10.5.96.187:3000/catalog/tms:1153

**Comment by yulgit1** [comment]
@flapka @edgartdata 
string length capped at 48 characters, how this look?
http://10.5.96.187:3000/catalog/orbis:3388920

this one's caption actually fits, but posting it as another example w/ captions enabled:
http://10.5.96.187:3000/catalog/tms:1153

**Comment by flapka** [comment]
That Orbis record above (http://10.5.96.187:3000/catalog/orbis:3388920) is a good example of an object in NetX where the data is in the wrong field -- it'll be replaced with something shorter, after clean up.

The appropriate thumbnail captions will be like what appears with our Vinters in Kent red book: http://10.5.96.187:3000/catalog/orbis:9292982

**Comment by edgartdata** [comment]
@yulgit1 I think 48 characters for view description under each thumbnail in the image ribbon works well.

**Comment by flapka** [comment]
I agree, on the limit of 48 characters.
