### ISSUE TITLE
ObjectID

### ISSUE THREAD

**Issue by edgartdata** [ycba-cia/blacklight-collections2#133]
@yulgit1 Could you please replicate what is currently in Vufind, which is that hovering over the accession number reveals the TMS objectID? This is very helpful for a number of things.

**Comment by yulgit1** [comment]
OK, added it: https://github.com/ycba-cia/blacklight-collections2/commit/a34bc7c4f8fcf7919d271ae611829ad4bd70529d

Another hint, you can also look at the identifier in the url: 
http://10.5.96.187:3000/catalog/tms:1011
