### ISSUE TITLE
Accession/Call number search

### ISSUE THREAD

**Issue by edgartdata** [ycba-cia/blacklight-collections2#137]
@yulgit1 Would it be possible to search on Accession numbers and Call numbers in the All Fields search box?

**Comment by flapka** [comment]
This would be desirable for library collections too (search call numbers in all fields search)

**Comment by yulgit1** [comment]
@edgartdata @flapka 

I added fielded search which should achieve this functionality.  Click on the box to the left of the search box to specifically search by title,creator,subject terms,or call number

Related to:
https://github.com/ycba-cia/blacklight-collections2/issues/136

**Comment by edgartdata** [comment]
That might be possible but I will ask just in case: would it be possible to search on title,creator,subject terms,or call number without having to select title,creator,subject terms,or call number?
In other words, if I type B1970.1 and All Fields is selected, it would be amazing if the Yale portrait would come up. The reason is that i don't think many users are going to use the drop down under All Fields.

**Comment by yulgit1** [comment]
As far as I can tell it does:

http://10.5.96.187:3000/?utf8=✓&search_field=all_fields&q=B1970.1

**Comment by edgartdata** [comment]
It does not work for any other accession number for me? For example B1973.1.14

**Comment by yulgit1** [comment]
Typo in config (should be 'callnumber_txt', not 'call_number_txt')

Please try now.

**Comment by edgartdata** [comment]
@yulgit1 Perfect! Thanks so much Eric!

**Comment by flapka** [comment]
@yulgit1 @edgartdata When I search for RB call numbers in the All Fields search, it appears to work well (though small sample size so far).

But: when I search for RB call numbers in the Call Number search, it doesn't seem to work at all (i.e., no hits).

**Comment by yulgit1** [comment]
@flapka - please try call number search now.

**Comment by flapka** [comment]
@yulgit1 Yes, seems to work well now. Thanks!
