### ISSUE TITLE
IIIF for the art collection

### ISSUE THREAD

**Issue by edgartdata** [ycba-cia/blacklight-collections2#138]
Update the list of records that have IIIF manifests for LIDO XML. For now @yulgit1 will get that list from the CDS from what has JP2. 

In the future, post launch, put in place a system so that LIDO XML always grab an updated list of IIIF manifests.

**Comment by yulgit1** [comment]
script getting manifests from s3: https://github.com/ycba-cia/blacklight-collections2/commit/4c951191055691222512416e9dbb547f429895fd

format: 
manifest/9998
manifest/9999
...

**Comment by edgartdata** [comment]
Monthly refresh of the IIIF list for LIDO.
