### ISSUE TITLE
outstanding ingest errors

### ISSUE THREAD

**Issue by yulgit1** [ycba-cia/blacklight-collections2#141]
Down to 30 ingest errors out of 11826, 2 types of errors.

@flapka - the 6 dc:language errors are a result of where in dc:language there is a note-like string (ex: "Translated from John Speed's "The theatre of the Empire of Great Britaine" the text of which is largely taken from William Camden's Britannica. Translated by Philemon Holland; maps engraved chiefly by Jodocus Hondius."), in addition to the language code (ex: "lat") in dc:language. Currently ingest is set to expect only a 3 letter language code in the language element.  Let me know if these is are metadata errors, or should be processed as is. 

@edgartdata - there are 24 errors because ingest is expecting an accession number like L1999... or B1975.... so as to parse out the year in the 2,3,4,5 indexes of the string.  These 24 defy this convention (most with a L.1999..., (when expecting L1999...)).  Let me know if this is metadata to be fixed in TMS or if special parsing should be put into place for these.

Dc:language:
https://libapp.library.yale.edu/OAI_BAC/src/OAIOrbisTool.jsp?verb=GetRecord&metadataPrefix=oai_dc&identifier=oai:orbis.library.yale.edu:3561593
https://libapp.library.yale.edu/OAI_BAC/src/OAIOrbisTool.jsp?verb=GetRecord&metadataPrefix=oai_dc&identifier=oai:orbis.library.yale.edu:12466980
https://libapp.library.yale.edu/OAI_BAC/src/OAIOrbisTool.jsp?verb=GetRecord&metadataPrefix=oai_dc&identifier=oai:orbis.library.yale.edu:9767095
https://libapp.library.yale.edu/OAI_BAC/src/OAIOrbisTool.jsp?verb=GetRecord&metadataPrefix=oai_dc&identifier=oai:orbis.library.yale.edu:9801936
https://libapp.library.yale.edu/OAI_BAC/src/OAIOrbisTool.jsp?verb=GetRecord&metadataPrefix=oai_dc&identifier=oai:orbis.library.yale.edu:12255056
https://libapp.library.yale.edu/OAI_BAC/src/OAIOrbisTool.jsp?verb=GetRecord&metadataPrefix=oai_dc&identifier=oai:orbis.library.yale.edu:12455172

workID type=“inventory number”
L.1999-105.364
	http://bac6-prod.its.yale.edu/oaicatmuseum/OAIHandler?verb=GetRecord&identifier=oai:tms.ycba.yale.edu:45186&metadataPrefix=lido
L.1999-105.367
	http://bac6-prod.its.yale.edu/oaicatmuseum/OAIHandler?verb=GetRecord&identifier=oai:tms.ycba.yale.edu:45189&metadataPrefix=lido
L.1999-105.365
	http://bac6-prod.its.yale.edu/oaicatmuseum/OAIHandler?verb=GetRecord&identifier=oai:tms.ycba.yale.edu:45187&metadataPrefix=lido
L.1999-105.368
	http://bac6-prod.its.yale.edu/oaicatmuseum/OAIHandler?verb=GetRecord&identifier=oai:tms.ycba.yale.edu:45190&metadataPrefix=lido
L.1999-105.369
	http://bac6-prod.its.yale.edu/oaicatmuseum/OAIHandler?verb=GetRecord&identifier=oai:tms.ycba.yale.edu:45191&metadataPrefix=lido
L.1999-105.370
	http://bac6-prod.its.yale.edu/oaicatmuseum/OAIHandler?verb=GetRecord&identifier=oai:tms.ycba.yale.edu:45192&metadataPrefix=lido
L.1999-105.372
	http://bac6-prod.its.yale.edu/oaicatmuseum/OAIHandler?verb=GetRecord&identifier=oai:tms.ycba.yale.edu:45195&metadataPrefix=lido
L.1999-105.373
	http://bac6-prod.its.yale.edu/oaicatmuseum/OAIHandler?verb=GetRecord&identifier=oai:tms.ycba.yale.edu:45198&metadataPrefix=lido
L.1999-105.403
	http://bac6-prod.its.yale.edu/oaicatmuseum/OAIHandler?verb=GetRecord&identifier=oai:tms.ycba.yale.edu:45281&metadataPrefix=lido
L.1999-105.406
	http://bac6-prod.its.yale.edu/oaicatmuseum/OAIHandler?verb=GetRecord&identifier=oai:tms.ycba.yale.edu:45284&metadataPrefix=lido
L.1999-105.407
	http://bac6-prod.its.yale.edu/oaicatmuseum/OAIHandler?verb=GetRecord&identifier=oai:tms.ycba.yale.edu:45330&metadataPrefix=lido
L.1999-105.408
	http://bac6-prod.its.yale.edu/oaicatmuseum/OAIHandler?verb=GetRecord&identifier=oai:tms.ycba.yale.edu:45331&metadataPrefix=lido
L.1999-105.410
	http://bac6-prod.its.yale.edu/oaicatmuseum/OAIHandler?verb=GetRecord&identifier=oai:tms.ycba.yale.edu:45336&metadataPrefix=lido
L.1999-105.496
	http://bac6-prod.its.yale.edu/oaicatmuseum/OAIHandler?verb=GetRecord&identifier=oai:tms.ycba.yale.edu:46777&metadataPrefix=lido
L.1999-105.497
	http://bac6-prod.its.yale.edu/oaicatmuseum/OAIHandler?verb=GetRecord&identifier=oai:tms.ycba.yale.edu:46778&metadataPrefix=lido
L.1999-105.493
	http://bac6-prod.its.yale.edu/oaicatmuseum/OAIHandler?verb=GetRecord&identifier=oai:tms.ycba.yale.edu:46774&metadataPrefix=lido
L.1999-105.495
	http://bac6-prod.its.yale.edu/oaicatmuseum/OAIHandler?verb=GetRecord&identifier=oai:tms.ycba.yale.edu:46776&metadataPrefix=lido
L.1999-105.494
	http://bac6-prod.its.yale.edu/oaicatmuseum/OAIHandler?verb=GetRecord&identifier=oai:tms.ycba.yale.edu:46775&metadataPrefix=lido
T185.8
	http://bac6-prod.its.yale.edu/oaicatmuseum/OAIHandler?verb=GetRecord&identifier=oai:tms.ycba.yale.edu:49691&metadataPrefix=lido
S215.7
	http://bac6-prod.its.yale.edu/oaicatmuseum/OAIHandler?verb=GetRecord&identifier=oai:tms.ycba.yale.edu:49702&metadataPrefix=lido
L194.6
	http://bac6-prod.its.yale.edu/oaicatmuseum/OAIHandler?verb=GetRecord&identifier=oai:tms.ycba.yale.edu:49717&metadataPrefix=lido
L235.18
	http://bac6-prod.its.yale.edu/oaicatmuseum/OAIHandler?verb=GetRecord&identifier=oai:tms.ycba.yale.edu:49728&metadataPrefix=lido
L325.5
	http://bac6-prod.its.yale.edu/oaicatmuseum/OAIHandler?verb=GetRecord&identifier=oai:tms.ycba.yale.edu:49734&metadataPrefix=lido
L.1999-105.550
	http://bac6-prod.its.yale.edu/oaicatmuseum/OAIHandler?verb=GetRecord&identifier=oai:tms.ycba.yale.edu:50825&metadataPrefix=lido

**Comment by flapka** [comment]
@yulgit1 Thanks Eric, this is helpful. For the dc:language error, could you point me to the code that parses this data from MARC? It's not in marc-preblacklight-ycba.xsl, is it? 

My hunch is that the existing code looks at two places in the MARC record: the coded language data (part of the MARC fixed field 008) and the free-text data in MARC 546. If we want only the coded data, we should have the parsing look only at MARC field 008.

**Comment by yulgit1** [comment]
That is a good question, I don't know the source from which the dc oai gets its data. But if it does get it from the marc,it looks like you suggest: dc language corresponds to 008 and 546.

https://libapp.library.yale.edu/OAI_BAC/src/OAIOrbisTool.jsp?verb=GetRecord&metadataPrefix=oai_dc&identifier=oai:orbis.library.yale.edu:3561593

https://libapp.library.yale.edu/OAI_BAC/src/OAIOrbisTool.jsp?verb=GetRecord&metadataPrefix=marc21&identifier=oai:orbis.library.yale.edu:3561593

@flapka I think it's your call whether we want only the lang code in dc:language.  If you do want to remove it, I'll see if I can find the parsing code.  If you want to leave it, I'll change the blacklight code to ignore dc:language element that don't contain the 3 letter code.

**Comment by flapka** [comment]
@yulgit1 Either option is fine with me, though I suppose I prefer the latter if it's doable ("change the blacklight code to ignore ...") Thanks!

**Comment by yulgit1** [comment]
dc:language issue resolved with latter from above:
https://git.yale.edu/ermadmix/camel_collections2/commit/62606ac892582f3329c6da98f780f3e176360459

verify after 7/27 ingest

**Comment by edgartdata** [comment]
@yulgit1 I am still working on this with registrars and P&D colleagues. We are trying to figure out why these records were not given a B accession numbers when they were acquired.

**Comment by edgartdata** [comment]
@yulgit1 @flapka Is this issue still open?

**Comment by flapka** [comment]
I think it's finished? Eric will know better than I.

**Comment by yulgit1** [comment]
The dc.language errors were resolved, but @edgartdata I believe it's back in your court about figuring out why these records have unusual inventory numbers.

**Comment by edgartdata** [comment]
@yulgit1 @EdwardTown1 I have suppressed the 24 TMS records listed above (and list attached here as well) and they will not appear in Vufind, BlackLight and any other platforms we programmatically contribute to.
If in the future we need to reinstate them, we can.

[CIA-BLACKLIGHT ODD ACCESSION NUMBERS (Autosaved).xlsx](https://github.com/ycba-cia/blacklight-collections2/files/3980289/CIA-BLACKLIGHT.ODD.ACCESSION.NUMBERS.Autosaved.xlsx)
