### ISSUE TITLE
Exhibition history

### ISSUE THREAD

**Issue by edgartdata** [ycba-cia/blacklight-collections2#142]
@EdwardTown1, today @flapka @mxgold @yulgit1 and @edgartdata discussed the possibility of publishing the exhibition history of the Center's collections in the YCBA online catalog.

TMS is the database of authority for exhibition history and data because it is the central system maintained by the YCBA registrars that documents what art collection and Rare Books & Manuscripts items are included in what exhibition. 

TMS has unique identifiers for its exhibitions.

for example, the William hunter show had 2 RB from the YCBA. This is one of them below: https://orbis.library.yale.edu/vwebv/holdingsInfo?searchId=1148&recCount=50&recPointer=3&bibId=13318536 
![RB record in Orbis for Hunter exhibition](https://user-images.githubusercontent.com/4093644/62796153-7b734480-baa6-11e9-9a91-0e45a94b0329.png)

and this is what it looks like in TMS for the purpose of the exhibition:
![RB record in TMS for Hunter exhibition](https://user-images.githubusercontent.com/4093644/62796175-8928ca00-baa6-11e9-872d-b55f3dba4786.png)

Obviously Orbis has richer metadata for it than TMS, but Orbis does not have exhibition data, and at this point in time does not cross-reference the TMS exhibition unique identifier.

We talked about TMS driven exhibition webpages and how they would relate to the webpages published by the YCBA Exhibitions & Publications department. Here is the one for the Hunter show: https://britishart.yale.edu/exhibitions/william-hunter-and-anatomy-modern-museum 
The TMS driven exhibition webpages could be separate from those from the E&P department, they could add to them with a list of objects and maybe thumbnails for the objects and 
exhibition shots.  

Whatever the decision, there should be a round trip linking mechanism between the exhibition webpages and the detailed object pages.

We talked about the possibility of creating an exhibition facet in BlackLight to filter on specific exhibitions, using Spotlight to create these TMS data driven webpages, and using exhibition shots to document further the physical layout and context of an exhibition.

The consensus is that there is much value from publishing such data and that we will need to collaborate with our colleagues in Exhibitions & Publications, Institutional Archives and Registrars.

**Comment by yulgit1** [comment]
@edgartdata - I tweaked the xslt to capture exhibition history so as to at least get the exhibitions for display in the item page, however the exhibition history is not yet in the dev-lido (which has the config used for blacklight lido).

http://bac6-prod.its.yale.edu/oaicatmuseum/OAIHandler?verb=GetRecord&identifier=oai:tms.ycba.yale.edu:5018&metadataPrefix=lido

http://bac6-dev.its.yale.edu/oaicatmuseum/OAIHandler?verb=GetRecord&identifier=oai:tms.ycba.yale.edu:5018&metadataPrefix=lido

If this is what you want we can ask David to go ahead and put this in dev for blacklight.

Also something that perhaps needs cleaning up, there are repeats in the one I'm testing with (tms:5018), for example:

```
  <lido:eventSet>      
    <lido:displayEvent>This Other Eden : British Paintings from the Paul Mellon Collection at Yale, 1998</lido:displayEvent>
   <lido:event>
    <lido:eventID lido:type="TMS">7</lido:eventID> 
    <lido:eventType>
     <lido:conceptID lido:source="AAT" lido:type="local">300054766</lido:conceptID>
     <lido:term>exhibition history</lido:term>
    </lido:eventType>
   </lido:event>
            </lido:eventSet>    
     
   <lido:eventSet>      
    <lido:displayEvent>This Other Eden : British Paintings from the Paul Mellon Collection at Yale, 1998</lido:displayEvent>
   <lido:event>
    <lido:eventID lido:type="TMS">7</lido:eventID> 
    <lido:eventType>
     <lido:conceptID lido:source="AAT" lido:type="local">300054766</lido:conceptID>
     <lido:term>exhibition history</lido:term>
    </lido:eventType>
   </lido:event>
            </lido:eventSet>    
     
   <lido:eventSet>      
    <lido:displayEvent>This Other Eden : British Paintings from the Paul Mellon Collection at Yale, 1998</lido:displayEvent>
   <lido:event>
    <lido:eventID lido:type="TMS">7</lido:eventID> 
    <lido:eventType>
     <lido:conceptID lido:source="AAT" lido:type="local">300054766</lido:conceptID>
     <lido:term>exhibition history</lido:term>
    </lido:eventType>
   </lido:event>
            </lido:eventSet>
```

**Comment by yulgit1** [comment]
@edgartdata 

One example:
http://10.5.96.187:3000/catalog/tms:5018
Full reindex to occur over the weekend

addressed in: https://github.com/ycba-cia/blacklight-collections2/commit/354ad6db3bf193cd783390c6778712afc624a3af
and
https://git.yale.edu/ermadmix/ycba_xslts/commit/e54e437c15a626c5e94cf7c0cb0887c650728421 

Next steps, 1) add exhibit facet to interface, 2)base it on change in  next comment:

**Comment by yulgit1** [comment]
David,
 
In LIDO DEV for BlackLight, we want to have a concatenation of some of the exhibition elements that we are passing though LIDO.
 
Exhibition data is in <lido:eventSet>
 
Right now in DEV, the title of the exhibition (in the example below, it is Connections, is in 2 different LIDO elements. It is in <lido:displayEvent> and in <lido:appellationValue>.
 
Can we please keep exhibition title as is in <lido:appellationValue> but replace the exhibition title in <lido:displayEvent> with the concatenation for the exhibition.
 
This is showing where the title appears twice in LIDO DEV now:
<lido:eventSet>
<lido:displayEvent>Connections</lido:displayEvent>
<lido:event>
<lido:eventID lido:type="local">757</lido:eventID>
<lido:eventType>
<lido:conceptID lido:type="local">300054766</lido:conceptID>
<lido:term>exhibition</lido:term>
</lido:eventType>
<lido:eventName>
<lido:appellationValue>Connections</lido:appellationValue>
 
The concatenation in <lido:displayEvent> should be:
 
Title of the exhibition (from <lido:appellationValue>), venue (from <lido:eventActor>), exhibition date <lido:displayDate>
 
If it is hard to get the concatenation, can you please hard code a place holder that says “place holder for exhibition display label” so that Eric can keep on testing.

**Comment by yulgit1** [comment]
https://github.com/ycba-cia/blacklight-collections2/commit/68d0db9b35b16b70d2ade1870a569fbde5c18711

@edgartdata @EdwardTown1 
Please see 10.5.96.187:3000
Exhibition history is now a facet, and linkable on the item page.

**Comment by edgartdata** [comment]
@yulgit1 I LOVE the exhibitioni facet! It's so great. thanks!

@flapka I think I remember that you said Orbis does not contain exhibition info for your collection? 

If that is true, can we try to reconcile TMS exhibition info for RB with RB Orbis/BlackLight records?

For example, N8640 .N6+ v. 1 no. 27 Oversize aka http://10.5.96.187:3000/catalog/orbis:13318536 is in the _William Hunter and the Anatomy of the Modern Museum_ exhibition but is currently not coming up as one of the objects of the exhibition in BlackLight.  
@flapka @yulgit1 I am conscious of the risk of getting data from TMS for describing rare books BUT maybe could we reconcile the accession numbers of rare books kept in TMS (for exhibition purposes) with their full fledged records/descriptions in Orbis? Right now we have long descriptive titles for RB in TMS. 

Question for @flapka : would it be possible to list the YCBA works in a selection of catalogs in RB such as http://10.5.96.187:3000/catalog/orbis:13318536 for example?

Question to @yulgit1 : would it be possible to add the titles of exhibitions in the all fields search in BlackLight?

**Comment by edgartdata** [comment]
@yulgit1 @EdwardTown1  I just talked with David and he is going to swap the date at the end of each exhibition concatenation with the specific dates the exhibition was open at each specific venue. So instead of having what looks like repeats, such as:

- An American's Passion for British Art - Paul Mellon's Legacy, Royal Academy of Arts, 2007-2008
- An American's Passion for British Art - Paul Mellon's Legacy, Yale Center for British Art, 2007-2008

they will read:
- An American's Passion for British Art - Paul Mellon's Legacy, Royal Academy of Arts, Apr-18-2007-Jul-29-2007
- An American's Passion for British Art - Paul Mellon's Legacy, Yale Center for British Art, Oct-20-2007-Jan-27-2008

I think this will go a long way towards answering the questions around exhibition info redundancy.

And @yulgit1 thank you so much for reading my mind and making each exhibition label in a record detailed page to be clickable! This is amazing!

**Comment by flapka** [comment]
I too think this facet is great. Additional thoughts:

1. Yes, RB does want its collections associated with exhibitions (in the facet, etc.) in the same manner as art collections.

2. RB records have exhibition data, but not exhaustively. Here's an example: http://10.5.96.187:3000/catalog/orbis:13691415

3. In that example, and others, the information appears in a 585 Exhibition History note, e.g.: 
"585 __ |a Selected exhibitions: "Instruction and Delight: Children's Games from the Ellen and Arthur Liman Collection" (Yale Center for British Art, 17 January-23 May, 2019)." As you can see, the data in their current form may not fulfill our functional requirements (because of syntax). We may need to explore the use of different fields and/or different syntax.

4. I'm open to different approaches, but my preference is to make the MARC descriptions the record of record for RB exhibition data (but could be swayed to other means, if they are more effective). If we use the MARC, we would enlist RB staff to add such information retrospectively.

5. If MARC is the record of record for RB exhibition, what are the precise data requirements (to fulfill functions)? Does the Event ID need to be there (in addition to the string)?

**Comment by edgartdata** [comment]
@yulgit1 I am not sure I understand what the results are when clicking on "Brilliant Effects" [ Jewels ], Yale Center for British Art, 2004 in http://10.5.96.187:3000/catalog/tms:5005 ? It is showing 1 - 100 of 112,313 (http://10.5.96.187:3000/?f[exhibition_history_ss][]=)

**Comment by yulgit1** [comment]
I suspect this is treating quotes in the field as a delimiter.  Let me see if there's a way to encode this.

**Comment by yulgit1** [comment]
@edgartdata - this required escaping to handle the quotes in the title

resolved in https://github.com/ycba-cia/blacklight-collections2/commit/e391e6a177350c78220de25a6acdd1914a7a2d85

**Comment by edgartdata** [comment]
@yulgit1 Perfect!

**Comment by edgartdata** [comment]
@EdwardTown1 I will ask David to filter out "2016 Installation YCBA - 401, Yale Center for British Art" so that it does not appear in the exhibition history of any works.

**Comment by edgartdata** [comment]
@flapka I am worried about this becoming a large data project for RB. Let's talk about this on Friday?

**Comment by yulgit1** [comment]
EDG writes "would it be possible to add the titles of exhibitions in the all fields search in BlackLight?"
@edgartdata - Done.

**Comment by edgartdata** [comment]
After talking with all, it is clear that for many different reasons, TMS is not accurate for the presence of RB materials in YCBA in-house exhibitions. On the other hand, RB has done some work on capturing this information for some exhibitions. Consequently, here is what I'd like to propose:

- Reference the TMS exhibition IDs in the appropriate Orbis records for RB objects included in exhibitions (@flapka can you please let @yulgit1 know which MARC field to get them from?)
- TMS will not try to be the database of authority for RB exhibition information (i.e. there will not be retroactive exhibition cataloguing work done in TMS for RB items)
- @yulgit1 will use the TMS exhibition IDs to lasso RB and art collection objects and bring them together in the same exhibition folder in the Exhibition History facet
- The TMS exhibition IDs for art collection objects are in <lido:eventID lido:type="local">757</lido:eventID>
- Use the exhibitions titles, venues, and begin and end dates as they are documented in TMS and expressed in LIDO as a concatenation in: <<lido:eventSet>>/<<lido:displayEvent>>Connections, Yale Center for British Art, 2011-05-26 - 2011-09-11</lido:displayEvent>

Because it seems that Exhibitions & Publications colleagues are working on fleshing out their exhibitions web pages up to exhibitions organized in 2014, Francis and I are also suggesting that we limit our scope for now until we can share more accurate exhibition information. Consequently, @yulgit1 will filter on <<lido:earliestDate>> 

Here is the list of all 16 in-house exhibitions organized at the YCBA since 1/1/2014: [YCBA exhibitions from 2014 on.xlsx](https://github.com/ycba-cia/blacklight-collections2/files/3610810/YCBA.exhibitions.from.2014.on.xlsx)  I have added a column with TMS exhibitions IDs. I have also added an object count per YCBA department.

In preparing this list, it has become clear that we also need to work with the registrars to make sure that the Venue Begin and End Dates are consitently filled in TMS. Three of these 16 exhibitions also do not have any objects linked to them in TMS.

Question to @EdwardTown1: YCBA art collection objects were included in 164 exhibitions since 1/1/2014, 16 of which were in-house. Do we want to include these loans to external exhibitions in this current effort? I.e. do we want to include exhibitions organized by other institutions that borrowed YCBA works of art (not RB)?

**Comment by edgartdata** [comment]
@yulgit1 Could we sort the exhibitions in the facet in chronological order, with the most recent exhibitions first?

**Comment by yulgit1** [comment]
resolved :https://github.com/ycba-cia/blacklight-collections2/commit/874b5be13b86091627788fc22be095fbe50ad1f7
@edgartdata sorted by start date (first yyyy-mm-dd), please verify

**Comment by edgartdata** [comment]
@yulgit1 I don't think it worked. I see Translations (1993) after English Landscape (1977).
![exhibition facet sort](https://user-images.githubusercontent.com/4093644/65172121-7052f300-da1a-11e9-8278-b9c8546c9387.png)

**Comment by yulgit1** [comment]
@edgartdata - I thought you meant the item page, not the facets.  

Not sure facets are resortable, let me take a look.

**Comment by edgartdata** [comment]
@yulgit1 Oh I love it to for the item page too!. Great idea. But can we please have the exhibitions there sorted with the most recent ones at the top?

**Comment by yulgit1** [comment]
@edgartdata  ok sorted most recent at top (with YCBA document to the top temporality until filtered out)

unfortunately there is a solr constraint that facets are only sortable by count or index

**Comment by edgartdata** [comment]
@yulgit1 Nice! Thanks.
That's too bad about the facet sort.
And I will add David again to filter out the YCBA 2016 installation.

**Comment by flapka** [comment]
@yulgit1 @edgartdata Initial thoughts on mapping:

1. To fulfill functional requirements, I think RB will use MARC field 711 to describe the inclusion of an item in an exhibition. The exhibition ID will appear in subfield 0 [that's a zero]. Here's a full example: 

`711 2_ ‡3 QK495.G74 G73 1800+ ‡i Exhibited in: ‡a 'Of Green Leaf, Bird, and Flower': Artists' Books and the Natural World ‡d (2014 : ‡c Yale Center for British Art) ‡0 (ycba)832 ‡5 CtY-BA`

2. As you can see, the exhibition ID is prepended by "(ycba)". This is required by the MARC standard.

3. If all we need from the MARC is that ID number (that's a big if), then it seems we should create an XSLT template that looks for "(ycba)" in 711 $0 -- and then grabs the number that follows.

4. To complicate matters, other (non-exhibition related) information appears in field 711, and we want to treat such occurrences differently. In the existing xslt, 711 maps (correctly enough) to "author_additional". We want to modify this template so that 711s that contain the "ycba" sting are omitted from "author_additional" while all others 711s are included.

5. For display in detailed record view, I assume we'd want the same as what's already implemented for art collections.

**Comment by flapka** [comment]
For example RB records, here's a set of three:
* http://10.5.96.187:3000/catalog/orbis:11728468
* http://10.5.96.187:3000/catalog/orbis:8818796
* http://10.5.96.187:3000/catalog/orbis:11291910

(I just modified today, so the data may not show up until tomorrow.)

**Comment by edgartdata** [comment]
@flapka @yulgit1 and @edgartdata verified that TMS exhibition IDs come through in Orbis. We talked about the need to create new SOLR index fields for exhibition TMS IDs and exhibition display labels (concatenation of TMS metadata elements). If this solution is too taxing on the SOLR index, we could switch to providing Eric with look up lists of objects per exhibition, but for now we will try this first solution.

We talked about setting up exhibition authority records for the YCBA. They will only include YCBA accessioned works. They too, like BlackLight, will need to grab Orbis RB exhibition data. @edgartdata will develop a LIDO XML template to produce XML files only describing exhibitions separate from and in addition to the current LIDO XML files we have for objects. The question is: what human readable URL should be the dereferenced link for YCBA exhibition authority records? If it is the webpages crafted by the Exhibitions & Publications department, we need to make sure that these webpages have persistent URI. Something to talk about with Rob probably.
https://www.w3.org/2001/sw/wiki/Semantic_Web_terminology
These exhibitions webpages from the Met have a lot of content, some of which YCBA has, some of it not (not sure if they are persistent though): https://www.metmuseum.org/exhibitions/listings/2018/public-parks-private-gardens  

We talked about adding OCLC/WorldCat's exhibition catalog IDs to Orbis for RB materials. In the process, we discovered that some OCLC ID captured in the TMS Bibliography Module are not referenced in the Linked Open Data records of OCLC as shown in the 2 screenshots below.

![OCLC number for YCBA bibliography](https://user-images.githubusercontent.com/4093644/65348853-1ab04f00-dbb0-11e9-9b96-0589a2045b92.png)
![OCLC LOD](https://user-images.githubusercontent.com/4093644/65348854-1ab04f00-dbb0-11e9-9b7b-4a6a97562305.png)

**Comment by yulgit1** [comment]
@flapka are there any examples with multiple 711s?

**Comment by flapka** [comment]
@yulgit1 Here's an example: http://10.5.96.187:3000/catalog/orbis:166089

**Comment by edgartdata** [comment]
@edgartdata to assess the Linked Art data model for exhibitions, then with David P to extend the COBOAT template to accommodate for this additional exhibition data and vend it to LIDO, then work with @yulgit1 to map the exhibition LIDO XML data to RDF.

Keep all the exhibition data in the one single LIDO XML file. Don't produce several XMLs.

**Comment by flapka** [comment]
@edgartdata @yulgit1 The example above (http://10.5.96.187:3000/catalog/orbis:166089) includes an exhibition which I can't find in TMS: Cottage of content ... (1977)

Perhaps it's there and I missed it? Or is this an example of an exhibition that we'll have to create anew in TMS?

**Comment by edgartdata** [comment]
@flapka It is ID 597 in TMS:
![image](https://user-images.githubusercontent.com/4093644/65910258-41e1fa00-e3c2-11e9-9c04-8b33e3953880.png)

**Comment by flapka** [comment]
Thank you @edgartdata !  @yulgit1 My sample records now have the correct exhibit IDs.

**Comment by yulgit1** [comment]
resolved:
https://git.yale.edu/ermadmix/ycba_xslts/commit/c4b51e07812c470a9807415362f93a22340a5594
https://git.yale.edu/ermadmix/ycba_xslts/commit/cd5f1dd96e7a9e97f32af1ae64be9375d6d329a0
https://git.yale.edu/ermadmix/ycba_xslts/commit/b6244db93f66903fa95d39fdfe8e8b605f30b2a3
https://git.yale.edu/ermadmix/camel_collections2/commit/ff90e506b3e488373cfb8b426825024ab82c8fbc

test objects:
http://10.5.96.187:3000/catalog/orbis:166089
http://10.5.96.187:3000/catalog/orbis:11728468
full reindexing next weekend

**Comment by yulgit1** [comment]
@flapka, @edgartdata -  I made the changes and applied to test objects above.  However exhibit 597 has no lido objects (this in is orbis:166089), so the lookup doesn't work (using the exhibit ID from marc and matching to a title from lido).  Just has missing title for 597.

Is there a plan B? Perhaps have a manually curated exhibititionID->title lookup for ones like 697 w/o a lido object (assuming only a handful to curate) or some other solution? Let me know.

**Comment by yulgit1** [comment]
For reference saving a reference to the results of the lookup, matching exh_id with title from lido.

To use do a find on id, and see the corresponding array, (some traveling exhibits have more than 1 title per id)
https://gist.github.com/yulgit1/bab654b767d65e699985e46e553393b5

**Comment by flapka** [comment]
@yulgit1 One possibility: In those cases where we can't match on a title from LIDO, could we simply use the title as found in the MARC -- concatenating 711 subfields a, d & c (in that order)?

**Comment by yulgit1** [comment]
@flapka - I like that idea! I just implemented with:

https://git.yale.edu/ermadmix/camel_collections2/commit/61775074d49cbf98a76f8bd4f3f9d90d18fa2e16
and
https://git.yale.edu/ermadmix/ycba_xslts/commit/ab31ac77604e364b46965dbc147c8261cbac54fa

As a test here is one where the exhibition_history_ss has both a title from the lido lookup, and another title falling back on the marc title as there is no lido object in the exhibition to lookup:
http://10.5.96.187:3000/catalog/orbis:166089.json

As long as the 711 adc exhibit info are consistent across marc objects this should work.

full reindexing over the weekend

**Comment by flapka** [comment]
@yulgit1 Excellent.

**Comment by edgartdata** [comment]
Looking forward to seeing this in action!

**Comment by yulgit1** [comment]
added exhibition history for marc records on the item page
https://github.com/ycba-cia/blacklight-collections2/commit/f0204fefe4bd7f40d2c53d991b0f68e0dfae7c30

**Comment by yulgit1** [comment]
@flapka @edgartdata - Please check out exhibitions, facets and item page (specifically RBs).

After full indexing there are 9 total RB with exhibition history now, the harmonized Green Leaf and Pleasures and Pastimes, and the Marc formatted Cottage of Content (no tms objects in this exhibit).  Also looks like some redundancy of exhibition history and notes, don't know if there should be some suppression of notes in this case.

**Comment by flapka** [comment]
Looks quite correct. Excellent!

As you've noted, we're evaluating the utility of the at-least-semi-redundant exhibition *notes*. We may delete them.

**Comment by edgartdata** [comment]
@flapka Would it be doable for RB only exhibitions to adopt the same format as art exhibitions, without becoming a data project?

For example:
Cottage of Content, or, Toys, Games, and Amusements of Nineteenth Century England (1977 : Yale Center for British Art)
would become:
Cottage of Content, or, Toys, Games, and Amusements of Nineteenth Century England, Yale Center for British Art, 1977 
on the model of:
Pleasures and Pastimes, Yale Center for British Art, 1990-02-21 - 1990-04-29

I assume that you are researching the y-m-d dates for RB only exhibitions? You actually have the granular dates in http://10.5.96.187:3000/catalog/orbis:183240 so I wonder if having only the years is a function of Eric's harvesting script?

**Comment by yulgit1** [comment]
@edgardata,@flapka - My script is pulling together from 711 subfields as instructed. In orbis:183240 the granular dates are from a 585 subfield a text entry (which could be leveraged per Francis's discretion I guess).  The catch is I'm not sure it's consistent in a way to invoke a regular expression to format like the art exhibition labels.

**Comment by flapka** [comment]
The string in that form -- Title (Date : Venue) -- follows library cataloging guidelines for Exhibition names. It'd be nice to comply with the standard, but I also understand the appeal of a common form/syntax. Since I've only begun to enter exhibition history as a relationship (heading) instead of a note, data cleanup isn't really an issue. 

Do we have confirmation from stakeholders outside of CIA that we definitely want exhibitions named in the form: Title, Venue, Date?

Also: Have we considered how we want to order the exhibition listing (in an object view). Alphabetically? Chronologically?

**Comment by flapka** [comment]
@yulgit1 I notice now that all (?) RB records have the exhibition history label, including items without an exhibition association. Example: http://10.5.96.187:3000/catalog/orbis:579220 

Can we make the label (and double-click instruction) disappear for items without such a history?

**Comment by edgartdata** [comment]
@flapka In a object record, the exhibitions are now listed chronologically, with the most recent ones at the top.

I am open to other formats for exhibitions, although somewhat restricted by what TMS exhibition data there is. A good topic for friday!

**Comment by yulgit1** [comment]
@flapka regarding your comment 2 comments above - this is odd, blacklight native methods should  filter this, had to apply a workaround: https://github.com/ycba-cia/blacklight-collections2/commit/5a82a0d90c093a32d43e1136ead7a56b7eddb598

let me know if anything is amiss

**Comment by flapka** [comment]
@yulgit1 Thanks, looks better. 

@edgartdata Happy to discuss more on Friday.

**Comment by edgartdata** [comment]
Consensus ond the exhibition citation format for art and RB collections:
title, (venue, granular venue dates spelled out): The Cottage (Yale Center for British Art, November 2-December 31, 1977)

RB: interest in recording bib citation in the same way the art collection does. OCLC identifier. More work needed on how to harmonize bib citations between departments.

Discussion on in-house and non in-house until 2014.

Keep the heading of Exhibition History in the facet and in the detailed record per Ed.

Historical exhibitions, pre-1977: who will be creating their TMS records?

How to make sure that each exhibition has a catalog and vice-versa?

Sort the exhibitions in the detailed object record chronologically with the most recent ones first.

Same chron order for bibliography with most recent ones first. 

Bibliography management in TMS: do we want a flag for exhibition catalog. 

Think about a flag to indicate the most important citations in the BlackLight detailed records, like the catalog raisonne. 

Look into italicizing titles in TMS and in BL.

**Comment by flapka** [comment]
@yulgit1 @edgartdata To confirm what EDG describes above, for the data in MARC our earlier proposal was this:

`711 2_ ‡3 GV1199 A4 ‡i Exhibited in: ‡a Cottage of Content, or, Toys, Games, and Amusements of Nineteenth Century England ‡d (1977 : ‡c Yale Center for British Art) ‡0 (ycba)597 ‡5 CtY-BA`

Our revised approach would be this:

`711 2_ ‡3 GV1199 A4 ‡i Exhibited in: ‡a Cottage of Content, or, Toys, Games, and Amusements of Nineteenth Century England ‡c (Yale Center for British Art, ‡d November 2-December 31, 1977) ‡0 (ycba)597 ‡5 CtY-BA`

For those cases when we need to concatenate the string from MARC, we'd now do: 711 subfields a, c & d (in that order)

Is all of this correct (and final)?

**Comment by edgartdata** [comment]
Following up on the issue around italicization of titles of exhibitions and bib citations. 

We are currently using slashes around titles of bib citations in our LIDO XMLs for Vufind: 

<lido:displayObject>
/Britain in the world: Highlights from the Yale Center for British Art in honor of Amy Meyers, /Yale University Press, New Haven, London, p. 68, N6761 .Y33 2019 (LC) (YCBA)
</lido:displayObject>

While it works for Vufind, I do wonder what the external services that receive our data make of this idiosyncratic use of punctuation. Probably not all that schema compliant either.

It seemed from our conversation last week that italicizing some parts of concatenations would help with providing some clarity in the exhibition history and publications but I am not sure TMS and XML are the most efficient way to do that?

**Comment by yulgit1** [comment]
@edgartdata - just noticed lido has 2 fields - displayObject (w/ italic markup) & objectNote (w/o markup), so external services that don't want the rendering markup can use objectNote.  Do we want the same for exhibition_history (italic, or italic+unformatted), or leave as is?

FWIW here's a screen shot with italics turned on:
<img width="1049" alt="Screen Shot 2019-10-17 at 5 05 43 PM" src="https://user-images.githubusercontent.com/2125400/67047853-1e78b800-f101-11e9-855c-f61370492f7f.png">

**Comment by yulgit1** [comment]
@flapka - happy to implement the revised you suggest (711 subfields a, c & d (in that order))

But should dates be normalized to' yyyy-mm-dd' rather than 'MONTH dd, yyyy' (or vice-versa)

**Comment by edgartdata** [comment]
@edgartdata Work on normalization of dates with David Parsell first.

**Comment by edgartdata** [comment]
@edgartdata reinstate LIDO objectNote element to allow for title formatting.

**Comment by edgartdata** [comment]
@flapka Very slight change in the exhibition label display: the hyphen in the date range is now a en-dash rather than a hyphen, and will thus read as such: 

The Cottage (Yale Center for British Art, November 2, 1977–December 31, 1977)

**Comment by edgartdata** [comment]
@yulgit1 Just noting that since the italics markup is already available in displayObject for bibliographic citations, feel free to render the italics in BlackLight whenever you have a chance. 

As mentioned above, I am working with David to reinstate the objectNote LIDO element. It will carry the bib citations without the italics markup for external services that might want the citations without italics.

**Comment by flapka** [comment]
@edgartdata Using the en dash is good, but: to the best of my knowledge, it is not a valid character in Voyager (that's me banging my head on the wall). 

Is there any harm in still using the hyphen for the strings in MARC, since any cited exhibition that has a LIDO equivalent will substitute the string from LIDO anyway?

**Comment by edgartdata** [comment]
@yulgit1 I see that the 1985-86 "Sir Joshua Reynolds" exhibition that went to 2 venues does not sort chronologically like the other exhibitions. The 1985 Reynolds show at the Réunion des Musées Nationaux shows first (before the 2015 show at YUAG) and the 1986 Reynolds show at the Royal Academy shows last. I have looked at the TMS records and I can't see what is going on. Any ideas?

![exhibition sort in detailed record](https://user-images.githubusercontent.com/4093644/67521719-66f02280-f679-11e9-9945-08212b8e41ae.png)

**Comment by yulgit1** [comment]
This is a result of the sort which sorts by the first occurrence of dddd-dd-dd descending.  That first Sir Joshua has format dddd-dd, so it doesn't get sorted and shows up first.  In other words anything that doesn't match to a 'dddd-dd-dd' shows up first.

**Comment by yulgit1** [comment]
added italics to publications (not technically exhibition history but recording here)
https://github.com/ycba-cia/blacklight-collections2/commit/620c404a8e77819d3e20f9964bf6ce3866485800

**Comment by yulgit1** [comment]
sort exhibition history desc based on <month word> dd, yyyy.

In: https://github.com/ycba-cia/blacklight-collections2/commit/4c705c08e2345215c4c6a408fa34cf8f2631c621

**Comment by yulgit1** [comment]
added forced stop of italics at end of each publication, in case italic typo
In: https://github.com/ycba-cia/blacklight-collections2/commit/e3a4cdcfb35ca9b7c68c8360bf4f97aa64997c13

**Comment by edgartdata** [comment]
@yulgit1 Minor issue: transforming the -- into a dash.
Example: James Ward (Yale Center for British Art, May 21, 2004--August 22, 2004)

**Comment by edgartdata** [comment]
Issue: how to ensure that YCBA exhibitions that only include RBMS items can still be published to BlackLight (such as 'Printing in England).

Solution: cache the TMS exhibitionIDs and titles of these RBMS only exhibitions in BlackLight SOLR (@flapka notes that per his research, so far he has come across 10 such exhibitions).

Steps: @edgartdata to create placeholder TMS exhibition records for such RBMS only exhibitions (YCBA registrars note that there are already such placeholder TMS exhibition records for pre-TMS exhibitions, for the purpose of linking images for example). These new placeholder TMS exhibition records will not link to any TMS RBMS records (no new RBMS object records will be created in TMS for the purpose of these past exhibitions), but these placeholder TMS exhibition records must include a title. Ideally, it is recommended that they also mention dates and venues (this will help for disambiguation in the future).

This solution helps consolidate TMS as the database of authority for YCBA exhibition history, even though some of these past/historical TMS exhibition records will not have any objects linked to them. 

@edgartdata will research how to assign a clear/prominent TMS status flag to such RBMS historical exhibitions: EDG to check for documenting that they are historical  markers only and not full exhibition documentation

**Comment by flapka** [comment]
@edgartdata 

Here are two examples of (predominantly) RBM exhibitions not in TMS:

The Mapmaker's Art: 300 Years of British Cartography (Yale Center for British Art, January 17, 1989-March 12, 1989)

Color Printing in England, 1486-1870 (Yale Center for British Art, April 20, 1978-June 25, 1978)

**Comment by edgartdata** [comment]
@flapka @yulgit1 
I have just created 2 new TMS exhibition records for these 2 RBMS only exhibitions:

- The Mapmaker's Art: 300 Years of British Cartography (Yale Center for British Art, January 17, 1989-March 12, 1989) - TMS EXHIBITIONID: **1048**


- Color Printing in England, 1486-1870 (Yale Center for British Art, April 20, 1978-June 25, 1978) - TMS EXHIBITIONID: **1049**

Both exhibition records now have:

- exhibition title

- exhibition begin & end dates

- exhibition display date

- exhibition venue (YCBA)

- this disclaimer in the Remarks field: THIS EXHIBITION ONLY INCLUDED RBMS. ITS TMS RECORD WAS CREATED IN 2020 FOR THE PURPOSE OF DISPLAYING ITS TITLE AND DATES IN BLACKLIGHT.
![TMS RBMS only exhibition record](https://user-images.githubusercontent.com/4093644/79879161-56b4c800-83bc-11ea-966a-2a25330ba1d8.png)

Let me know if the records need anything else for BlackLight.

**Comment by flapka** [comment]
Thanks @edgartdata. That should be everything I need to proceed. I'll have Bonnie work on adding data for those two exhibitions.

**Comment by yulgit1** [comment]
@flapka - can you provide some examples of RBs in the Mapmakers Art & Color Printing exhibitions?

**Comment by flapka** [comment]
@yulgit1 Sure. 

Mapmaker's art: http://ycba-collections-dev.herokuapp.com/catalog/orbis:12283779

Color printing: http://ycba-collections-dev.herokuapp.com/catalog/orbis:16042

For both, you'll notice a small glitch in the order of information.
* Appears as: Color Printing in England, 1486-1870 April 20, 1978-June 25, 1978) (Yale Center for British Art,
* Should be: Color Printing in England, 1486-1870 (Yale Center for British Art, April 20, 1978-June 25, 1978)

In the glitch, the MARC 711 subfields are mapped in the order a d c. Order should be a c d.

That same ordering glitch impacts other data too, e.g. Cottage of content: http://ycba-collections-dev.herokuapp.com/catalog/orbis:172300

**Comment by yulgit1** [comment]
@flapka - fixed the subfield order and reindexed:

https://git.yale.edu/ermadmix/ycba_xslts/commit/536e1e9488b66d318509f013c117e3ea588cbbc9

look ok?

**Comment by flapka** [comment]
@yulgit1 Yes, the order now looks fixed. Thanks!

**Comment by edgartdata** [comment]
@flapka Okay to close this issue?

**Comment by flapka** [comment]
Yes, thanks.

**Comment by flapka** [comment]
@yulgit1 For reasons too dull to mention, I have to make a small change to data in RB describing exhibitions. This will require a parallel change in our XSLT template for ""exhibit_title"

Where that template currently says: <xsl:if test="starts-with($exh_indicator,'(ycba)')">

Please change to: <xsl:if test="starts-with($exh_indicator,'(CtY-BA)')">

I.e., change **ycba** to **CtY-BA**.

Thanks, and sorry for the trouble.

**Comment by flapka** [comment]
@yulgit1 Sorry, I see that parallel changes are required in two other templates:

* In the "exhibit_history" template, there are two instances of **ycba**, both of which should be changed to **CtY-BA**.
* In the "author_additional" template, there is one instance of **ycba**, which should be changed to **CtY-BA**.

Thanks again.

**Comment by yulgit1** [comment]
Addressed:
https://git.yale.edu/ermadmix/ycba_xslts/commit/9725868e80798582d1c0d6bdef483e1d9f95bc10

Won't show up soon, Indexing is currently off, working on a firewall issue related to https://github.com/ycba-cia/blacklight-collections2/issues/277
Not sure how long it will take.

**Comment by flapka** [comment]
Looks good. If I make a batch change to the MARC data now (with Youn's help), these records will be re-indexed after indexing is turned back on, right?

**Comment by yulgit1** [comment]
correct, and still haven't heard from ITS about firewall....
