### ISSUE TITLE
On view status added to records detailed view

### ISSUE THREAD

**Issue by edgartdata** [ycba-cia/blacklight-collections2#147]
@EdwardTown1 @flapka @yulgit1 How would you feel about adding "on view" or "not on view" to the detailed records of objects that are in a public location in YCBA?  (This idea is suggested by Nancy MacGregor, our registrar). And if we are in favor or it, where in the record? Just before Export maybe?

**Comment by flapka** [comment]
@edgartdata Would the display also indicate where the item is on view -- specifying a floor for example?

**Comment by edgartdata** [comment]
We could but it will require some data massaging & processing as the locations labels as recorded in TMS are not intuitive & ready for public consumption. Example: YCBA, 401, Bay01

**Comment by edgartdata** [comment]
@EdwardTown1 @flapka @yulgit1 Reposting this issue to see where we stand on it.

**Comment by yulgit1** [comment]
The "on view/not on view" field is used in the facets can be displayed on the item pages with a simple configuration change. 

To be more explicit, I believe lido is already exposing the "YCBA, 401, Bay01" info in different elements that could be concatenated and mapped to a field for display.

So it seems like a 'why not?' to me.  I defer to other's opinions.

**Comment by yulgit1** [comment]
added on view on item page: https://github.com/ycba-cia/blacklight-collections2/commit/620c404a8e77819d3e20f9964bf6ce3866485800
