### ISSUE TITLE
Inscription(s) /Marks/ Lettering:

### ISSUE THREAD

**Issue by edgartdata** [ycba-cia/blacklight-collections2#154]
@yulgit1 In a detailed object record page, can we please change the heading "Inscription(s) /Marks/ Lettering:" to become "Inscription(s)/Marks/Lettering:"? Which is the same heading minus the spaces around the forward slashes.
11929 has inscriptions and would show this field in its detailed record.

Thank you.

**Comment by yulgit1** [comment]
resolved:
https://github.com/ycba-cia/blacklight-collections2/commit/620c404a8e77819d3e20f9964bf6ce3866485800
