### ISSUE TITLE
Images of Reference Library items

### ISSUE THREAD

**Issue by edgartdata** [ycba-cia/blacklight-collections2#158]
I just noticed that images from the Reference Library show in the list of results, but not in the detailed item records. I assume we want them to carry over to the detailed records? @KraigBinkowski 
http://10.5.96.187:3000/catalog/orbis:12838837
![Ref Lib image](https://user-images.githubusercontent.com/4093644/69164170-7bc7a680-0abd-11ea-833e-62d37795493e.png)

**Comment by yulgit1** [comment]
@edgartdata, @KraigBinkowski  This is not one of our images, but a book cover thumbnail pulled by isbn from openlibrary, google, or amazon service, hence not an image on the item page.

**Comment by edgartdata** [comment]
Is that something new? I see that that item does not have an image in Vufind.

**Comment by KraigBinkowski** [comment]
I think this has always been the case - though the image is currently pulled into the full record. 

Also, in the new version I noticed that after the call number field the following note is displaying: 
[Request for use in the YCBA Study Room] -- which should not be the case.

Also - there is still the "Request photography" link at the top which I thought we talked about removing for Ref collection items?

**Comment by flapka** [comment]
@yulgit1 @KraigBinkowski @edgartdata 

I belatedly notice that thumbnail images pulled from external sources (based on ISBN) are also displaying for RB items, in search results -- which isn't the desired outcome. We want images only from our own source (of our own copy of a book).

Example in [Blacklight](http://ycba-collections-dev.herokuapp.com/?utf8=%E2%9C%93&search_field=all_fields&q=miura+tini+1991); compare same in [Vufind search results](https://collections.britishart.yale.edu/vufind/Search/Results?join=AND&lookfor0%5B%5D=miura+tini+1991&type0%5B%5D=allfields&bool0%5B%5D=AND&lookfor1%5B%5D=&type1%5B%5D=title&bool1%5B%5D=AND&lookfor2%5B%5D=&type2%5B%5D=auth_author&bool2%5B%5D=AND&lookfor3%5B%5D=&type3%5B%5D=earliestDate&bool3%5B%5D=AND&lookfor4%5B%5D=&type4%5B%5D=topic&bool4%5B%5D=AND&lookfor5%5B%5D=&type5%5B%5D=geographic&bool5%5B%5D=AND).
