### ISSUE TITLE
changes to Reference Library item page

### ISSUE THREAD

**Issue by yulgit1** [ycba-cia/blacklight-collections2#159]
1) Eliminate the “Request for use in the YCBA Study Room” note for all ref items.
 
2) Discuss whether to remove the “request photography” link as well for all the ref materials.

**Comment by yulgit1** [comment]
resolved (1) https://github.com/ycba-cia/blacklight-collections2/commit/64f5cf3aeaf3cdf3fc8790f5dfddfa3f5c012a3a
resolved (2) with: https://github.com/ycba-cia/blacklight-collections2/commit/f8d330b99686680eea50d2df4082d23095f460c3

**Comment by edgartdata** [comment]
Done.
