### ISSUE TITLE
Image size facet?

### ISSUE THREAD

**Issue by edgartdata** [ycba-cia/blacklight-collections2#161]
An idea: would it be helpful for users to be able to select the size of images?
The use case I have in mind is this: people interested in images of copyrighted works that we make available as larger than thumbnail size, such as Nick Mead's _Untitled 3_ http://ycba-collections-dev.herokuapp.com/catalog/tms:67304
Right now, users have to go through records one by one or chance upon these large images of copyrighted works. Do we think that there are enough of these to create a facet?  I think it would be a nice way to call attention to living artists who are being generous with the Center. But again, maybe there are not enough of such cases to warrant more work on this.

**Comment by flapka** [comment]
I see some appeal in indicating the size of image immediately available (e.g. thumbnail, full-size). But given that full-size images are available upon request for many objects for which we serve only thumbnails to the catalog, is there a danger that a facet indicating image size might give the wrong impression to some users (e.g. that only a thumbnail is available, full stop)?

**Comment by edgartdata** [comment]
@flapka I see what you mean. So maybe this functionality/facet would only be useful for the art collection? @mxgold curious to take your take on it.

**Comment by edgartdata** [comment]
Not enough material for such a facet.
