### ISSUE TITLE
Remove bookmarks, history, login from search bar

### ISSUE THREAD

**Issue by edgartdata** [ycba-cia/blacklight-collections2#164]

**Comment by yulgit1** [comment]
resolved: https://github.com/ycba-cia/blacklight-collections2/commit/5aec702dbdae2a23e1343bdac263d9ace63ccc48

**Comment by edgartdata** [comment]
Done but removing the Bookmark button takes away that functionality from BlackLight altogether. The consensus is that it is okay for now.

**Comment by yulgit1** [comment]
also suppressing bookmark selection box on List results view:

https://github.com/ycba-cia/blacklight-collections2/commit/3e39e83ffe2dde4fd5498438e0fb2ca65ca70a2e
