### ISSUE TITLE
Image not yet available 

### ISSUE THREAD

**Issue by edgartdata** [ycba-cia/blacklight-collections2#165]
and change the background to white.

**Comment by yulgit1** [comment]
feedback on language and color (current vs new below)?

<img width="1225" alt="Screen Shot 2019-12-20 at 11 48 00 AM" src="https://user-images.githubusercontent.com/2125400/71277652-7ad79e00-2323-11ea-8a47-46ec22eed399.png">
<img width="1232" alt="Screen Shot 2019-12-20 at 12 21 57 PM" src="https://user-images.githubusercontent.com/2125400/71277662-8034e880-2323-11ea-8b0c-9ca8dad68f46.png">

**Comment by yulgit1** [comment]
I like the original darker grey actually.

**Comment by edgartdata** [comment]
@yulgit1 I like the lighter gray better!

**Comment by flapka** [comment]
Me too (the lighter gray). Could we see how it looks when mingled with search results that include images?

**Comment by yulgit1** [comment]
<img width="1294" alt="Screen Shot 2019-12-20 at 2 44 54 PM" src="https://user-images.githubusercontent.com/2125400/71287848-66050580-2337-11ea-95bd-ab77955e60c9.png">

**Comment by edgartdata** [comment]
@yulgit1 I like it!

**Comment by yulgit1** [comment]
ok, will let @EdwardTown1 and others a chance weigh in

**Comment by edgartdata** [comment]
@EdwardTown1 Just a reminder to weight in on this when you have a chance. Thanks.

**Comment by edgartdata** [comment]
@EdwardTown1 agrees with the light grey option.

**Comment by yulgit1** [comment]
addressed https://github.com/ycba-cia/blacklight-collections2/commit/a873c299860950347c5311a2dcb630dc29948cd3
