### ISSUE TITLE
Improve "unknown" copyright label in object view (RBM)

### ISSUE THREAD

**Issue by flapka** [ycba-cia/blacklight-collections2#167]
@yulgit1 @edgartdata @mxgold 

For library material, if an item has copyright status "unknown" the label "unknown" appears beneath the image, as in this example: http://ycba-collections-dev.herokuapp.com/catalog/orbis:11619343

For art collections, if an item has copyright status "unknown" the label "Copyright Information" appears beneath the image, as in this example: http://ycba-collections-dev.herokuapp.com/catalog/tms:20053

What do we need to revise so that the "Copyright Information" label appears with library collections as well?

**Comment by yulgit1** [comment]
@flapka -see code below, the field here is ort_ss, looks like "unknown" should change to "Copyright Information"?  If this makes sense should the change apply to rights_ss as well?

Also there might be a mistake.  ort_ss gets populated from 542f but the code that adds the current "unknown" is checking 542l.  Does that make sense?
        
<xsl:if test="not(marc:datafield[@tag='542']/marc:subfield[@code='l'])">
            <xsl:element name="ort_ss">
                <xsl:text>unknown</xsl:text>
            </xsl:element>
            <xsl:element name="rights_ss">
                <xsl:text>unknown</xsl:text>
            </xsl:element>
            <xsl:element name="rightsURL_ss">
                <xsl:text>http://hdl.handle.net/10079/c59zwbm</xsl:text>
            </xsl:element>
        </xsl:if>

                <xsl:for-each select="marc:subfield[@code='f']">
                    <xsl:value-of select="normalize-space(.)"/>
                </xsl:for-each>
            </xsl:element>

**Comment by mxgold** [comment]
Out of office/Traveling now but will weigh in more detail tomorrow!

Thanks and apologies-
Melissa

Sent from my iPhone

On Dec 18, 2019, at 4:39 PM, yulgit1 <notifications@github.com<mailto:notifications@github.com>> wrote:


@flapka<https://nam05.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fflapka&data=02%7C01%7Cmelissa.fournier%40yale.edu%7C6d4d3425ccda429dfdb308d78402b8a5%7Cdd8cbebb21394df8b4114e3e87abeb5c%7C0%7C0%7C637123019537510268&sdata=QaR2s8u3bLocDO1OgT0k5ci7F8Hr9brwLc%2BEah7s4VM%3D&reserved=0> -see code below, the field here is ort_ss, looks like "unknown" should change to "Copyright Information"? If this makes sense should the change apply to rights_ss as well?

Also there might be a mistake. ort_ss gets populated from 542f but the code that adds the current "unknown" is checking 542l. Does that make sense?

<xsl:if test="not(marc:datafield[@tag<https://nam05.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Ftag&data=02%7C01%7Cmelissa.fournier%40yale.edu%7C6d4d3425ccda429dfdb308d78402b8a5%7Cdd8cbebb21394df8b4114e3e87abeb5c%7C0%7C0%7C637123019537510268&sdata=kMdIUWfOlpxTIwQDfnGMkw81J2Y%2BdQYNcPMiWGrxTLw%3D&reserved=0>='542']/marc:subfield[@code<https://nam05.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fcode&data=02%7C01%7Cmelissa.fournier%40yale.edu%7C6d4d3425ccda429dfdb308d78402b8a5%7Cdd8cbebb21394df8b4114e3e87abeb5c%7C0%7C0%7C637123019537520263&sdata=D%2F6Q8DngLAJX5vDmjXhOo%2F1HoWDRjuAqJURkwBKVWnw%3D&reserved=0>='l'])">
<xsl:element name="ort_ss">
xsl:textunknown</xsl:text>
</xsl:element>
<xsl:element name="rights_ss">
xsl:textunknown</xsl:text>
</xsl:element>
<xsl:element name="rightsURL_ss">
xsl:texthttp://hdl.handle.net/10079/c59zwbm<https://nam05.safelinks.protection.outlook.com/?url=http%3A%2F%2Fhdl.handle.net%2F10079%2Fc59zwbm&data=02%7C01%7Cmelissa.fournier%40yale.edu%7C6d4d3425ccda429dfdb308d78402b8a5%7Cdd8cbebb21394df8b4114e3e87abeb5c%7C0%7C0%7C637123019537520263&sdata=yOnuApBHnu83DzeB8yN97%2FRSt2eSprOL6R8EcC0i92Y%3D&reserved=0></xsl:text>
</xsl:element>
</xsl:if>

            <xsl:for-each select="marc:subfield[@code='f']">
                <xsl:value-of select="normalize-space(.)"/>
            </xsl:for-each>
        </xsl:element>

**Comment by flapka** [comment]
Here's a related issue, now closed: https://github.com/ycba-cia/blacklight-collections2/issues/167

In general, it is correct for that label to map from MARC 542 $f (= Copyright Statement), as it does already. 

My discomfort is this: When the copyright is unknown, we apparently want the label "Copyright Information" to show up with that link -- which is quite reasonable. But "Copyright Information" is *not* a copyright statement. I'd prefer that "Copyright Information" not be hard-coded into a field where the semantics expect something else (e.g. "Copyright unknown" or "Copyright unidentified"). To my mind, it'd be better to auto-generate the link text "Copyright Information" whenever the rights_ss=unknown.

Looks like "Copyright Information" is hard-coded in TMS/LIDO, is that correct?

Am I being too fussy, @mxgold @edgartdata?

**Comment by yulgit1** [comment]
Will hear from others about Francis' hardcoding question, but regarding these 2 comments:

"In general, it is correct for that label to map from MARC 542 $f (= Copyright Statement), as it does already." 
"(Likewise, whenever a MARC record lacks 542 data, the xslt could supply rights_ss="unknown" and ort_ss="Copyright Information")"

I can change ort_ss to "Copyright Information" for lacking 542 as you suggest.  But revisiting this question, is it for lacking 542 $f or 542 $l? Or does it kind of works either way (the subfields are in tandem)?  Currently it's implemented as 542 $l.  @flapka please let me know.

Also there is an additional layer of logic in the interface that displays "unknown" when there is no ort_ss.  Given the XSLT as is there should always be an ort_ss for MARC based records so it should never reach this point.  For LIDO not sure if this would ever be missing entirely.  Just bringing this up FYI, I don't remember the rationale for coding it this way.

**Comment by flapka** [comment]
@yulgit1 In general, if our record has a 542 field it will always include both subfields, $f and $L, where $L supplies the coded rights value (used in the facet?) and $f provides the statement to be displayed beneath the image. Does that answer your (first) question?

**Comment by yulgit1** [comment]
Yes @flapka , if my understanding is correct the only change to be made is "unknown" to "Copyright Information" in the absence what is now 542 $l.

**Comment by flapka** [comment]
RB will modify practice to conform to art collections practice. So:
* when we do add 542 fields for items of unknown copyright, we will keep “unknown” as subfield $L (rights) and then enter “Copyright Information” in $f (ort)
* for those records for which we have not yet added a 542 field, the xslt will supply “unknown” for right and “Copyright Information” for ort

**Comment by yulgit1** [comment]
Bullet point 2 addressed: https://git.yale.edu/ermadmix/ycba_xslts/commit/9daa984e7495473d75a0f015e759bb6043ab4e5f

to be confirmed after next reindexing

**Comment by yulgit1** [comment]
@flapka - indexing complete, please confirm this is as you specify

**Comment by flapka** [comment]
@yulgit1 Spot-checking, this looks correct. Thank you! I will click "close and comment."
