### ISSUE TITLE
Move caption and other elements into one line below the image

### ISSUE THREAD

**Issue by edgartdata** [ycba-cia/blacklight-collections2#171]
@yulgit1 In the detailed record, please have the following elements in one line in that order under the image:
- IPTC keywords (recto, verso,...)
- object rights status
- request additional photography
- print object
- download selected image
- iiif

@flapka I am not sure we talked about what to do when the IPTC keywords/caption is very long as with http://ycba-collections-dev.herokuapp.com/catalog/orbis:11411486

**Comment by yulgit1** [comment]
<img width="1258" alt="Screen Shot 2020-01-10 at 5 18 23 PM" src="https://user-images.githubusercontent.com/2125400/72190441-8d4a7200-33cd-11ea-9c26-9ed29f907b88.png">
<img width="1324" alt="Screen Shot 2020-01-10 at 5 18 43 PM" src="https://user-images.githubusercontent.com/2125400/72190461-99363400-33cd-11ea-8faa-5e73366de8e5.png">
<img width="1314" alt="Screen Shot 2020-01-10 at 5 20 18 PM" src="https://user-images.githubusercontent.com/2125400/72190473-9cc9bb00-33cd-11ea-9811-1ecab3ec10b5.png">
<img width="1294" alt="Screen Shot 2020-01-10 at 5 20 28 PM" src="https://user-images.githubusercontent.com/2125400/72190478-9f2c1500-33cd-11ea-9e71-33588cbb9f3d.png">

**Comment by yulgit1** [comment]
See "before" and "after" above.  Implemented now as "after".

I left  IPTC keywords centered below the image.  It looked horrible in the row.  And made "Download Selected Image" a link rather than button, as it didn't scale to mobile view in a row.

Opinions, keep? Revert?

**Comment by flapka** [comment]
Seems clunkier than what we had before, and I can't think of an obvious answer.

A small suggestion: the "Print Object" link could be moved farther down in the record, near the Export options? That might slightly ease our graphic design challenge.
