### ISSUE TITLE
Add tombstone info above the main image in detailed record

### ISSUE THREAD

**Issue by edgartdata** [ycba-cia/blacklight-collections2#172]
@yulgit1 Please add the name of the artist/author, the title (bolded), and the date of creation/publication (separated by commas) in one line above the main image.
It is okay to shorten long titles.
It is okay to drop the nationality and life dates of the artist/author.

Inspiration for this from Tate: https://www.tate.org.uk/art/artworks/bacon-three-studies-for-figures-at-the-base-of-a-crucifixion-n06171

**Comment by yulgit1** [comment]
addressed:https://github.com/ycba-cia/blacklight-collections2/commit/6c2b49fee4c813544b21ef4c280b5460f79ff987

**Comment by edgartdata** [comment]
Hi @yulgit1 when you have a minute, can you please add a comma after the artist's name and after the title? thanks.

**Comment by flapka** [comment]
I agree, this is a good change. Two comments:

I think the top tombstone info would benefit from more padding (white space), especially between the info and the image, where there's very little space.

There are small issues with tombstone data for library material. See this example: http://ycba-collections-dev.herokuapp.com/catalog/orbis:12673002. Where it currently reads "Darly, M. (Mary), engraver., Hinton & Lock :, [not after 1778]" we want it to read "Darly, M. (Mary), Hinton & Lock, [not after 1778]". The latter -- the desired outcome -- would present the data precisely as it appears in search results, so whatever we've done for the search results context should be replicated here.

**Comment by EdwardTown1** [comment]
Hi @yulgit1. 
The following comments probably warrant a full discussion with the group, but I wanted to log my thoughts. I'm aware that we've gone back and forth too many times on the arrangement of the hyperlinks/actions that are listed below the main image for object records and above the string of alternative images. 

However, having seen your latest changes, I think that it is best if the string of thumbnail appears directly below the image and its caption. Having spoken with both Rob and edgartdata about this, we think that if possible the hyperlinks/actions should be a row of buttons (in the style of the JPEG and TIFF options within Download selected image - provided this still complies with accessibility), and that these appear in the following order: Download selected image; Print object information; Request additional photography [please note change to Capitalize/lower-case] and then the IIIF icon.  

May I suggest that the rights information e.g. 'Public Domain' appears on the same line as the image caption (e.g. Cropped image, recto, unframed; **Public Domain**) 

For the sake of consistency, please may I also suggest that the first letter in these image captions is capitalized, and then what follows is in lower case (e.g Recto, unframed)

Many thanks, 
Ed

**Comment by yulgit1** [comment]
addressed @flapka suggestions above with: https://github.com/ycba-cia/blacklight-collections2/commit/6e531a6f2280e193a701ef73e2574af2eac7bbe0

**Comment by flapka** [comment]
Thanks @yulgit1 , this partially fixes the problem. One detail still: the field that captures the short title often ends with a punctuation mark, either a '.' a ':' or a '/'. In the search results view, we do some normalization to remove that mark -- and we want to do the same normalization in the caption above the image so that we don't end up with combinations like ".," ":," and "/," Here's another example of the problem:

http://ycba-collections-dev.herokuapp.com/catalog/orbis:13687137

**Comment by yulgit1** [comment]
@flapka trailing punctuation should now be removed: https://github.com/ycba-cia/blacklight-collections2/commit/541dcf50084a4183a7340e57ae9db6e1872aeb43

**Comment by flapka** [comment]
@yulgit1 Yes, looks fixed. Many thanks!

**Comment by yulgit1** [comment]
@EdwardTown1 - I implemented from your above comments:
https://github.com/ycba-cia/blacklight-collections2/commit/c1ce8cf64a487f870b2bbcbc16aa49000387d9fa
https://github.com/ycba-cia/blacklight-collections2/commit/c69207391bc47558dc155fb669acf7d55923f61e
https://github.com/ycba-cia/blacklight-collections2/commit/609d8212bb8494f336abb773860307031f762cc4

The only departure is that I put the image rights statement centered on it's own line, as it didn't look appropriate on the same line as the main caption.

**Comment by edgartdata** [comment]
@EdwardTown1 @flapka @mxgold Would it be okay to move the object rights type into the metadata block? Maybe under the credit line?

**Comment by mxgold** [comment]
I don’t object; there are pros and cons to each placement.  Happy to cover these in tomorrow’s discussion and defer to group decision.  Thanks!

**Comment by edgartdata** [comment]
@EdwardTown1 Do we want to get rid of the artist's life dates and nationality before the title in the tombstone above the image in the detailed record.

@flapka feels like consistency with the gallery view might be better.

**Comment by edgartdata** [comment]
Let's add ORT in the main metadata section.
Let's give it the heading Copyright status.
For now when the ORT is unknown the text is copyright unknown. Melissa would want to change that uknown ORT text. Would need David's help.

**Comment by edgartdata** [comment]
@yulgit1 Let's make the action buttons a little less blue.

**Comment by edgartdata** [comment]
Are there accessibility issues with a slideshow?

**Comment by mxgold** [comment]
Quick clarification:

The item that we are moving down into the object metadata block is an amalgam of the TMS fields Copyright and Object Rights Type (ORT)

The textual rights information displayed online comes from the TMS Copyright field
Common values include
For works under copyright: © The Artist, © Estate of the Artist, or bespoke copyright notice per rightsholder
For works out of copyright: “Public Domain”
For works of unknown or undetermined status: “Copyright Information”
                The destination/hyperlink for the text displayed is determined by the ORT field

Controlled ORT data in TMS will remain the same, but I will work with David to bulk edit TMS copyright fields that currently contain the phrase “Copyright information” (usually in conjunction where ORT for the object =unknown) to another mutually agreed upon statement that will make sense to our users in the new location.

**Comment by yulgit1** [comment]
addressed:
https://github.com/ycba-cia/blacklight-collections2/commit/b735c3791b0ade5a619d1dab56ea0f127aabb7d9
https://github.com/ycba-cia/blacklight-collections2/commit/472dff06b0ebceae116a6374a73965c0956aba03
https://github.com/ycba-cia/blacklight-collections2/commit/a6a9f894aca65a599f8367e5006f423927f9dea1
https://github.com/ycba-cia/blacklight-collections2/commit/4f0d762dce2a3bb12824acc8d006409b8af2c221

Using "Copyright Information" as default for now on item page.
Using "Unknown" as default for now on print page.

**Comment by edgartdata** [comment]
@mxgold ok to close this issue?
