### ISSUE TITLE
Landing page visual

### ISSUE THREAD

**Issue by edgartdata** [ycba-cia/blacklight-collections2#175]
@EdwardTown1 to send Eric highlight images to add to the slideshow.
They will be in an orientation that takes full advantage of the space on the landing page.

**Comment by flapka** [comment]
Would we like curatorial input on selection of such images? (I can think of at least one or two curators who might like to be asked.)

**Comment by edgartdata** [comment]
I thought curators' input was taken into consideration to come up with the website highlights a few months back? Also the slideshow is only a suggestion to Courtney.

**Comment by flapka** [comment]
No biggie for the selections shown to Courtney. If the slideshow is implemented, will it cycle through all the website highlights, or a selection of the selections? If the latter, I think it reasonable (again) to ask curators for their preferences.

**Comment by EdwardTown1** [comment]
Just selections of the collection. I've just written to Matthew to ask for
this again, and I'll review. If it doesn't contain highlights from RB etc,
we'll rectify this.

**Comment by EdwardTown1** [comment]
Here is the working list - I've added something from RB & PD Photography to get the ball rolling. 
The selection has Matthew's approval although RB may want to change their image! 
![image](https://user-images.githubusercontent.com/47252357/72271801-9027ab80-35f5-11ea-8e32-e3a29d230e77.png)

**Comment by yulgit1** [comment]
implemented in:
https://github.com/ycba-cia/blacklight-collections2/commit/303e8344c5ee00d096bd9319a1c68d3932c953ab
https://github.com/ycba-cia/blacklight-collections2/commit/6ce0bb87d0460f70636686bbf50b99b23b23536e
https://github.com/ycba-cia/blacklight-collections2/commit/7e12fb77c32d7f411516fa062a36d3122f685396

**Comment by flapka** [comment]
Elisabeth is I think pleased with this possibility. If we implement it, or something like it, she'd prefer these two images from RB:
* the opening from the Helmingham herbal and bestiary that depicts a dragon (folio 17v-18r)
* an image of one of our watercolor boxes, presumably the same as is featured on our [collections page](https://dev-britishart-yale-edu-d8.pantheonsite.io/rare-books-and-manuscripts)

I'm copying both images below.

![image](https://user-images.githubusercontent.com/7634899/72832056-0f4e5c80-3c52-11ea-8a0d-414ce057a529.png)

![image](https://user-images.githubusercontent.com/7634899/72832064-14131080-3c52-11ea-8f0a-62d12e71f80a.png)

**Comment by edgartdata** [comment]
Caption for the second image: Reeves & Sons, Box of pigments and implements for painting on china, ca. 1880

**Comment by edgartdata** [comment]
@yulgit1 For the slideshow, can we please not have the edges of the images burnt in? If we can't move the tombstone caption from the top of the image in the slideshow to below the image altogether, can we please move it the just above the slide picker? Can we also make the navigation arrows more transparent?

**Comment by yulgit1** [comment]
addressed: https://github.com/ycba-cia/blacklight-collections2/commit/bfe122b1f9db3e6b21c6133a06861715782507a9

**Comment by edgartdata** [comment]
@yulgit1 Can you please replace the one RBM image in the slideshow with the 2 above? thanks.

Caption for the first image: Helmingham herbal and bestiary, ca. 1500

Caption for the second image: Reeves & Sons, Box of pigments and implements for painting on china, ca. 1880

**Comment by edgartdata** [comment]
Change the color of the navigation arrows in the slideshow to a light gray.

**Comment by yulgit1** [comment]
added the 2 RBM images, and made navigation arrows a light gray per above comments:
https://github.com/ycba-cia/blacklight-collections2/commit/e66a6e4a557200ca263dd0c7b379303f8e92c6cb

**Comment by edgartdata** [comment]
Hi @yulgit1 Can we please have the Paul Mellon bust in #2 place in the slideshow? Also its caption is: Tessa Pullan, Paul Mellon, 1984, cast 1990

@mxgold Do we have copyright clearance for this image?

**Comment by yulgit1** [comment]
fixed caption and move bust image to #2 in the rotation

**Comment by EdwardTown1** [comment]
Hi @yulgit1 <https://github.com/yulgit1> -

Please may I suggest a revised order for the slideshow:

Turner
Pullan
Hepworth
Nicholson
Sandby
Talbot
Helmingham Bestiary
Lewis
Reeves & Sons
Palmer

Many thanks,
Ed

**Comment by yulgit1** [comment]
@EdwardTown1 should be all set:
https://github.com/ycba-cia/blacklight-collections2/commit/b2c32bdab97ed0baf7196d2f59e22bf4419562f3

**Comment by EdwardTown1** [comment]
Thanks Eric!

E T

**Comment by mxgold** [comment]
Maria is working on the clearance – will update you when all set.

Melissa


Melissa Gold Fournier
Head of Imaging and Intellectual Property
Program Manager, YCBA West Campus Initiatives
YALE CENTER FOR BRITISH ART
britishart.yale.edu<https://nam05.safelinks.protection.outlook.com/?url=http%3A%2F%2Fwww.britishart.yale.edu%2F&data=02%7C01%7Cmelissa.fournier%40yale.edu%7Cfc1f08ffe31e42a159dd08d77fe56415%7Cdd8cbebb21394df8b4114e3e87abeb5c%7C0%7C0%7C637118495505325141&sdata=z1WuHPXbKIs5mhG%2FwQ532KBTP4JajBdk8O6HnvLmS9Y%3D&reserved=0>

**Comment by mxgold** [comment]
Is it possible for slideshow images to link to their corresponding object records?

**Comment by yulgit1** [comment]
@mxgold implemented:

https://github.com/ycba-cia/blacklight-collections2/commit/a4341a51261016aeeb5679196e3b07f24fc77375

However one of the records, "Box of Pigments" has no images published (all cdslevel=0)

https://deliver.odai.yale.edu/info/repository/YCBA/object/12590207/type/1
https://yalemuseums.netx.net/app/#search/basic/ba-orb-12590207-

**Comment by mxgold** [comment]
@yulgit1 thanks, & thanks for the heads up.  I just published three images for this object.  @flapka I'll follow up with Laura Callery in case RBMS wishes to adjust the selection or order + image captions.
