### ISSUE TITLE
Download Selected Image opens in a separate page?

### ISSUE THREAD

**Issue by edgartdata** [ycba-cia/blacklight-collections2#177]
@EdwardTown1 @flapka Would it be preferable if the Download Selected Image functionality opened in a separate page from the detailed item record?
As it is currently, users have to use the browser's back arrow to go back to the item's detailed page.

**Comment by flapka** [comment]
Yes, I think opening the download in a new tab or new window would be preferable. Thanks for suggesting.

**Comment by yulgit1** [comment]
Resolved.
