### ISSUE TITLE
Frame keywords

### ISSUE THREAD

**Issue by edgartdata** [ycba-cia/blacklight-collections2#178]
@yulgit1 Another frame issue: None of the keywords describing frames are coming through BlackLight. They are in bac6DEV (65464 is a good example).

Here are the 6 LIDO frame keyword types:
-	Frame alteration
-	Frame status
-	Frame ornament
-	Frame feature
-	Frame quality
-	Frame style

Thanks!

**Comment by yulgit1** [comment]
They are indexed too, but not configured for display.  @edgartdata where do you want them placed in the item page?

topic_frameAlteration_ss
topic_frameStatus_ss
topic_frameOrnament_ss
topic_frameFeature_ss
topic_frameQuality_ss
topic_frameStyle_ss

**Comment by edgartdata** [comment]
Between Collection and Currently on view would be great. thanks.

**Comment by yulgit1** [comment]
Addressed:
https://github.com/ycba-cia/blacklight-collections2/commit/d9fbb5eaf6b36e56df9c0e9d834f5548f97ccb55

**Comment by edgartdata** [comment]
@EdwardTown1 Checking with you if we still want to publish the frames' quality?

**Comment by EdwardTown1** [comment]
No thank you

**Comment by edgartdata** [comment]
@yulgit1 can you please not publish the frame quality attribute to BlackLight? thanks.

**Comment by yulgit1** [comment]
addressed: https://github.com/ycba-cia/blacklight-collections2/commit/de6048a0ede351b050a5318d444c5b613c9621c6
