### ISSUE TITLE
Currently On View

### ISSUE THREAD

**Issue by edgartdata** [ycba-cia/blacklight-collections2#179]
The field heading for the on view/not on view status is 'Currently On View', which then can read 'Currently On View: Not on view' which is not ideal.

What other heading can we come up with? @EdwardTown1 @flapka

**Comment by flapka** [comment]
I posted a tangential comment on a now-closed issue a couple of weeks ago: https://github.com/ycba-cia/blacklight-collections2/issues/52

> While appreciating the utility of the "currently on view" facet, Elisabeth is concerned that the label "currently on view" may inadvertently contribute to an under-appreciation that certain collections are also viewable in the Study Room. She thinks it'd be preferable to have a label along the lines of "On view in galleries" to make a clearer distinction.

**Comment by flapka** [comment]
@EdwardTown1 @edgartdata 

What if we broadly redesigned the facet to indicate these statuses (or something like them):
* On view in galleries
* Viewable by request in Study Room
* some 3rd category, for works that are neither in the galleries or easily request-able in the SR

**Comment by EdwardTown1** [comment]
Sounds good to me. As long as there is a category that covers works that
are off site, in deep storage, and unavailable for view in the short and
medium term.

**Comment by edgartdata** [comment]
@EdwardTown1 @flapka What would that third category be called? What would be your suggestions?

**Comment by flapka** [comment]
@edgartdata @EdwardTown1 What if we change the name of the facet to "Access" (or something similar) -- and name the third category "Not on view"?

**Comment by edgartdata** [comment]
@EdwardTown1 @flapka I like "Access" for both the name of the facet and the name of the field in the detailed records. 
As a related note, TMS does not track locations outside of YCBA. 
I would have to check if we can triage "Viewable by request in Study Room" from "not on view" with TMS data. I think we can but i need to check.
What use cases would "not on view" be?

**Comment by flapka** [comment]
@KraigBinkowski To provide an appropriate Access value for every item in the catalog, we might also include "Available in Reference Library"?

**Comment by KraigBinkowski** [comment]
Yes, each item in the reference collections should have some comparable access value: "Available in the Reference Library" (I would prefer to use the article "the" so that it might approximate a sentence).

**Comment by edgartdata** [comment]
Actually we are already doing this for P&D items since in their detailed records we indicate [Request for use in the YCBA Study Room] so presumably we could reuse this filter for the Access facet as well. @yulgit1 ?

**Comment by edgartdata** [comment]
- On view
- Accessible by request in the Study Room
- Accessible in the Reference Library
- Not on view

New name of the Currently on View field in the detailed record: Access

Possible values for this field: 

- for P&D and RBM: 'Accessible by request in the Study Room' (with [Request] link or 'on view'
(the P&D staff communicates hours of operation separately)
- for P&S: 'on view' or 'not on view'
- for Ref Lib: 'Accessible in the Reference Library' (with [Hours] link)

Leave the facet name as Currently on View and display the 4 values above.

For P&D items not on view, @yulgit1 filter on 'not on view' + P&D department = Accessible by request in the Study Room

For Ref Lib: filter on department = Accessible in the Reference Library

For RBM items not on view, @yulgit1 filter on 'not on view' + RBM department = Accessible by request in the Study Room

**Comment by yulgit1** [comment]
@flapka - defying the logic above, there is no "On View"/"Not On View" for RB/Ref/IA.  I don't even know how this would be recorded this coming from MARC.

As defined above, that is OK as Ref/IA will always be "Accessible in the Reference Library"

Similarly Should _all_ RB just be "Accessible by request in the Study Room" (as there is no onview field for RB)?

**Comment by flapka** [comment]
@yulgit1 yes, that's right. It's a blanket assessment, based on belonging to RB or to Ref.

**Comment by yulgit1** [comment]
indexing addressed:
https://git.yale.edu/ermadmix/camel_collections2/commit/19ccbc66f27b2679a0169d142dda6e556eb3ef46
https://git.yale.edu/ermadmix/camel_collections2/commit/4999c6639d6d9e27fe8ecbfdfa15c0f54a44a138
interface changes
:https://github.com/ycba-cia/blacklight-collections2/commit/ebfdf58d648bb16e43b58d91819068c62dabd82f

awaiting weekend indexing, will deploy interface changes once this is done

**Comment by edgartdata** [comment]
We agree to not accommodate the opening hours of the P&D Study Room and Reference Hours for now for the works of art there.

**Comment by edgartdata** [comment]
@edgartdata  and @yulgit1 check that the Ref Lib and Study Room locations are in the on view stream.

**Comment by edgartdata** [comment]
@flapka okay to close this issue?

**Comment by edgartdata** [comment]
Fine tuning our filtering logic for objects on display in the Study Room and Reference Library, such as Anish Kapoor’s Shadow IV https://collections.britishart.yale.edu/vufind/Record/3818715 (TMS location is 222, Screen 1) and sculpture https://collections.britishart.yale.edu/vufind/Record/1670893 (TMS location is 222, Wall).
 
I will circle back to P&D and @KraigBinkowski to identify these few locations.

So art objects on display in the Study Room and Reference Library (on the wall or on a cabinet) would get an 'on view' status, instead of the 'not on view' status that they get now. 

Is this a post or pre-launch issue? @yulgit1 any concerns?

**Comment by edgartdata** [comment]
@edgartdata to finalize
