### ISSUE TITLE
Rights language

### ISSUE THREAD

**Issue by edgartdata** [ycba-cia/blacklight-collections2#188]
@mxgold During the TMS Users' Group meeting yesterday, there were questions about some of the terms in the Rights facet, specifically 'restricted' and 'rights reserved' did not seem clear to YCBA users. I am only flagging this as feedback from users as we are inviting a larger group of YCBA colleagues to contribute their thoughts about BlackLight. Not sure if there is the possibility somewhere in the page to define further what the 5 rights statuses mean? Is this something we want to investigate further?

**Comment by edgartdata** [comment]
@mxgold, all, Is this a BL launch deal breaker?

**Comment by edgartdata** [comment]
@mxgold to go through the 13 rights reserved items 
![rights reserved](https://user-images.githubusercontent.com/4093644/82069158-edfdfa00-96a0-11ea-8e15-5c028a207886.png)

**Comment by mxgold** [comment]
Done.  Only one item remains in the category at present.  In terms of usability/UI - is a mouseover/hover possible for facets?  If so, I could submit short descriptions for each rights facet / category that might appear.

**Comment by yulgit1** [comment]
@mxgold 
hover works, let me know what you want mapped.

unknown
public domain
under copyright
rights reserved

**Comment by mxgold** [comment]
Suggestions for hover text:

unknown: "Copyright undetermined"
public domain: "Works that have no known copyright"
under copyright: "Works that are in copyright"
rights reserved: "Works that are not in copyright, but works or their images have other restrictions"

**some final additional thoughts on this facet (LMK if I should make these independent issues)
- simplify facet label from “Item Rights” to simply "Rights"
- The rights terms are uncapitalized - can or should they be capitalized, in keeping with almost all of the other facet terms?

**Comment by yulgit1** [comment]
addressed:
https://github.com/ycba-cia/blacklight-collections2/commit/cfc47e740d4b92f165179201fe50ee30000bab5b

**Comment by edgartdata** [comment]
@EdwardTown1 your feedback on the scope notes for the rights?

**Comment by edgartdata** [comment]
unknown: "Copyright undetermined" to change to "Copyright yet to be determined"
Capitalize 'restricted' (and image available and unavailable).

**Comment by yulgit1** [comment]
addressed:
https://github.com/ycba-cia/blacklight-collections2/commit/4984ba50c1aa3f0dd065b415b6a46620d0f34820
