### ISSUE TITLE
Search drop down

### ISSUE THREAD

**Issue by edgartdata** [ycba-cia/blacklight-collections2#191]
@yulgit1 Returning to this issue of the 4 fields in the search drop down not working: title, creator, subject terms, call number.
It seems like a helpful way to allow users to formulate a specific query in fewer clicks than through the full menu of facets available only after a general query is made. Agree?

![BlackLight search drop down](https://user-images.githubusercontent.com/4093644/79880743-69c89780-83be-11ea-9b57-d08555889cf2.png)

**Comment by edgartdata** [comment]
Also, we probably want to replace "Call Number" with another term that works for RBMS and the art collection. Item number?

**Comment by flapka** [comment]
Item number or object number would be okay with me.

**Comment by yulgit1** [comment]
The dropdown for each of these 4 fields appears to be working correctly for me.  Can you give an example of what is not working?

Also, on the item page for LIDO it is "Accession Number" and for MARC "Call Number"

For whatever we decide to call it should be consistent in all 3 places?

**Comment by edgartdata** [comment]
use http://10.5.96.187:3000 for testing.

**Comment by yulgit1** [comment]
Dropdown fixed: 

https://github.com/ycba-cia/blacklight-collections2/commit/2f512aa2e580419dc8a8146ded5800876717b796
