### ISSUE TITLE
YCBA exhibition pages

### ISSUE THREAD

**Issue by edgartdata** [ycba-cia/blacklight-collections2#193]
A topic to discuss with Exhibition & Publications colleagues: How to merge exhibition information coming from TMS and from the YCBA webpages for the benefit of the website?

**Comment by yulgit1** [comment]
One suggestion, have a link to the catalog using the exhibit facet, to see all published objects related to the exhibition, ex: [Line of Beauty](http://ycba-collections-dev.herokuapp.com/?f%5Bexhibition_history_ss%5D%5B%5D=The+Line+of+Beauty+%3A+British+Drawings+and+Watercolors+of+the+Eighteenth+Century+%28Yale+Center+for+British+Art%2C+May+19%2C+2001--August+05%2C+2001%29&q=&search_field=all_fields)

**Comment by edgartdata** [comment]
This is a future enhancement.

**Comment by edgartdata** [comment]
Let's revisit this issue soon as it has been brought up the Deputy Director at a recent curatorial meeting with the desire to happen.

**Comment by edgartdata** [comment]
@EdwardTown1 Might we connect soon with the Drupal team to coordinate with them what BlackLight exhibition related content they could use in the Exhibitions Drupal webpages? They are currently working on preparing a number of Drupal webpages for past YCBA exhibitions in addition to the ones already up on the website.

Today, with the goal of leveraging collections information beyond the BlackLight catalog, we talked about how it might be helpful to add, whenever appropriate, a new section/rubric to the structure of a Drupal exhibition webpage to point to the groups of YCBA objects present in exhibitions as already available in BlackLight. BlackLight currently mints URLs for groups of YCBA objects present exhibitions, such as this one for the _Figures of Empire_ exhibition: https://collections.britishart.yale.edu/?f%5Bexhibition_history_ss%5D%5B%5D=Figures+of+Empire%3A+Slavery+and+Portraiture+in+Eighteenth-Century+Atlantic+Britain+%28Yale+Center+for+British+Art%2C+2014-10-02+-+2014-12-14%29&q=figures+empire&search_field=all_fields

For reference, here is the Drupal exhibition link to _Figures of Empire_:  https://britishart.yale.edu/exhibitions-programs/figures-empire-slavery-and-portraiture-eighteenth-century-atlantic-britain)

@EdwardTown1 @KraigBinkowski @flapka I assume we would also want to capture the Drupal exhibition URL for the benefit of the BlackLight detailed object/item records? 

Questions: 

- What might be the name of that new Drupal rubric? 

- Some YCBA exhibitions were loan heavy. Knowing that BlackLight does not publish any loans, what is the selection criteria around number of YCBA objects present in an exhibition?

- Are there technical considerations around the stability of BlackLight and Drupal URLs?

This proposal would be a good start to address the original issue raised, which is providing a round trip mechanism between BlackLight and Drupal.

**Comment by flapka** [comment]
@edgartdata et al, I'd like to hear more of your thoughts on "we would also want to capture the Drupal exhibition URL for the benefit of the Blacklight detailed object/item records" and "providing a round trip mechanism between Blacklight and Drupal." 

In a detailed object/item record view, the actionable hyperlink underlying the name of each exhibition retrieves all other objects in the exhibition. Are we proposing a link back to Drupal exhibition pages that would be in addition to the existing link?

**Comment by flapka** [comment]
@edgartdata @KraigBinkowski @rchatalbash 

In this morning's meeting, we also talked about the possibility of making wider associations in the "Exhibition History" facet, namely:
* making connections to the related exhibition catalogs (in Ref)
* making connections to archival material related to exhibitions (in IA)

In both of those cases, we could copy the technique that RB uses to connect objects to exhibitions. *But* the semantics are a bit different. Rather than this object *was included in* an exhibition, we have relationships such as this catalog *was produced in conjunction with* an exhibition; or this archival material *documents* an exhibition (etc.). Are we comfortable blurring the varying semantics in a single facet? Would the label "Exhibition History" still apply?

**Comment by yulgit1** [comment]
It's a heavy lift but it'd be remiss not to mention Spotlight.  Spotlight can render blacklight-like pages using subsets of the blacklight index (leveraging exhibition facets for instance), and adding custom content with a variety of widgets (loan materials potentially).

See a page of examples:
https://exhibits.stanford.edu

**Comment by yulgit1** [comment]
Regarding "we would also want to capture the Drupal exhibition URL for the benefit of the Blacklight detailed object/item records"

Could we leverage TMS exhibitionID from the LIDO local eventID, in a semantic handle.  For example something like:

http://hdl.handle.net/10079/ycbaexb/248 

to point to:

An American's Passion for British Art - Paul Mellon's Legacy (Royal Academy of Arts, 2007-10-20 - 2008-01-27)
<lido:eventID lido:type="local">248</lido:eventID>

**Comment by yulgit1** [comment]
@KraigBinkowski @flapka @edgartdata 

Added ilsnumber_ss to index, should run overnight.

What should the tab on the book item page be called? Something like "YCBA Objects" or "Catalog Objects"?

**Comment by KraigBinkowski** [comment]
Can this be easily re-indexed? A good percentage of the ILS numbers have not yet been added to TMS yet - Francis and I just have to give Eric our spreadsheet of matches and he would have to addd the new numbers to TMS. 

When you say "Tab" where would this go and what would it look like?

I think something like "YCBA Objects" would be best but perhaps something that makes it even more clear that these objects are mentioned in some way in the publication? I know we don't want a tab with a thousand words on it...

**Comment by yulgit1** [comment]
Yes it would be reindexed daily.  To add ILSNumbers not in TMS I'd need 2 columns, the TMS ReferenceID, and the ILSNumber.

**Comment by edgartdata** [comment]
But don't we want all ILSNumbers we can find in TMS? Or is the list you are working with Eric just until they are all in TMS?

**Comment by KraigBinkowski** [comment]
We do want all of them - the list for Eric is the retro bib entries from before we were adding ILS numbers to each record.

**Comment by yulgit1** [comment]
Created separate issue for pub/obj linking https://github.com/ycba-cia/blacklight-collections2/issues/411
Continue the YCBA exhibition pages discussion here (exclude past 6 days, include all the above in this thread from 2020).

**Comment by yulgit1** [comment]
from @edgartdata email:

"Kristin Dwyer says that Drupal has persistent links for exhibitions, such as https://britishart.yale.edu/node/739  Would we use that instead of https://britishart.yale.edu/exhibitions-programs/fancy-pieces-genre-mezzotints-robert-robinson-his-contemporaries ?
 
She is also in favor of adding links in the Drupal pages to the group of objects that were in the exhibition. Would we give her links like [https://collections.britishart.yale.edu/?f[exhibition_history_ss][]=Fancy+Pieces+-+Genre+Mezzotints+by+Robert+Robinson+%26+His+Contemporaries+%28Yale+Center+for+British+Art%2C+1994-11-19+-+1995-01-29%29](https://collections.britishart.yale.edu/?f%5bexhibition_history_ss%5d%5b%5d=Fancy+Pieces+-+Genre+Mezzotints+by+Robert+Robinson+%26+His+Contemporaries+%28Yale+Center+for+British+Art%2C+1994-11-19+-+1995-01-29%29) ? Or something else?"

**Comment by yulgit1** [comment]
from @yulgit1 email:

"Using the persistent link would work.  I don’t know if it’s anymore persistent than the named URL. A question for Kristen.  If it is then definitely use it, if not just a matter of preference, the short node URL or the longer but more readable title URL?
 
And yes that facet link would work.  We could also create handles to those links (click the ‘batch’ radio button to see the setup):
 
https://link.its.yale.edu/ypls/index.html"

**Comment by edgartdata** [comment]
Persistent Drupal exhibition links added to the TMS exhibition text entries with the type exhibitionURL. 

Will be in harvester-test Monday as an eventID in LIDO of type “ExhibitionURL”:

{if $Venue->websitete != ''}<lido:eventID lido:type="ExhibitionURL">{$Venue->websitete}</lido:eventID>{/if}

Next step: Emmanuelle needs to craft persistent BL links for Communications team.
