### ISSUE TITLE
Searching on curatorial comments

### ISSUE THREAD

**Issue by edgartdata** [ycba-cia/blacklight-collections2#194]
@yulgit1 Can we make the curatorial comments searchable via the All Fields search bar? 

@flapka For the RBMS collection, is there a comparable field? 

There are 398 art collection objects (60 from P&S) that have curatorial comments, such as http://ycba-collections-dev.herokuapp.com/catalog/tms:34 

Would we also want another way to indicate that there is additional description for some items? (otherwise users would not know to look for these objects).

**Comment by flapka** [comment]
MARC doesn't provide a semantically distinct field for curatorial comments. Where we have them -- or where we have similar content -- it is in the summary field (MARC 520).

**Comment by edgartdata** [comment]
@yulgit1 to make these curatorial comments and summary fields searchable in All Fields.
Have them open by default with option to hide.

**Comment by yulgit1** [comment]
Do we want all three (Curatorial Comment, Exhibition History, Publications) open by default?

**Comment by edgartdata** [comment]
@EdwardTown1 what do you think about having Curatorial Comment, Exhibition History, Publications open by default?

**Comment by edgartdata** [comment]
@yulgit1 Also i wanted to correct my previous comment about include RBMS summary field MARC 520 in this. Per @flapka it is not possible at this point in time to include 520 for this purpose. @flapka is that correct?

**Comment by edgartdata** [comment]
For the purpose of keeping track of todays' conservation: we talked about have Curatorial Comments open by default with the option of collapsing them still available to users.

**Comment by flapka** [comment]
> @yulgit1 Also i wanted to correct my previous comment about include RBMS summary field MARC 520 in this. Per @flapka it is not possible at this point in time to include 520 for this purpose. @flapka is that correct?

Correct, because the MARC 520 field is broader in scope than curatorial comment.

**Comment by flapka** [comment]
Exhibition history is the only of the three fields that currently apply to RB. For it, I think it would be preferable to have it open by default -- with the caveat that the field should be placed at the bottom of the RB detailed display (i.e. move it to just above "Export - XML").

**Comment by EdwardTown1** [comment]
I would be in favour.

E T

**Comment by edgartdata** [comment]
@yulgit1 under Access, can we have these 3 fields in this order:
- Exhibition History (closed by default)
- Publications (closed by default)
- Curatorial Comments (open by default)

This new order for these 3 fields is to make sure that, for records that have a curatorial comment/long text open by default, users would know that there are exhibition history and publications. If the exhibition history and publications sections were kept after the open curatorial comments, I would be concerned that users would not scroll all the way to the end of the record and miss them.

I also see @flapka comments about RBMS only having data for 1 of these 3 fields, namely exhibition history. @yulgit1 I wonder if exhibition history could be open by default only for RBMS and not the art collection? It might not be possible?

Here is how the NGA handles this question, with only provenance open by default: https://www.nga.gov/collection/art-object-page.166478.html

**Comment by flapka** [comment]
Eric will attempt to have certain boxes open by default predicated on the owning department.

**Comment by yulgit1** [comment]
museum:
Exhibition History (closed by default)
Publications (closed by default)
Curatorial Comments (open by default)

library:
Exhibition History (open by default)
Publications (N/A)
Curatorial Comments (N/A)

addressed:
https://github.com/ycba-cia/blacklight-collections2/commit/ce4d88dbfb534c4b4694acd42d8e131b2441337d
