### ISSUE TITLE
Un-captioned images dropping down in image carousel 

### ISSUE THREAD

**Issue by EdwardTown1** [ycba-cia/blacklight-collections2#196]
Observed in B1973.1.57
http://10.5.96.187:3000/catalog/tms:151

**Comment by edgartdata** [comment]
All to search through BlackLight for examples of that (probably mostly in Paintings per Melissa) and to send them to Melissa.

**Comment by yulgit1** [comment]
@EdwardTown1 @edgartdata @mxgold 

I just fixed this, let me know if it's rendering ok

**Comment by mxgold** [comment]
Looks good - thanks!

**Comment by edgartdata** [comment]
Awesome, thanks @yulgit1 .  
@mxgold I think going forward we should see fewer images without caption since your team is working on providing view metadata for all shots?

**Comment by mxgold** [comment]
Yes, when there is more than one view per object presented.  If you run into P&D cases please send them my way.  Our team will review and update ALL paintings and sculpture records over the next three weeks or so; no need to send those.
