### ISSUE TITLE
Double check on the COBOAT's filtering mechanism for locations on view/not on view

### ISSUE THREAD

**Issue by edgartdata** [ycba-cia/blacklight-collections2#198]
This is mostly to not forget this issue, which I just emailed David Parsell about again.

**Comment by edgartdata** [comment]
The location 221-C121-Sh10 was marked public in TMS, which translates into 'on view' in BL. I corrected it in TMS so http://10.5.96.187:3000/catalog/tms:46411 which is in this location should now show up as 'not on view' in BL. @yulgit1 can we verify that with a update of the data?

**Comment by yulgit1** [comment]
@edgartdata 

I checked the LIDO and it appears as ‘not on view’, so it will show up as that after indexing.  But I must be missing something, this record has datestamp of yesterday (2020-05-14), but already indicates ‘not on view’.  If you just corrected it now how did this happen?

https://harvester-bl.britishart.yale.edu/oaicatmuseum/OAIHandler?verb=GetRecord&identifier=oai:tms.ycba.yale.edu:46411&metadataPrefix=lido

**Comment by edgartdata** [comment]
@edgartdata to work on this.

**Comment by edgartdata** [comment]
Confirmation that location 221-C121-Sh10 now comes through as 'not on view' in LIDO and 'Accessible by request in the Study Room'.

![Object not on view](https://user-images.githubusercontent.com/4093644/83901844-664c5e00-a729-11ea-9ec7-4d93848352e8.png)

**Comment by edgartdata** [comment]
@edgartdata @KraigBinkowski and Charlotte Lefland (P&D) now working on further finessing our filtering logic for YCBA items (RBMS or art collection items) on display in the Study Room and Reference Library, such as Anish Kapoor’s Shadow IV https://collections.britishart.yale.edu/vufind/Record/3818715 (TMS location is 222, Screen 1) and sculpture https://collections.britishart.yale.edu/vufind/Record/1670893 (TMS location is 222, Wall).

We will identify what other locations in the  Study Room and Reference Library have/could have objects on display?

The Reference Library and the Study Room currently get the blanket status of ‘not on view’, but now the goal is to give YCBA accessioned items on display in these 2 locations the 'on view' status.

**Comment by KraigBinkowski** [comment]
For the reference library - room 212 is the reading room, room 211 is my office - those are the only places where art lives in Reference.

**Comment by edgartdata** [comment]
@KraigBinkowski so 212 is already marked as /on view': https://ycba-collections-dev.herokuapp.com/catalog/tms:157

Right now there is only 1 painting in your office https://ycba-collections-dev.herokuapp.com/catalog/tms:38438 and it is flagged as 'not on view'. Do you really change it to 'on view'?

**Comment by KraigBinkowski** [comment]
How are you handling the paintings in the Study Room offices? Theoretically, my office is open just as much as the library is open. As long as a patron can get in the library, they would be able to go into my office.

**Comment by edgartdata** [comment]
Ok, so I will change 211 to be 'on view'.

In the Study Room the locations below will now be made public in TMS, i.e. 'on view' in BlackLight:
Rm. 222, Screen 1
Rm. 222, Screen 2
Rm. 222, Screen 3
Rm. 222, Screen 4
Rm. 222, Screen 5
Rm. 222, Screen 6
Rm. 222, Wall
