### ISSUE TITLE
Aeon Request

### ISSUE THREAD

**Issue by EdwardTown1** [ycba-cia/blacklight-collections2#200]
@yulgit1 @edgartdata  @flapka

In the TMS meeting Charlotte Lefland rose the issue that now that patrons have capability to request we should check to see at which point they are told that the request cannot be completed because the building and the Study Room are closed. She currently has no requests for Rare Books and Manuscripts.

**Comment by yulgit1** [comment]
![Screen Shot 2020-05-13 at 1 18 07 PM](https://user-images.githubusercontent.com/2125400/81843944-5bcce900-951c-11ea-9c2c-8fc8972fa670.png)
