### ISSUE TITLE
Exhibition history chrono order problem

### ISSUE THREAD

**Issue by edgartdata** [ycba-cia/blacklight-collections2#202]
A note to look into why the exhibition history is out of chronological order for http://10.5.96.187:3000/catalog/tms:11603 ?
![B1974 2 51 exhibition history out of order](https://user-images.githubusercontent.com/4093644/82068767-70d28500-96a0-11ea-9b56-3e41e53b6eb9.png)

**Comment by yulgit1** [comment]
It is being sorted chronologically descending. You can see from 2020 down to 1980, just 2 exhibits without dates get sorted to the top.  Not sure why no dates in LIDO for these 2 (coboat issue?):

<lido:displayEvent>
Drawing in England from Hilliard to Hogarth (Yale Center for British Art,
</lido:displayEvent>

<lido:displayEvent>
Drawing in England from Hilliard to Hogarth (British Museum,
</lido:displayEvent>

![Screen Shot 2020-05-15 at 11 33 05 AM](https://user-images.githubusercontent.com/2125400/82069577-7f6d6c00-96a1-11ea-8bb6-31008f701991.png)

Here's an exhibition with dates in the LIDO to compare:
![Screen Shot 2020-05-15 at 11 38 27 AM](https://user-images.githubusercontent.com/2125400/82069608-8b592e00-96a1-11ea-86d6-f05510fd53e5.png)

**Comment by edgartdata** [comment]
@yulgit1 I will check with David but I think it may be because the Exhibition Begin and End Dates are not mm-dd-yyyy for the exhibtion 'Drawing in England'.

**Comment by edgartdata** [comment]
The venue dates are missing the days. Ask David to change the COBOAT script to work on MM-YYYY too.

**Comment by edgartdata** [comment]
In fact, COBOAT picks up values from the **Venue Begin and End Date** fields (as shown below in screenshot), i.e. the exhibition run dates at the specific venues, **NOT** from the **Exhibition Begin and End Date** fields (which are the overall run dates when the exhibition goes to several venues).

Additionally, COBOAT is going to display whatever text is in those date fields whether it's just year, yr/mth or yr/mth/day

![Exhibition venue begin and end dates](https://user-images.githubusercontent.com/4093644/83281993-f547fc00-a1a6-11ea-82c5-86d515fe7900.png)

**Comment by edgartdata** [comment]
We are still trying to figure out why the full exhibition concatenation for "Drawing in England" is dropping the Venue Begin and End Dates in LIDO and COBOAT.

**Comment by edgartdata** [comment]
Update: COBOAT is now accommodating for Venue Begin and End Dates that may not be complete, i.e. that may not have a day or a month accompanying the year.

@edgartdata @flapka Follow up question on that: do we want to use a boiler plate statement for exhibitions that did not have venue begin and/or end dates (as in Constable's Clouds TMS exhibitionID 23 and see screen shot below)? And if yes, what should it be?

![YCBA exhibition with no venue begin and end dates](https://user-images.githubusercontent.com/4093644/83570187-9d392e80-a4f3-11ea-810a-a1c29d0733e2.png)

**Comment by flapka** [comment]
My first instinct is to supply only the information we know, with little or no (boilerplate). For the National Galleries of Scotland example, could we do either:

1. Constable's Clouds (National Galleries of Scotland, 2000)

or 

2. Constable's Clouds (National Galleries of Scotland, ended Oct 29, 2000)

**Comment by edgartdata** [comment]
Consensus is to publish these exhibitions with the venue dates as they are in TMS right now, even if they are no dates.

**Comment by edgartdata** [comment]
I am currently double checking with David Parsell that working with one or 2 missing TMS venue dates will not cause problem. If he says it is not a problem, this issue will be good to close.

**Comment by edgartdata** [comment]
Resolved.
