### ISSUE TITLE
Exhibition facet sort

### ISSUE THREAD

**Issue by edgartdata** [ycba-cia/blacklight-collections2#214]
@EdwardTown1 @flapka @yulgit1 
I am wondering if we would be interested in another sort mechanism for the exhibitions facet? Specifically would sorting exhibitions in the facet by dates be a helpful mechanism? Right now, exhibitions are sorted by the number of objects they had, starting with the largest exhibitions. Would SOLR/BL be able to do that if we wanted to?

Please do not answer now!

**Comment by edgartdata** [comment]
@yulgit1 Eric, would that be a possible option? No rush on this.

**Comment by yulgit1** [comment]
There is no mechanism for this, It would involve a deep change that would sacrifice maintainability.
