### ISSUE TITLE
Display issue 2 on mobile: item page text overlay

### ISSUE THREAD

**Issue by robl** [ycba-cia/blacklight-collections2#223]
Malik has identified two display issues on mobile; maybe possible to fix? This one is overlapping text on item page (see screenshot).
![Screenshot_20200624-113612_Chrome2](https://user-images.githubusercontent.com/55926/85785763-9f0f9f80-b6f7-11ea-8e54-021d4d471ccc.jpg)

**Comment by yulgit1** [comment]
Addressed:  https://github.com/ycba-cia/blacklight-collections2/commit/a673004ffddc8e85abaf466a08a761c8b2479729

![Screen Shot 2020-06-26 at 11 42 33 AM](https://user-images.githubusercontent.com/2125400/85875578-6ed10b00-b7a2-11ea-8f87-48e989e81170.png)
