### ISSUE TITLE
Image display on "print" page for works with image size restrictions

### ISSUE THREAD

**Issue by mxgold** [ycba-cia/blacklight-collections2#224]
For most works with object rights status "under copyright" or "unknown", images are published to the online collection via CDS  Level 1, which provides a max 249 x 249 pixel thumbnail image only (unless by other agreement or arrangement with the rights holder and/or collection curator.)

However, when navigating to the "print object" page for works under copyright or unknown, the thumbnail image provided is stretched to fill a larger display area (700 x 800?)  Can we restrict the image size in the print object page template to max size image delivered by CDS?

examples: 
https://collections.britishart.yale.edu/print/tms:63012/1
https://collections.britishart.yale.edu/print/tms:50804/1

**Comment by yulgit1** [comment]
resolved:https://github.com/ycba-cia/blacklight-collections2/commit/d0dffad214225dbd363947f407f4780b6021dc23

**Comment by edgartdata** [comment]
@yulgit1 When I click on _Print_ for this Sickert with unknow ORT https://collections.britishart.yale.edu/catalog/tms:5019, I get this error message: We're sorry, but something went wrong. If you are the application owner check the logs for more information.
