### ISSUE TITLE
Update footer link URL for “Accessibility at Yale”

### ISSUE THREAD

**Issue by robl** [ycba-cia/blacklight-collections2#230]
The destination URL for the “Accessibility at Yale” link in the footer was modeled on the Drupal site’s link, which turned out to be incorrect. The correct URL for that link is as below, please. Thanks, @yulgit1 .

https://usability.yale.edu/web-accessibility/accessibility-yale

**Comment by yulgit1** [comment]
addressed: https://github.com/ycba-cia/blacklight-collections2/commit/8161091d51a0f3c42778de1facc2a345465e443e
