### ISSUE TITLE
Easy revision to mapping of alternate titles for MARC

### ISSUE THREAD

**Issue by flapka** [ycba-cia/blacklight-collections2#232]
For MARC objects, alternate titles currently map from field 246. Here's our XSLT:

`

<xsl:template name="title_alt">
--
  | <xsl:for-each select="marc:datafield[@tag='246']">
  | <xsl:element name="title_alt_ss">
  | <xsl:for-each select="marc:subfield[@code!='0']">
  | <xsl:value-of select="normalize-space(.)"/>
  | <xsl:if test="following-sibling::marc:subfield">
  | <xsl:text> </xsl:text>
  | </xsl:if>
  | </xsl:for-each>
  | </xsl:element>
  | </xsl:for-each>
  | </xsl:template>

`

In addition to the 246 field, alternate title should map from the MARC 130 and 240 fields. Here are two example records that are impacted:
* alt title in 130: https://collections.britishart.yale.edu/catalog/orbis:13205595
* alt title in 240: https://collections.britishart.yale.edu/catalog/orbis:12338481

Sorry I didn't catch this sooner.

**Comment by yulgit1** [comment]
addressed: https://git.yale.edu/ermadmix/ycba_xslts/commit/0677c0cf2ebbfcebd14c19f0bd6611a398ca49bb

Will pick up after next indexing

**Comment by flapka** [comment]
Thanks @yulgit1. Has indexing occurred since you changed the XSLT? I don't see the expected alternate titles in the two examples cited above.

**Comment by flapka** [comment]
This now appears fixed. Thanks @yulgit1 . I think we can close it.
