### ISSUE TITLE
Header graphic missing?

### ISSUE THREAD

**Issue by mikeapp** [ycba-cia/blacklight-collections2#24]
There was a "Yale Center for British Art" banner graphic that appears to be missing in the new version.  It does not seem to be an HTTPS issue.

**Comment by yulgit1** [comment]
Heroku doesn't public static assets.  Apparently there is a workaround:

https://devcenter.heroku.com/articles/rails-4-asset-pipeline

Tried both the config.serve_static_assets and the rails12_factor gem, neither worked.  So just copied the banner image from assets/images to public
