### ISSUE TITLE
Change IIIF root URL to https

### ISSUE THREAD

**Issue by mikeapp** [ycba-cia/blacklight-collections2#25]
Change to HTTPS in Javascript so that HEAD request doesn't fail on HTTPS site:

`"http://manifests.britishart.yale.edu/manifest/" +`...

**Comment by mikeapp** [comment]
Related to #22

**Comment by mikeapp** [comment]
Logo image URL is available via HTTPS: https://static.britishart.yale.edu/images/logo-iiif.png

**Comment by yulgit1** [comment]
done
