### ISSUE TITLE
Need to pad AAT IDs to 9 digits for subjects coming from TMS Thesaurus Manager

### ISSUE THREAD

**Issue by edgartdata** [ycba-cia/blacklight-collections2#266]
Just a note to document that I have shared Yer’s script for padding our AAT IDs in our LIDO coming from the TMS Thesaurus Manager with David Parsell on 9/14/2020.

@yulgit1 Related question: I know that for our RDF output we are already padding our less than 9 digits TMS vended AAT IDs, 
so I wonder if this change in LIDO will create a problem for the RDF?

[PadAATTerms.pdf](https://github.com/ycba-cia/blacklight-collections2/files/5263803/PadAATTerms.pdf)

**Comment by yulgit1** [comment]
It shouldn't as it uses the following code. When TMS source has 9 digits, nothing will be appended.

def normalize_aat(s)
  s = "30000000" + s if s.length == 1
  s = "3000000" + s if s.length == 2
  s = "300000" + s if s.length == 3
  s = "30000" + s if s.length == 4
  s = "3000" + s if s.length == 5
  s = "300" + s if s.length == 6
  s = "30" + s if s.length == 7
  s = "3" + s if s.length == 8
  "http://vocab.getty.edu/page/aat/#{s}"
end

**Comment by edgartdata** [comment]
Successfully done!
