### ISSUE TITLE
YCBA / Study Room / Ref access information during partial closure

### ISSUE THREAD

**Issue by flapka** [ycba-cia/blacklight-collections2#270]
Text below is extracted from a September email exchange.

FL wrote: 

> In the Blacklight context, clearly the pink banner at top will need revision, to indicate that the Center is partially open but the Study Room and Reference Library remain closed until further notice. Here’s the current banner:
>  
>
> >Welcome to YCBA Collections Online
> >As a COVID-19 precaution, the Center is closed until further notice. We are committed to the health, safety, and well-being of our visitors and staff. Our collections can still be explored and enjoyed through this online catalogue.
>
> In addition, detailed object records in Blacklight have statements on access that may be misleading without further information. We suggest the following changes in object records, to increase the transparency of closures.

 
![image](https://user-images.githubusercontent.com/7634899/94144000-9afe3580-fe3e-11ea-87d1-8d3d09cd5189.png)

> For objects requested through the Aeon system (for P&D and RB material), it will be useful to retain the request links, so that staff and researchers alike can continue to queue material of interest, even while we’re closed. When a user clicks on the “Request” link the subsequent screen will include the following banner describing COVID-19 precautions:
>  
> `Yale Library Special Collections reading rooms are open to Yale affiliates by appointment only [link].  You must present a current Yale ID authorized to enter campus buildings to conduct onsite research. The Yale Center for British Art Study Room is closed until further notice. Please email the relevant repository for more information, and monitor the library's COVID-19 page for updates.`

KB replied:

> For the Ref Record in Blacklight, it would be nice to say something like: “ For scans from the reference collection please email ycba.reference@yale.edu”

**Comment by yulgit1** [comment]
@flapka, notes added
PD: https://collections.britishart.yale.edu/catalog/tms:10810
RB: https://collections.britishart.yale.edu/catalog/orbis:11747803
IA: https://collections.britishart.yale.edu/catalog/orbis:14474803
REF: https://collections.britishart.yale.edu/catalog/orbis:7848589

**Comment by flapka** [comment]
Thanks @yulgit1 , I think this is good. Two small tweaks:

1. For Ref, @KraigBinkowski suggests this phrase, if possible: "For scans from the reference collection please email ycba.reference@yale.edu” I think that phrase is intended as a replacement rather than an addition, but @KraigBinkowski can verify
2. For the 3 others, it looks like we need a space inserted after "precaution,"

**Comment by edgartdata** [comment]
Check with @KraigBinkowski before making further changes.

**Comment by edgartdata** [comment]
Today we don't have the new language for the pink COVID banner.

**Comment by KraigBinkowski** [comment]
I think we can have the standard Covid-19 closure note with the "scans" sentence added if possible?

**Comment by yulgit1** [comment]
Resolved:
https://github.com/ycba-cia/blacklight-collections2/commit/d637bf72d1c39b01f02bd3865ef9ce669fb016f8

Ex: https://collections.britishart.yale.edu/catalog/orbis:4898226
