### ISSUE TITLE
BL URIs in LIDO XML

### ISSUE THREAD

**Issue by edgartdata** [ycba-cia/blacklight-collections2#271]
Just a note to document that yesterday in LIDO we replaced the vufind object URIs with BL URIs.
@yulgit1 Do we need to let our agreegators know?

**Comment by yulgit1** [comment]
New URL, but same endpoint from the redirect, so should be seamless.  But I don't see why not letting our aggregators know.  

But who are our aggregators?  Are you keeping track somehow who's using the harvester?

**Comment by edgartdata** [comment]
I know only of external services we have have official partnership with: Art UK, Google Arts & Culture, The Watercolour World, and Smartify.
@yulgit1 Is there a way to monitor the harvester? It might be helpful to keep an eye on it in case the requests impact its performance?

**Comment by yulgit1** [comment]
They are running on ITS servers, I'll ask.

**Comment by edgartdata** [comment]
@yulgit1 @robl Circling back to this in the light of our email thread today prompted by Rob Lowe's question. Can we close this issue?

**Comment by yulgit1** [comment]
I think so.
