### ISSUE TITLE
Height and width

### ISSUE THREAD

**Issue by mikeapp** [ycba-cia/blacklight-collections2#28]
Height and width fields are 'unknown', need to be populated correctly.
Search for Constable paintings with height limits, for example.

**Comment by yulgit1** [comment]
'unknown' for latest date and earliest date as well.  This is faceting issue that is new, these had real values before the last reindex. (the *_i extensions are no longer there)

**Comment by yulgit1** [comment]
This was initially indexed without populating the height and width solr fields.  Should now be fixed.
