### ISSUE TITLE
Creator name search

### ISSUE THREAD

**Issue by edgartdata** [ycba-cia/blacklight-collections2#283]
Ed notes that searching for "john Ruskin" returns the first object records in which he is not the creator. 
Agreement for boosting names of people as production related constituents. @yulgit1 

![image](https://user-images.githubusercontent.com/4093644/99812126-11a07200-2b14-11eb-9a92-25ba2c4359ba.png)

**Comment by edgartdata** [comment]
Just noting that today the masonry view returns the same results, with the first 2 works not by Ruskin.

**Comment by yulgit1** [comment]
The reason for that is that the result set is ordered by collections and the P&S objects are sorted first.

https://collections.britishart.yale.edu/?q=John+ruskin&search_field=all_fields

**Comment by edgartdata** [comment]
@yulgit1 Could we circle back to this scenario, which is that there are no results in P&S for the search 'john ruskin'. Ideally BL would not return P&S records since neither 'john' or 'ruskin' are in the 2 records presented first in the masonry view.

**Comment by yulgit1** [comment]
The impediment is that the sort order is:

_collection_sort_s asc, score desc_

So the collection order (P&S first) will always supersede the search score, even though the score is low (because Ruskin is in the exhibition history of those 2 records, not in a high boost field like creator).

**Comment by edgartdata** [comment]
I think we came to the conclusion that Ruskin is the only case for which this happens. Will reopen if other use cases come up.
