### ISSUE TITLE
Collection facet for library objects held by Ref and RB 

### ISSUE THREAD

**Issue by flapka** [ycba-cia/blacklight-collections2#285]
@yulgit1 @KraigBinkowski 

Molly has pointed out that our Blacklight collection facet doesn't account for the fact that some books are held by both Ref and RB.  According to [this search in Orbis](https://orbis.library.yale.edu/vwebv/search?searchArg1=bacrb&argType1=all&searchCode1=HKEY&combine2=and&searchArg2=&argType2=all&searchCode2=GKEY&combine3=and&searchArg3=&argType3=all&searchCode3=GKEY&year=2020-2021&fromYear=&toYear=&location=Reference+Library+%28BAC%29&place=all&type=all&status=all&medium=all&language=all&content=all&media=all&carrier=all&recCount=50&searchType=2&page.search.search.button=Search), there should be 172 items in this category. 

Looking at several examples ([one ](https://collections.britishart.yale.edu/?f%5Bauthor_ss%5D%5B%5D=Gersht%2C+Ori%2C+1967-&q=clearing&search_field=Title)| [two ](https://collections.britishart.yale.edu/?utf8=%E2%9C%93&search_field=Title&q=Aedes+Hartwellianae%2C+or%2C+Notices+of+the+manor+and+mansion+of+Hartwell+)| [three](https://collections.britishart.yale.edu/?utf8=%E2%9C%93&search_field=Title&q=Animal+painting+in+England+from+Barlow+to+Landseer)), it appears that collection facet records the Ref value in all cases (omitting RB). 

In the detailed object view, all copies are correctly acknowledged -- because we use a different method in that context for retrieving the holdings information. The problem is only in the Collection facet.

@yulgit1 This has something to do with the technique that we use to harvest records, right? What could we do to make the collection value repeatable?

**Comment by yulgit1** [comment]
@flapka

(1) the multiple collections would have to appear in the Marc XML set spec element.  It looks like only one set is there checking the first example:

https://libapp.library.yale.edu/OAI_BAC/src/OAIOrbisTool.jsp?verb=GetRecord&identifier=oai:orbis.library.yale.edu:8009172&metadataPrefix=marc21

(2) unknown to me is how the camel xpath would handle the multiple elements (will it concatenate into one String, in which case the xslt should use a contains() rather than starts-with()?  Would have to experiment at this point).

```
<setHeader headerName="set">
        <xpath resultType="String">//record/header/setSpec/text()</xpath>
</setHeader>
```

**Comment by flapka** [comment]
@yulgit1 Ah, thanks for showing that the problem is clearly in the data feed, where the RB copy is not acknowledged unless we also query another data point (e.g. https://libapp.library.yale.edu/VoySearch/GetAllMfhdItem?bibid=8009172) -- which would take us back to the problem of slow harvesting & indexing, right?

For other reasons, I've identified an interest in replacing the libapp feed with YUL's Metadata Cloud data feed, once the latter is mature. If we think that such a transition is feasible in 2021, I'd be content to table this issue for now (with the hopes that this bug would be solved in the process).

**Comment by yulgit1** [comment]
@flapka Not necessarily, there can be multiple set specs for example:

```
<header>
<identifier>oai:tms.ycba.yale.edu:10019</identifier>
<datestamp>2020-12-22</datestamp>
<setSpec>ycba:pd</setSpec>
<setSpec>ycba:incomplete</setSpec>
</header>
```
Again, there might be issues downstream in how apache camel processes what is returned from an xpath finding multiple elements, but I would favor that approach first rather than making mfhd calls, which would slow things down considerably.

Re: moving to Metadata Cloud, that sounds like a big if!

**Comment by flapka** [comment]
@yulgit1 Thanks, that's helpful. My inclination is to reach out to Yue (at YUL) to ask if YUL could vend multiple setspecs. Do you agree with that as a logical next step?

**Comment by yulgit1** [comment]
@flapka Yes, in a libapp-test (not prod yet).

**Comment by flapka** [comment]
Email from Yue on Jan. 27:

From: Ji, Yue 
Sent: Wednesday, January 27, 2021 4:23 PM
To: Lapka, Francis <francis.lapka@yale.edu>
Cc: James, Eric <eric.james@yale.edu>; Smith, Steelsen <steelsen.smith@yale.edu>
Subject: RE: libapp / OAI setspecs
 
Hi Francis,
 
I made the update based on your request, and it’s on the test server. Here’s your sample url:
https://libapp-test.library.yale.edu/OAI_BAC/src/OAIOrbisTool.jsp?verb=GetRecord&identifier=oai:orbis.library.yale.edu:8009172&metadataPrefix=marc21
 
If there is no problem, please test thoroughly, maybe doing the full load testing to make sure this new update won’t impact other functions.
 
After your thorough testing is done, please contact Steelsen for production roll out, usually needs to be in the queue first. Library IT has the production roll out protocol. I included him here to be in the loop.
 
Thanks,
 
Yue

> From: Ji, Yue 
> Sent: Wednesday, January 27, 2021 4:23 PM
> To: Lapka, Francis <francis.lapka@yale.edu>
> Cc: James, Eric <eric.james@yale.edu>; Smith, Steelsen <steelsen.smith@yale.edu>
> Subject: RE: libapp / OAI setspecs
>  
> Hi Francis,
>  
> I made the update based on your request, and it’s on the test server. Here’s your sample url:
> https://libapp-test.library.yale.edu/OAI_BAC/src/OAIOrbisTool.jsp?verb=GetRecord&identifier=oai:orbis.library.yale.edu:8009172&metadataPrefix=marc21
>  
> If there is no problem, please test thoroughly, maybe doing the full load testing to make sure this new update won’t impact other functions.
>  
> After your thorough testing is done, please contact Steelsen for production roll out, usually needs to be in the queue first. Library IT has the production roll out protocol. I included him here to be in the loop.
>  
> Thanks,
>  
> Yue

For comparison, this is the same record in the current OAI feed:
https://libapp.library.yale.edu/OAI_BAC/src/OAIOrbisTool.jsp?verb=GetRecord&identifier=oai:orbis.library.yale.edu:8009172&metadataPrefix=marc21 

@yulgit1 responded to indicate that he will test (a full load?) when time permits. Progress!

**Comment by flapka** [comment]
@yulgit1 @edgartdata I believe this is now resolved. See the following, where Blacklight acknowledges 177 items held by both RBM and Ref: 
https://collections.britishart.yale.edu/?f%5Bcollection_ss%5D%5B%5D=Rare+Books+and+Manuscripts&f%5Bcollection_ss%5D%5B%5D=Reference+Library
