### ISSUE TITLE
Broken external links

### ISSUE THREAD

**Issue by edgartdata** [ycba-cia/blacklight-collections2#287]
@yulgit1 @robl Is there a way to programmatically scan for which Publication links might have become broken over time? (they might have been taken down by their provider or the link has changed)

**Comment by yulgit1** [comment]
With a list of links, the HTTP status code could be checked for each, but that wouldn't tell you if the page was still up but changed.

As far as getting that list I was looking at the 'remarks' field of the query:

```
select *
FROM [TMS].[dbo].[AltNums]
where AltNum = 'Available Online'
```
There are only 39 rows, many of which don't contain links.  

Another query, as AltNum isn't always 'Available Online' for links in the Remarks field, returns 83 rows:

```
select *
FROM [TMS].[dbo].[AltNums]
where Remarks like '%http%'
```

@edgartdata are the publication links held in any other places in the database?  If not perhaps this is a manageable number to  check manually.

**Comment by edgartdata** [comment]
@yulgit1 I believe the Remarks field is the only field where we would have http resources that we want to make actionable in BL. @KraigBinkowski please correct me if I am wrong. 

83 links to check is doable but @yulgit1 are you saying that it would have to be a manual job at a schedule determined by ourselves?

**Comment by KraigBinkowski** [comment]
@edgartdata that is correct - the bibliography url links are only from the Remarks field within Alternate Numbers. There may be others in the bib records, but these are the only ones we want actionable.

**Comment by yulgit1** [comment]
@edgartdata - by manual I mean actually putting each of the 83 URL in the browser and see that you get what you intended to get.  Again there's no way to programmatically know if page content has changed.

**Comment by edgartdata** [comment]
@KraigBinkowski @yulgit1 I am closing this issue noting that links will have to be manually verified to still be valid every so often (one or twice a year or?).
