### ISSUE TITLE
Creator facet search results inconsistent with Vufind

### ISSUE THREAD

**Issue by mikeapp** [ycba-cia/blacklight-collections2#29]
Searching on "John Constable" as creator in Vufind by facet returns works by others. Why does Lionel Constable appear in these results?

http://collections.britishart.yale.edu/vufind/Search/Results?join=AND&bool0[]=AND&lookfor0[]=%22Paintings+and+Sculpture%22&type0[]=collection&filter[]=auth_author_display_facet%3A%22John+Constable%22&view=grid

**Comment by mikeapp** [comment]
And Blacklight is missing "Attributed to John Constable", e.g.,  http://collections.britishart.yale.edu/vufind/Record/1668066

**Comment by yulgit1** [comment]
second comment should be fixed via using author_ss as per issue 30.

**Comment by yulgit1** [comment]
re: first comment: the vufind uses auth_author_facet, which is a multiple field which happens to have entries for both John and Lionel 

http://collections.britishart.yale.edu/vufind/Record/1670659

**Comment by yulgit1** [comment]
Closing this, and tracking outstanding question in #30.
