### ISSUE TITLE
Issue with Google Chrome loading images 

### ISSUE THREAD

**Issue by EdwardTown1** [ycba-cia/blacklight-collections2#290]
@yulgit1 @edgartdata @mxgold Hi all - both primary and alternative images in ribbon/carousel in Blacklight are not loading in Google Chrome. No issue with Safari and Firefox. @yulgit1 Any ideas about the root of the issue?

**Comment by edgartdata** [comment]
I was going to add that for me today in both Firefox and Chrome only the primary and the UV shots are loading for https://collections.britishart.yale.edu/catalog/tms:80137  with the recto unframed and the verso unframed are not loading at all ... but as soon as I stopped Zoom all the images loaded in both browsers. Other images in other records, still with Zoom off, there is a noticeable delay.

**Comment by yulgit1** [comment]
Everything seems to be loading ok for me including tms:80137 and others (5005,50055).  Sounds like bandwidth issue, but don't know for certain.
