### ISSUE TITLE
Provenance 

### ISSUE THREAD

**Issue by edgartdata** [ycba-cia/blacklight-collections2#292]
We are thinking about publishing the human readable provenance entries to P&S and P&S BL records. 
Would right after Curatorial Comment (soon to become Curatorial Description) works?
Have the section open of closed by default?
Would RBM want to publish provenance to a few records as well?

To @yulgit1 Can we not push any LIDO data to a new Provenance section yet please, until Ed has reviewed the research.

**Comment by flapka** [comment]
For provenance information in RBM descriptions, the emphasis is very much on recording the material evidence (e.g., bookplates, autographs, annotations, etc.). The description is recorded as part of a copy-specific note, usually alongside information about the (bespoke) binding. For example:

> BAC: British Art Center copy bound in contemporary tan half calf and marbled boards. Armorial bookplate: Charles Henry Parry.

[Full record](https://collections.britishart.yale.edu/catalog/orbis:2496056))

**Comment by edgartdata** [comment]
@flapka Would RBM consider recording the ownership history of its items in a format closer to what the Carnegie Museum of Art developed in 2016-17 (based on 2000 guidelines by Nancy Yeide/AAM)? These guidelines are intended to transform traditional provenance text into structured data with the goal to:
-	make the text information more explicit and precise
-	identify gaps in knowledge (for example unknown whereabouts during some time) 
-	enable machine-searchability (i.e. to be able to return results for complex research questions, such as: What paintings did Paul Mellon buy from Agnew before 1970?)

Traditionally, provenance consists of two semantically different sections. One is the paragraph of semi-structured text that contains a list of transfers ordered from first owner until the present day. The other is a collection of footnotes which provide unstructured content, commentary, and documentation of sources. In addition to these 2 traditional sections, structured provenance data requires two new ones: authorities and citations.

CMOA example: 

**Semi-structured text:**
Possibly purchased at auction by John Doe? [1910?-1995?], Boise, ID, for daughter of previous, Sally Moe, Baroness of Leeds [1940-], Pittsburgh, PA?, at “Sale of Pleasant Goods”, Christie’s, in London, England, sometime after November 5, 1975 (stock no. 10, for $1000) [1][a][b].

**Notes:**
[1]: Purchased on the occasion of her birthday.

**Authorities:**
John Doe: http://ulan.getty.com/123455
Boise, ID: http://geonames.com/123456
Sally Moe, Baroness of Leeds: http://viaf.org/123456
Pittsburgh, PA: http://tgn.getty.org/123456
London, England: http://geonames.com/555121
Christie’s: http://viaf.org/1234569 Sale of Pleasant Goods: no record found.

**Citations:**
[a]: See Arnau, F. (1961). The art of the faker: Three thousand years of deception. Boston: Little, Brown. http://www.worldcat.org/oclc/873114
[b]: See curatorial file, Carnegie Museum of Art.

**Comment by flapka** [comment]
@edgartdata Yes, to the extent possible, RBM is keen to align our provenance descriptions with those generated for art collections. 

The primary challenge is this: for most RBM material, provenance information is not at hand beyond a) Mellon's purchase of the object; or b) our purchase of the object. Records of earlier sale and transfer are most often not present in the YCBA's files. Perhaps the situation is similar to that for prints in P&D? Short of YCBA staffing investment in provenance research for RBM, additional provenance details will be difficult to fill in.

Where we have sufficient data in RBM to create the semi-structured text, we can make that our goal. However: that text should be in additional to description of the material evidence of provenance (annotations, etc.), which is of significant interest to RBM researchers. 

Yes, also, on recording names of individuals related by provenance. Such names are in many RBM records already, as in the [example above](https://collections.britishart.yale.edu/catalog/orbis:2496056). There's room for improvement (changes of policy) in the details: [1] MARC isn't well-designed for provenance information, so it's shoe-horned into a non-standard field; [2] in conformance with legacy practice, the name is sub-divided by a term (e.g. "Bookplate") that doesn't align with our long-term goals.

**Comment by flapka** [comment]
@edgartdata @EdwardTown1 Is there an intention, for art collections, to separately index agents related by provenance? If so, do we envision a separate facet for provenance agents?

**Comment by edgartdata** [comment]
Very quickly (and we should probably have a longer convo on this): yes to researching URIs in external authorities for provenance related agents. I still have to figure out what would be the best way to record them in TMS but yes, the intention is to vend them through LIDO & RDF.

**Comment by flapka** [comment]
@edgartdata Sorry, I edited my question above just as you submitted your response! In the long term, I think a facet for provenance agents would be desirable. Happy to coordinate RBM activities in this domain wherever we can.

**Comment by flapka** [comment]
@edgartdata In my fist take, I didn't fully grasp one of your questions above, concerning the textual descriptions of provenance. Formatting is nearly non-existent in the MARC environment, which means that basic elements of the text block -- especially line breaks -- would be impossible in the Voyager environment. We'd need to look for another method. 

This more advanced formatting is possible in ArchivesSpace, for provenance related to archival collections.

**Comment by edgartdata** [comment]
MARC does not accommodate for text formatting, i.e. creating different text sections for provenance entry, citations, notes and authorities so is there value in asking RBMS to follow this model?

EDG to share YCBA's documentation with Francis.

**Comment by edgartdata** [comment]
EDG shared YUAG and YCBA provenance guides with Francis today (not the full length one for YCBA yet).

**Comment by edgartdata** [comment]
@yulgit1 Can we please have an additional tab for Provenance? Let's not publish publish yet any of the 5 LIDO-Provenance entries that we have as I am checking with Ed if these 5 are ready for public consumption.

**Comment by yulgit1** [comment]
@provenance is ready and waiting in blacklight.  Just need examples to make sure LIDO and solr indexing are set up.

**Comment by edgartdata** [comment]
@yulgit1 Just to let you know I am about to add the provenance for 766. Would it be possible to see it in its tab in production tomorrow?

**Comment by yulgit1** [comment]
@edgartdata 
I just added indexing of provenance https://git.yale.edu/ermadmix/ycba_xslts/commit/7d3759c1f155a45ee8153de19be44d82d088d2cb

If LIDO is set up to publish it, which I think it is, we should see it in production tomorrow

**Comment by edgartdata** [comment]
@yulgit1 Can we use \n\n as markers for line returns in the Provenance tab text please? Right now they print in BL.

![Provenance text reserved characters](https://user-images.githubusercontent.com/4093644/133281794-c97a9d79-cb42-4f1a-890b-2f2a1c077578.png)

**Comment by yulgit1** [comment]
@edgartdata resolved: https://github.com/ycba-cia/blacklight-collections2/commit/63decdff58e5dd4f7ab7716cc8489376c1a348cf

https://collections.britishart.yale.edu/catalog/tms:766

**Comment by edgartdata** [comment]
Would we want to include provenance tab text into the overall catalog search?

**Comment by edgartdata** [comment]
@yulgit1 given the 6/9 group discussion, can we please add "Available provenance" under the All Fields search? Hopefully that fits in the drop down.
We will want to revisit this issue once there is more provenance content in the online catalog.

**Comment by yulgit1** [comment]
Added 'Available Provenance' to Search type.
https://github.com/ycba-cia/blacklight-collections2/commit/5377e930883b45a9626658bcadc3d129c8c4daa2

**Comment by edgartdata** [comment]
@yulgit1 We can include provenance in our next LUX dataset.

**Comment by yulgit1** [comment]
OK, it is going now:

https://collections.britishart.yale.edu/catalog/tms:38536
https://ycba-lux.s3.amazonaws.com/v3/object/d9/d90c59bd-1b87-4b2b-b8ca-25f4662d7e8e.json

But is currently not HTML formatted.  I just added this and should go in next delivery.

**Comment by edgartdata** [comment]
Great, so I will close this issue until another provenance related one comes up, i.e. until we have structured data to work with.
