### ISSUE TITLE
New item page tab design

### ISSUE THREAD

**Issue by edgartdata** [ycba-cia/blacklight-collections2#293]
From @yulgit1 In anticipation of the new text categories, I’ve have a redesign using tabbed panes (LIDO items only for now).  You can take a look on the dev server (on VPN).  Here are 2 examples:
 
http://10.5.96.187:3000/catalog/tms:34 (extensive description)
http://10.5.96.187:3000/catalog/tms:10101 (metadata tab only)
 
The goal would be to implement new tabs for the new text categories:
 
Curatorial Description
Published Catalog Entry
Gallery Label
Artist's statement
Excerpt from Publication
 
Please let me know what you think. I can make the same changes for MARC and push these changes to production if there is consensus.
 
https://github.com/ycba-cia/blacklight-collections2/issues/275

Eric James

**Comment by edgartdata** [comment]
from @KraigBinkowski 
I think the tabs look vastly better than the double click fields and as far as navigation goes, it is much easier to see and use them up in the tab area. I would like to see a record with 7 or 8 tabs to make certain it doesn’t look cluttered?  I am a little concerned that with tabs such as “Published catalog entry” and “Except from publication”, that the tab title “Publications” losses its clarity in that context. Would the tab be more clearly called “Bibliography” or “Citations”?

**Comment by edgartdata** [comment]
from @edgartdata 
Dear Eric, @yulgit1 
 
I really like this elegant solution. Thank you very much for sharing. I think this is far better than having an endlessly long column of text. 
 
I have some feedback, all cosmetic issues, which I’m sure I’m sure is premature so I’ll keep quiet until the appropriate time. 
 
That said, today Emmanuelle and I were tapped by MD to introduce the new Text Categories to the Director at this Wednesday’s Curatorial Meeting. Would you be willing for us to show these to the group, on the proviso that we credit it as your work and as work in progress? 
 
Very best, 
Ed

**Comment by edgartdata** [comment]
from @yulgit1 Absolutely please share.

**Comment by edgartdata** [comment]
from @flapka I too like the draft design. Thanks Eric!

I share Kraig’s concern about the possible confusion caused with the tab heading “Publications”; I like “Bibliography” as a replacement. Is the word “Metadata” (for the initial tab) too jargon-y? Perhaps we could use “Object details” instead?

Francis

**Comment by edgartdata** [comment]
from @edgartdata 
Hi Eric, all,

I also really like this tab design (thanks Eric for working on this new option!) but I would like to suggest that we keep the metadata/tombstone information as a block that is always on the screen above the tabs, and that stays on the screen when the users click on a different tab. I think it is necessary from a clarity standpoint so that the users know what specific object the gallery labels or bibliography pertains to.

In addition to the usability point, it will save us some real estate to fit in more tabs, which will be needed as I can already think of 2 other new categories/tabs that will need to be folded in soonish:

•	Group description/Related items
•	Provenance

Emmanuelle

**Comment by edgartdata** [comment]
Further to the idea of keeping the tombstone info above the tabs at all times, would we want to consider taking all subjects (subject terms, associated people, associated places, subject headings) out of the tombstone block and putting them into their own separate tab?

**Comment by edgartdata** [comment]
And how having a 'machine-readable data' tab for the XML, RDF, and IIIF manifest?

**Comment by flapka** [comment]
I'm keen to hear more thoughts on the benefit of moving subject terms, associated people, associated places, and subject headings to a separate tab. Collectively, they take up a modest amount of space, and putting them on a separate tab forces the user to execute another click to find them. Also: for a number of objects, these terms will be those that matched a researcher's query; when that's the case, I think it's more useful to have the terms on the primary tab (again, given that they don't take up much space).

**Comment by yulgit1** [comment]
Please see an item such as:

http://10.5.96.187:3000/catalog/tms:34

Per suggestions I changed Publications to Bibliography, moved the tabs to below the tombstone data, and added what we're thinking now as the full array of tabs.  When complete, the tabs without content will be suppressed, but for now am showing all of them to get a sense of the layout with full content.

**Comment by edgartdata** [comment]
Are there other opinions on replacing “Publications” with "Bibliography”? I wonder if bibliography might be interpreted as an effort to be complete? As far as I understand (and @KraigBinkowski corrects me if I am wrong) but it is difficult to know 100% for sure all the publications related to an item/object. Would "selected bibliography" work? Other suggestions?

As time is of the essence and we have been thinking about this issue for several weeks, I would like for us to decide on the names of these categories tomorrow so that they can be encoded next week in the data pipeline from TMS to BL.

**Comment by KraigBinkowski** [comment]
I think we are safe calling it "Bibliography" and not claiming absolute comprehensiveness - no bibliography is absolute. Using "select", on the other hand, indicates that we have selected only certain titles to include - and have some criteria by which we are selecting them. We do not do this but include all citations that can be culled from art historical sources, leaving the viewer to determine their usefulness to their needs.

**Comment by edgartdata** [comment]
Here is the tab design that Eric crafted yesterday and that we presented at the curatorial meeting yesterday: http://10.5.96.187:3000/catalog/tms:34 

It was very well received but I thought looking at the visual might help us finalize our decision.

I understand we can't have an indefinite number of tabs and longs names for our tabs but I would like to suggest a change for the "Related" tab, which is meant to contains description of series/group and list the items/objects in these groups. Can we think of a clearer name for this category/tab?

Other questions:
What order should these tabs be in?
If an object does not have an artist's statement, will the tab still be present in its record? If yes, can we at least hard code the logic that if it is a record coming from TMS, it should not have artists' statements and excerpts? and vice versa for the RBM records? At least for now as we heard yesterday some interest from P&D for artists' statements.

@EdwardTown1 @flapka Anything I might have missed from the curatorial meeting?

![image](https://user-images.githubusercontent.com/4093644/109170212-9374ec80-774e-11eb-95c0-fd9b2e460066.png)

**Comment by edgartdata** [comment]
@yulgit1 Can we have the name of a tab occupy 2 lines? I am particularly thinking about the one you have as "Catalog Entry" which should be "Published Catalog Entry" to convey its difference with the other tabs.

**Comment by edgartdata** [comment]
Order of tabs:

- Curatorial Description [open by default]
- Gallery Label
- Published Catalogue Entry
- Excerpt from this Work  
- Artist’s Statement 
- Provenance 
- Exhibition History 
- Bibliography
- Associated YCBA Objects

**Comment by edgartdata** [comment]
@flapka Are you okay with renaming 'Excerpts from Publications' with 'Excerpt from this Work'?

**Comment by flapka** [comment]
@edgartdata Yes, that's as good as any.

**Comment by edgartdata** [comment]
The 'Associated YCBA Objects' tab would contain a description of the group of objects and a list of associated works with their accession numbers hyperlinked to their individual detailed BL records.

The description will most probably come from the TMS Group Information field. @edgartdata to provide LIDO configuration next. 

The objects in this group tab would be gathered from sharing the same Collective Title. @edgartdata to check if sketchbooks have another relationship in TMS that could be leveraged for this.

**Comment by yulgit1** [comment]
@edgartdata @flapka @KraigBinkowski. When you’re ready, could you provide a record or records (TMS object/MARC XML) that cover all the tab options, and multiples entries per tab?  That should be sufficient to build and test an implementation in coboat and blacklight.

**Comment by edgartdata** [comment]
@yulgit1 5005 has 2 published catalog entries, 2 gallery labels and 1 curatorial description.

**Comment by edgartdata** [comment]
Wondering how others feel if we were to move _Link_ and _Export_ to below the tabs?

**Comment by yulgit1** [comment]
I don't like that, given the dynamic sizing of the tab block, I worry that the Link and Export would get pushed around and perhaps get unnoticed.

**Comment by flapka** [comment]
I see link and export as functions that might align (somewhat) with our function cluster at top, i.e. Download Selected Image ... [to] iiif. Could they go up there, perhaps with a smaller footprint?

**Comment by yulgit1** [comment]
Keeping an example of what it looks like with all tabs, before implementing so only tabs with data get shown (Must be in GitHub issue, not email to see image)
![Screen Shot 2021-03-25 at 4 33 12 PM](https://user-images.githubusercontent.com/2125400/112540090-27ef6080-8d88-11eb-8482-f7c112fd684a.png)

**Comment by edgartdata** [comment]
Feedback from 3/26 meeting:
- for the tab with prose text, make the space between the columns a little bit wider
- @edgartdata to add text to the Curatorial Description, Gallery Label and Published Catalog Entry tabs, one object record at a time
- the Curatorial Comment tab will need to stay for object records whose Curatorial Comment content still needs to be triaged to the Curatorial Description, Gallery Label and Published Catalog Entry tabs
- The Associated YCBA Objects tab will go away and its content migrate to the metadata block

**Comment by yulgit1** [comment]
The new tab design has been deployed to test server:

https://collections-test.britishart.yale.edu

Tabs are shown if any of the following solr fields have content:

curatorial_comment_ss
curatorial_description_ss
gallery_label_ss
pub_cat_entry_ss
work_excerpt_ss
artists_statement_ss
provenance_ss
exhibition_history_ss
citation_ss

@edgartdata @flapka @KraigBinkowski Please let me know if OK merge.  If the fields don't exist yet they just won't show up.

Next steps:
(1):
Actually Add content to TMS and MARC records.  (See the 2nd pub_cat_entry of Prue for how /n/n gets formatted on the actual page.)
(2) 
Set up coboat for the new TMS fields, should be able to leverage displayEvent element.
(3)
set up solr xslts for new TMS
(4)
set up solr xslts for MARC fields.  Please let me know the MARC->SOLR mappings if any.

**Comment by flapka** [comment]
@yulgit1 In MARC, it's a challenge to code descriptive texts in a way that plays well in both Orbis and Blacklight (not to mention Lux) -- especially if we want to parse out the date and the name of the author. I lean towards proposing something like what follows. I'm keen to hear if this sounds reasonable to you.

1. Descriptive texts will all map from MARC field 520, but not all 520 fields will be descriptive texts. The distinction will be made by use of the first indicator (e.g. if value='8' then descriptive text; else treat as note)
2. In MARC, we cannot use a hack such as /n to indicate a new paragraph, because it will display poorly in Orbis/Quicksearch/LUX. For the moment, we don't have a solution for indicating new paragraphs.
3. AIl human-readable text will go in 520 subfield $a. All machine-readable content will go in 520 subfield $c (because subfield $c does not display in Orbis). We'd want to adjust the Blacklight mapping so that 520 subfield $c does not display.
4. 520 subfield $c would include two pieces of machine-readable data: type of descriptive text (to sort the text into the right tab) and date (also for sorting, within a tab). 

Here's an example, where AS=Artist's Statement:

`520 8_ $a "Rising above the North Lewis peat land, Stacashal is surrounded by small lochans ... [and so on]."--Alex Boyd, January 2013 $c AS_2013-01` 

Would that work? 

@edgartdata Also, what's the preferred format for display dates? I think spelled out months are more user friendly.

**Comment by flapka** [comment]
@yulgit1 For type codes, how about:
* AS = Artist's Statement
* CD = Curatorial Description
* EW = Excerpt from the Work
* GL = Gallery Label
* PC = Published Catalog Entry

As for the syntax, is any one of the following forms preferable for your processing?
AS_2013-01
AS_201301
AS201301

**Comment by yulgit1** [comment]
@edgartdata - they're sorted:

https://collections-test.britishart.yale.edu/catalog/tms:5005
https://github.com/ycba-cia/coboat-github/blob/main/bac-prd-db1/config/LIDOTMSretrieve.cbcs#L282

**Comment by yulgit1** [comment]
@flapka No strong opinion, I guess AS201301.

**Comment by edgartdata** [comment]
@yulgit1 Am I looking in the wrong place? What I see is 2 published catalog entries with the one from 1998 first and then the one from 2007 below. We want the opposite, with the 2007 at the top followed by the 1998 under so that people who open this tab read the most recently written text.

**Comment by yulgit1** [comment]
Right, sorry, dyslexic moment.  Same for exhibit history? (order descending)?

**Comment by edgartdata** [comment]
yes, same descending chrono order for all tabs. thanks!

**Comment by flapka** [comment]
@yulgit1 I will adopt the AS201301-style syntax (my first examples will have year only). 

I've made these changes in two RBM examples, to test the new XSLT & implementation (once the data refreshes tomorrow):
* For artist's statements: https://collections.britishart.yale.edu/catalog/orbis:15657871
* For excerpt from the work: https://collections.britishart.yale.edu/catalog/orbis:12961206

**Comment by edgartdata** [comment]
Just documenting here a question that came up at our last meeting: how would these additional tabs print? I think we said the text would print in line, after the metadata block, when there is text, with the users not being able to select what tab they would want to print.

**Comment by yulgit1** [comment]
@flapka marc xslt change:
https://git.yale.edu/ermadmix/ycba_xslts/commit/e909a08459ffe7784aafb6541b8e132481d532de
indexing overnight

**Comment by edgartdata** [comment]
Some TMS object records with content in the new tabs in DEV:
https://collections-test.britishart.yale.edu/catalog/tms:10833
https://collections-test.britishart.yale.edu/catalog/tms:5005

**Comment by flapka** [comment]
Thanks @yulgit1. After peeking at the XSLT, a question: Will 520 fields with first indicator 8 be processed by both the "desc_fields" and the "description" templates? When the 520 maps to "desc_fields" (because of first indicator 8), we'd want it left out of "description" to avoid repetition. There's a good chance I've misread the XSLT, but thought I'd check.

**Comment by yulgit1** [comment]
@flapka no had to exclude 520, but include 520 with ind1 not equal to 8 for description_ss:
https://git.yale.edu/ermadmix/ycba_xslts/commit/502c9c8017f333e9ebca10ef7fde4f01320074c9

**Comment by yulgit1** [comment]
production xslt parser didn't accept the position of the xsl:sort element, had to place xsl:sort above xslt:variable element:
https://git.yale.edu/ermadmix/ycba_xslts/commit/a33deb91b7c684f707b89763b22d660719de507c
reindexing overnight

**Comment by edgartdata** [comment]
Just a quick note to say that https://collections-test.britishart.yale.edu/catalog/tms:5005 looks pretty good this morning! Texts are sorted chronologically with the most recent ones first, and the line breaks are coming through nicely.
@EdwardTown1 I wonder if we could not ask the RWG for help with getting the texts ready in TMS?

**Comment by flapka** [comment]
Happy to note that the two RBM examples look exactly as expected too:
* Artist's statement: https://collections-test.britishart.yale.edu/catalog/orbis:15657871
* Excerpt: https://collections-test.britishart.yale.edu/catalog/orbis:12961206

As to your second question @edgartdata -- Courtney has asked for the RWG to wind down its work (within the coming weeks). So while I agree that it makes sense to see if staff could be recruited for the project, it's unclear to me whether it should be coordinated by RWG. Perhaps not.

**Comment by KraigBinkowski** [comment]
Just to concur with Francis - this would most likely not be able to be coordinated by the RWG. However, HR may have insights into who from staff might be able to help.

**Comment by edgartdata** [comment]
Just a note to document that the new tab design was rolled out to production today April 13, 2021. Congrats everybody!
