### ISSUE TITLE
Copyright status leading to "Page Not Found"

### ISSUE THREAD

**Issue by mxgold** [ycba-cia/blacklight-collections2#298]
The copyright hyperlink in the cataloging text block sometimes leads to a "Page not Found" 
example: http://10.5.96.187:3000/catalog/tms:1322, which should resolve to https://britishart.yale.edu/using-images-works-under-copyright

After further testing, I believe this occurs only when the status of the work is under copyright but the copyright notice is customized rather than generic.  For instance, links from (c) The Artist and (c) Estate of the Artist resolve correctly, but ones like (c) Anthony Fry do not.

**Comment by yulgit1** [comment]
@mxgold this is coming from a handle found in LIDO:

```
<lido:conceptID lido:source="YCBA" lido:type="local" lido:label="object copyright">55</lido:conceptID>
<lido:term>under copyright</lido:term>
<lido:term lido:label="url">http://hdl.handle.net/10079/x0k6dsf</lido:term>
</lido:rightsType>
```

**Comment by yulgit1** [comment]
@mxgold there is some old logic in lido:
https://github.com/ycba-cia/coboat-github/blob/main/bac-prd-db1/config/LIDOTMSretrieve.cbcs#L1436

```
case  --new 5-15-12
			when ObjRights.ObjRightsTypeID = 9 then 'http://hdl.handle.net/10079/w6m90dq'
			when ObjRights.ObjRightsTypeID = 10 then 'http://hdl.handle.net/10079/rfj6qd5'
			when ObjRights.ObjRightsTypeID = 20 then 'http://hdl.handle.net/10079/7h44j7v'
			when ObjRights.ObjRightsTypeID = 22 then 'http://hdl.handle.net/10079/nk98sp5'
			when ObjRights.ObjRightsTypeID = 23 then 'http://hdl.handle.net/10079/x0k6dsf'
			when ObjRights.ObjRightsTypeID = 24 then 'http://hdl.handle.net/10079/s7h44rz'
			when ObjRights.ObjRightsTypeID = 25 then 'http://hdl.handle.net/10079/1rn8pss'
			when ObjRights.ObjRightsTypeID = 26 then 'http://hdl.handle.net/10079/mpg4fcm'
			when ObjRights.ObjRightsTypeID = 27 then 'http://hdl.handle.net/10079/nk98sp5'
			else 'http://hdl.handle.net/10079/c59zwbm'
```
Please let me know the new logic and I will revise the coboat.

**Comment by mxgold** [comment]
Looks like a couple of broken handles.  @yulgit1 could you please let me know the corresponding Object Rights Types for ObjRightsTypeID's 23 and 26? Then I will attempt to  update / repoint the old handles, or provide new ones.

**Comment by yulgit1** [comment]
```
ObjRightsTypeID	ObjRightsType
0	(not entered)
9	public domain
10	under copyright (fair use)
11	unknown
20	rights reserved
22	under copyright (all restricted)
23	under copyright (no restrictions)
24	under copyright (orphaned work)
25	under copyright (screen cleared)
26	under copyright (thumbnail cleared)
27	contract restricted (all)
```

**Comment by edgartdata** [comment]
@mxgold @yulgit1 circling back to this because today 4/21 the copyright hyperlink in the cataloging text block for http://10.5.96.187:3000/catalog/tms:1322 is still going to a "Page not Found" when it should go to https://britishart.yale.edu/using-images-works-under-copyright

**Comment by mxgold** [comment]
@yulgit1 I've checked all links, please see below for changes.  thanks!

when ObjRights.ObjRightsTypeID = 9 then 'http://hdl.handle.net/10079/w6m90dq'
			when ObjRights.ObjRightsTypeID = 10 then 'http://hdl.handle.net/10079/rfj6qd5' **OK**
			when ObjRights.ObjRightsTypeID = 20 then 'http://hdl.handle.net/10079/7h44j7v' **OK**
			when ObjRights.ObjRightsTypeID = 22 then 'http://hdl.handle.net/10079/nk98sp5' **OK**
			when ObjRights.ObjRightsTypeID = 23 then 'http://hdl.handle.net/10079/x0k6dsf' FIX to http://hdl.handle.net/10079/rfj6qd5
			when ObjRights.ObjRightsTypeID = 24 then 'http://hdl.handle.net/10079/s7h44rz' **OK**
			when ObjRights.ObjRightsTypeID = 25 then 'http://hdl.handle.net/10079/1rn8pss' FIX to http://hdl.handle.net/10079/rfj6qd5
			when ObjRights.ObjRightsTypeID = 26 then 'http://hdl.handle.net/10079/mpg4fcm' FIX to http://hdl.handle.net/10079/rfj6qd5
			when ObjRights.ObjRightsTypeID = 27 then 'http://hdl.handle.net/10079/nk98sp5' **OK**
			else 'http://hdl.handle.net/10079/c59zwbm' **OK**

**Comment by mxgold** [comment]
@yulgit1, I overlooked one change to the above, my apologies:

 ObjRights.ObjRightsTypeID = 24 (orphaned work) should direct to http://hdl.handle.net/10079/c59zwbm

**Comment by yulgit1** [comment]
@mxgold These should be corrected in prod now

https://github.com/ycba-cia/coboat-github/commit/0a54dc8eb8209367ef1c4a8d3b4eeecc89844c50
