### ISSUE TITLE
(1) Creator on results list vs. detail and (2) show all creators

### ISSUE THREAD

**Issue by mikeapp** [ycba-cia/blacklight-collections2#30]
On the results list page, creator needs to be the same field as on the detail pages.

For instance, https://ycba-collections-dev.herokuapp.com/catalog/1668417
Results list:  John Constable
Detail page: Attributed to John Constable, 1776–1837, British

**Comment by mikeapp** [comment]
Also, should display additional creators:

http://collections.britishart.yale.edu/vufind/Record/1668066
```
Attributed to John Constable, 1776–1837, British
Formerly John Constable, 1776–1837, British
```

https://ycba-collections-dev.herokuapp.com/catalog/1668066
```
Attributed to John Constable, 1776–1837, British
```
Missing the second value.

**Comment by yulgit1** [comment]
results list uses 'auth_author_display_txt"
 [
          "John Constable",
          "John Constable"
  ]
details page uses 'author_ss'
[
          "Attributed to John Constable, 1776–1837, British"
]
Which should be used?

**Comment by mikeapp** [comment]
Use `author_ss`
Is there another field that has both the "Attributed..." and "Formerly..." values?  If not, perhaps there's a field in the Vufind Solr that wasn't copied over.

**Comment by yulgit1** [comment]
There is no field in vufind or blacklight that has the "Formerly..." other than the full lido blob.

http://localhost:8380/solr/biblio/select?q=*:*&fq=id:1668066&wt=json&indent=true

https://search-index-dev.its.yale.edu/solr/ycba_collections_search/select?fq=id%3A1668066&wt=json&indent=true

fullrecord_txt
...
<lido:displayActorInRole>Formerly John Constable, 1776–1837, British</lido:displayActorInRole>
...

Perhaps vufind is doing an xpath on this field?  Is that necessary in blacklight?

**Comment by yulgit1** [comment]
...also because there is no field with "Formerly...", clicking on that line results in a empty facet lookup in vufind (no author,author2, or author_additional field with this value):

http://collections.britishart.yale.edu/vufind/Record/1668066

**Comment by yulgit1** [comment]
vufind is doing xpath:

$xml = new SimpleXMLElement($this->fields['fullrecord']);
			$result = $xml->xpath('//lido:eventActor/lido:displayActorInRole');

from /usr/local/vufind-prod/vufind-1.2/web/RecordDrivers/LidoRecord.php (ln 497)

**Comment by mikeapp** [comment]
It might be best to create a new field and process the LIDO in a separate rake task for now.

**Comment by yulgit1** [comment]
Created a new field actorInRole_ss using displayActorInRole xpath as in above comments.  However it appears now the underlying LIDO used to create the index is different that the LIDO in the harvester.

The harvester has:
<lido:eventActor>
<lido:displayActorInRole>Attributed to John Constable, 1776–1837, British</lido:displayActorInRole>
AND
<lido:eventActor>
<lido:displayActorInRole>Formerly John Constable, 1776–1837, British</lido:displayActorInRole>

The indexed LIDO just has
 <lido:eventActor>
<lido:displayActorInRole>Attributed to John Constable, 1776–1837, British</lido:displayActorInRole>

Given this also it is unclear whether to use author_ss or the new actorInRole_ss as they both have:
"Attributed to John Constable, 1776–1837, British"

**Comment by yulgit1** [comment]
Would help to have another example of this issue.

**Comment by yulgit1** [comment]
Final solution to this issueas tested with:

http://collections.britishart.yale.edu/oaicatmuseum/OAIHandler?verb=GetRecord&identifier=oai:tms.ycba.yale.edu:38502&metadataPrefix=lido

change
lido:eventActor[1]/lido:displayActorInRole
to
lido:eventActor/lido:displayActorInRole

This change picks up both "Attributed" and "Formerly" rather than the first.

**Comment by yulgit1** [comment]
fixed with:

https://github.com/yulgit1/ybca_xslts/commit/66a18c0b2d75e902d1288fd0c94db311999f6075
