### ISSUE TITLE
Display all non repository TMS titles as former titles in BlackLight

### ISSUE THREAD

**Issue by edgartdata** [ycba-cia/blacklight-collections2#301]
TMS titles can be:

- alternate
- collective
- creator's 
- exhibited
- foreign language
- former
- inscribed
- repository
- scratched 
- verso

In order to make the titles section clearer to users, we would like to add a new title heading to BlackLight: Former title(s).

So for B1970.1, the metadata block would look like this:

Title(s): (which would keep on getting the Repository Titles)
The family of Elihu Yale and an Enslaved Child

Former title(s): (to which all the other titles would be mapped to)
Elihu Yale; William Cavendish, the second Duke of Devonshire; Lord James Cavendish; Mr. Tunstal; and an Enslaved Servant
Elihu Yale, the second Duke of Devonshire, Lord James Cavendish, Mr. Tunstal, and a Page
The 2d Duke of Devonshire, Lord James Cavendish, Elihu Yale, an unknown adult male, and a page

**Comment by edgartdata** [comment]
Vend the title types for Art and RBMS items just before the actual titles (i.e. not on the left under Title(s)).

Repository titles would just stay as is.

**Comment by edgartdata** [comment]
Circling back to this issue because it has become a priority for Courtney and Martina. They want us to be able to clearly identify in the online collections catalog which titles are historical, and in what contexts they may have been created.

While identifying the historical titles of items in our collections will require significant curatorial research, can we please start thinking about ways to customize the BL metadata block to reflect a number of scenarios?

Here are the titles for [B1970.1](https://collections.britishart.yale.edu/catalog/tms:107):

-  The family of Elihu Yale and an Enslaved Child
- Elihu Yale; William Cavendish, the second Duke of Devonshire; Lord James Cavendish; Mr. Tunstal; and an Enslaved Servant
- Elihu Yale, the second Duke of Devonshire, Lord James Cavendish, Mr. Tunstal, and a Page
- The 2d Duke of Devonshire, Lord James Cavendish, Elihu Yale, an unknown adult male, and a page

Only the first one has a BL heading: Title(s). As I have mentioned above TMS has several title types (controlled vocabularies) and sometimes some not edited/not for public consumption source for the titles so we have some more metadata to contribute/refine for the BL UI if we wanted to.

I feel like a more careful nuanced contextualization of titles would benefit from a longer prose explanation (that would probably incorporate the title source in some fashion), and that this text might fit naturally in the new "Curatorial description" tab.

Thoughts welcome!

**Comment by yulgit1** [comment]
The coboat for LIDO seems to be configured properly for this:
```
<lido:titleWrap>
<lido:titleSet lido:type="Repository title">
<lido:appellationValue lido:pref="preferred" xml:lang="eng">The family of Elihu Yale and an Enslaved Child</lido:appellationValue>
</lido:titleSet>
<lido:titleSet lido:type="Former title">
<lido:appellationValue lido:pref="alternate" xml:lang="eng">
Elihu Yale; William Cavendish, the second Duke of Devonshire; Lord James Cavendish; Mr. Tunstal; and an Enslaved Servant
</lido:appellationValue>
</lido:titleSet>
<lido:titleSet lido:type="Former title">
<lido:appellationValue lido:pref="alternate" xml:lang="eng">
Elihu Yale, the second Duke of Devonshire, Lord James Cavendish, Mr. Tunstal, and a Page
</lido:appellationValue>
</lido:titleSet>
<lido:titleSet lido:type="Former title">
<lido:appellationValue lido:pref="alternate" xml:lang="eng">
The 2d Duke of Devonshire, Lord James Cavendish, Elihu Yale, an unknown adult male, and a page
</lido:appellationValue>
</lido:titleSet>
</lido:titleWrap>
```
So the "Repository title" would remain as is and passed to the manifest and displayed in the tombstone data as "Title" (change the label from "Title(s)" to "Title").  And all the non-"Repository title" title types(the other 3 in this case with type="Former Title") would need to get indexed together so as to display with a  new label "Historical Title(s)", or a label to that effect.

Other than entering into TMS seems very straightforward.  Am I missing anything?

Maybe the other thing EDG is hinting at is some kind of "Metadata Remediation" tab with a detailed chronological logged description of the metadata changes, sources of gender labels, etc, which again other than entering in TMS, should be fairly straightforward.

**Comment by edgartdata** [comment]
We talked about adding 2 additional title categories/headings in the BL UI for art and RB records to bring clarity when a work or item has several titles. These 2 additional categories to place under _Title(s)_ are: _Former title(s)_ and A_lternate title(s)_

TMS mapping:

1. TMS title type _Repository_ --> BL UI Title(s)
2. TMS title types _Former_ and _Exhibited_ --> new BL UI _Former_ title(s) category
3. TMS title types _Foreign Language_, _Inscribed_, _Scratched_, and Verso --> new BL UI Alternate _title(s)_ category

@flapka What would be the concordance with RBMS?

**Comment by edgartdata** [comment]
Let's deploy in DEV

**Comment by edgartdata** [comment]
Review the sequence with specific examples.

EDG to mock up an example that has several title types.

**Comment by flapka** [comment]
@edgartdata For clarification, which labels will be shown in Blacklight? Just the three: Title, Former title(s), and Additional title(s)? Or will we also show the more specific labels, such as "Repository", "Exhibited", "Inscribed" and so on?

**Comment by edgartdata** [comment]
@flapka We discussed this very question last week and decided for now in DEV to first try with just the 3 labels for Title, Former titles, and Additional titles. If after review we think the 3 labels are not clear enough, we will consider adding the more specific title labels.

**Comment by flapka** [comment]
@edgartdata @yulgit1 With that in mind, the MARC mapping is:
* Title: MARC 245 (already mapped)
* Additional title(s): use the existing MARC mapping in the title_alt template -- i.e. from MARC 130 (uniform title), 240 (uniform title), and 246 (varying form of title)
* Former title(s): map from MARC 247 (former title)

**Comment by yulgit1** [comment]
@edgartdata No need to mock up an example as you were going to do per above, I was able to put together a test object for use in oxygen.  The numbers in the comments are the objects where the example was pulled from.

```
<lido:titleWrap>
<lido:titleSet lido:type="Repository title">
<lido:appellationValue lido:pref="preferred" xml:lang="eng">
Dort or Dordrecht: The Dort Packet-Boat from Rotterdam Becalmed
</lido:appellationValue>
</lido:titleSet>
    <!--22877-->
    <lido:titleSet lido:type="Creator's title">
        <lido:appellationValue lido:pref="alternate" xml:lang="eng">Natural Selection</lido:appellationValue>
    </lido:titleSet> 
    <!--81-->
    <lido:titleSet lido:type="Former title">
        <lido:appellationValue lido:pref="alternate" xml:lang="eng">Two Women on a Sofa, 1875</lido:appellationValue>
    </lido:titleSet>
    <!--8-->
    <lido:titleSet lido:type="Exhibited title">
        <lido:appellationValue lido:pref="alternate" xml:lang="eng">Margaret Tyers and her husband, George Rogers</lido:appellationValue>
    </lido:titleSet>
    <!--7-->
    <lido:titleSet lido:type="Alternate title">
        <lido:appellationValue lido:pref="alternate" xml:lang="eng">The Building of a Canal (The Bude Canal?)</lido:appellationValue>
    </lido:titleSet>
    <!--2112-->
    <lido:titleSet lido:type="Inscribed title">
        <lido:appellationValue lido:pref="alternate" xml:lang="eng">
            The Guards on the March for the Duke of York's Campaign in Flanders
        </lido:appellationValue>
    </lido:titleSet>
    <!--3132-->
    <lido:titleSet lido:type="Verso title">
        <lido:appellationValue lido:pref="alternate" xml:lang="eng">Sketches of Islands</lido:appellationValue>
    </lido:titleSet>
    <!--17836-->
    <lido:titleSet lido:type="Foreign language title">
        <lido:appellationValue lido:pref="alternate" xml:lang="eng">
            The Environs of London, Vol.II: Memorial to Thomas Weldish from Bedfont Church
        </lido:appellationValue>
    </lido:titleSet>
    <!--46491-->
    <lido:titleSet lido:type="Scratched title">
        <lido:appellationValue lido:pref="alternate" xml:lang="eng">Standing Figures in Church</lido:appellationValue>
    </lido:titleSet>
</lido:titleWrap>
```

And here's the mapping to be implemented:
```
Collective title			<exclude>
Creator's title			Title
Alternate title			Additional
Former title			Former
Repository title		Title
Inscribed title			Additional
Verso title			Additional
Foreign language title		Additional
Exhibited title			Former
Scratched title			Additional
```

**Comment by yulgit1** [comment]
XSLT revised marc and lido, indexing tonight:
https://git.yale.edu/ermadmix/ycba_xslts/commit/7be1bdccde22deeca9d26133e5e03154dba78593

**Comment by yulgit1** [comment]
@flapka - do need to ask for example Marc  to verify these changes with, with exception of 245 which I have already: 

245 -  title primary
130,240,246 - additional
247 - former

**Comment by flapka** [comment]
@yulgit1 Examples of additional title(s) -- which we currently label alternate title(s):
* 130 (uniform title): https://collections.britishart.yale.edu/catalog/orbis:6469854
* 240 (uniform title): https://collections.britishart.yale.edu/catalog/orbis:13576560
* 246 (varying form of title): https://collections.britishart.yale.edu/catalog/orbis:9882320

Example of former title(s), MARC 247:
* https://collections.britishart.yale.edu/catalog/orbis:3318550

**Comment by yulgit1** [comment]
See examples below with their LIDO types and mapping to labels. (Prefix with: https://collections-test.britishart.yale.edu/)


catalog/tms:22877 Repository title, Creator's title, Inscribed title -> Titles(s), Additional Titles(s)
catalog/tms:81 Repository title, Former title -> Titles(s), Formal Titles(s)
catalog/tms:8 Repository title, Exhibited title, Alternate title -> Titles(s), Formal Titles(s), Additional Titles(s)
catalog/tms:3132 Repository title, Verso title -> Titles(s), Additional Titles(s)
catalog/tms:17836 Repository title, Foreign language title, Collective Title -> Titles(s), Additional Titles(s), Part Of
catalog/tms:3132 Repository title, Scratched title -> Titles(s), Additional Titles(s)
catalog/orbis:6469854 245,130 -> Title(s), Additional Title(s)
catalog/orbis:13576560 245,240 -> Title(s), Additional Title(s)
catalog/orbis:9882320 245, 246 -> Title(s), Additional Title(s)
catalog/orbis:3318550 245, 247, 130 -> Title(s), Former Titles(s), Additional Title(s)

**Comment by flapka** [comment]
@yulgit1 The RBM examples look correct. Thanks.

**Comment by edgartdata** [comment]
Thanks for these examples Eric! Is access to https://collections-test.britishart.yale.edu to specific YCBA staff members or can anyone who knows the URL have access, like P&D colleagues?

**Comment by yulgit1** [comment]
It is open.

**Comment by edgartdata** [comment]
The mapping of TMS titles is correct too.
(just noting here - and that's not a change in the mapping - that https://collections-test.britishart.yale.edu/catalog/tms:46491 is the correct example for a scratched title, not https://collections-test.britishart.yale.edu/catalog/tms:3132)

Noting here that I like the way Part of: Collective Title is right below all the title labels https://collections-test.britishart.yale.edu/catalog/tms:17836 

![image](https://user-images.githubusercontent.com/4093644/122279030-98081100-ceb5-11eb-85cd-3eaf83676585.png)

**Comment by edgartdata** [comment]
Might need to add 'Sale title(s)' as a new title type. TBD.  Not ready for production yet.

**Comment by edgartdata** [comment]
@yulgit1 Thanks for reinstituting https://collections-test.britishart.yale.edu/catalog/tms:xxxxxx !

**Comment by edgartdata** [comment]
@yulgit1 New TMS mapping as of July 9, 2021 (I have highlighted the changes in bold):

- TMS title type Repository **(only Repository now, i.e. we are not mapping the Creator's title type to Repository anymore)** --> BL UI Title **(take '(s)' out of 'Title(s)' heading)**
- TMS title types Former, **Creator's** and Exhibited --> new BL UI Former title(s) category
- TMS title types Alternate, Foreign Language, Inscribed, Scratched, and Verso --> new BL UI Additional title(s) category
-

**Comment by edgartdata** [comment]
7/9/2021:
Contextualization of some titles will come through provenance. No need to map a new TMS field for the source of the titles to BL.

In TMS, cataloguers and curators will sort titles chronologically with the most recent at the top. The most recent will also get the title type of Repository title and be displayed in BlackLight with the heading _Title_. The subsequent titles will not get the title type of Repository (in fact COBOAT will not accept more than 1 repository title per object record). 

@EdwardTown1 The title types that we currently have available in TMS (alternate, creator's, exhibited, foreign language, former, inscribed, repository, scratched, verso) might be enough for now but we can create new ones as needs arise.

**Comment by yulgit1** [comment]
Resolved:
https://github.com/ycba-cia/blacklight-collections2/commit/4c9bd759375405e09b35b6ebd2cf83d368e9e0e8
https://git.yale.edu/ermadmix/ycba_xslts/commit/e004b629f35306ff7242df1ff2a0cf8f39ae20f0

Reindexing over weekend.

**Comment by edgartdata** [comment]
On 8/6: 
Auction titles should go under Former Titles. 
Reassess alternate titles: can most of them become former titles?
![Order of titles](https://user-images.githubusercontent.com/4093644/129071020-2dd36cc8-13aa-4262-a0a2-b5e1c9f845bf.png)

**Comment by edgartdata** [comment]
@yulgit1 Thanks for programmatically changing in TMS all accessioned P&S Alternate titles to Former titles, they are now coming through BlackLight nicely.

**Comment by edgartdata** [comment]
@yulgit1 If you are looking for examples of records that have former titles that were published in the YCBA 1985 Concise Catalogue, here are a few objectIDs: https://collections.britishart.yale.edu/catalog/tms:135 and https://collections.britishart.yale.edu/catalog/tms:124

Sometimes, the repository title itself will have its source mentioned in square bracket too, such as https://collections.britishart.yale.edu/catalog/tms:155

**Comment by yulgit1** [comment]
Added TitleRemarks for Remarks that are in brackets

https://github.com/ycba-cia/coboat-github/commit/6c5aeec8762339ad028a8476177c447754a02ad0

harvester-test to run overnight

next steps - promote to prod and implement BL indexing and BL UI

**Comment by yulgit1** [comment]
Harvester-test Looks good:
https://harvester-test.britishart.yale.edu/oaicatmuseum/OAIHandler?verb=GetRecord&identifier=oai:tms.ycba.yale.edu:124&metadataPrefix=lido
https://harvester-test.britishart.yale.edu/oaicatmuseum/OAIHandler?verb=GetRecord&identifier=oai:tms.ycba.yale.edu:155&metadataPrefix=lido

again next steps - promote to prod and implement BL indexing and BL UI
