### ISSUE TITLE
Center / Study Room reopening -- messaging in Blacklight

### ISSUE THREAD

**Issue by flapka** [ycba-cia/blacklight-collections2#302]
As the Center will re-open on June 4, and the Study Room on June 1, how & when do we want to modify the current notices in Blacklight?

* Can we delete the pink banner at top of the Blacklight interface after June 1? Is it worthwhile to post an interim message about the dates of reopening?
* For the access note that appears with P&D, RBM, and IA records ("Note: As a COVID-19 precaution, the Study Room is closed until further notice."), do we want a variant message before June 1, along the lines of "The Study Room will reopen June 1, 2021, by appointment only"?

**Comment by robl** [comment]
The banner message will want to remain closely coordinated with the banner on the main (Drupal) website; once new banner text is in hand for that site, I can let this group know.

**Comment by KraigBinkowski** [comment]
"Note: As a COVID-19 precaution, the Reference Library is closed until further notice. For scans from the reference collection please email ycba.reference@yale.edu."  --- Reference Library access note should also change in accord with the P&D and RBM note for the June 1 opening. 
Ref would still like to maintain the "For scans from the...." note at the end of the access note.

**Comment by edgartdata** [comment]
And the new text for the overall banner is:
The Center reopens June 4. Free and open to the public. The Reference Library and Study Room will reopen to Yale ID holders on June 1 by appointment only.

**Comment by KraigBinkowski** [comment]
The Center opening on June 4 can also be deleted from the Ref Library holdings and to be consistent with RB: 

Note: The Reference Library will reopen to Yale ID holders on June 1 by appointment only. Please visit the Reference Library page on our website for more details.  For scans from the reference collection please email ycba.reference@yale.edu.

Reference Library page should link to: https://britishart.yale.edu/reference-library-and-photograph-archives

**Comment by edgartdata** [comment]
And we will check https://britishart.yale.edu/visitor-guidelines for latest reopening information.

**Comment by yulgit1** [comment]
rather than:

"The Study Room will reopen to Yale ID holders on June 1 by appointment only. Please visit the Study Room page on our website for more details."

maybe:

"The Study Room reopens to Yale ID holders on June 1 by appointment only. Please visit the Study Room page on our website for more details."

so the tense is valid after June 1.

**Comment by yulgit1** [comment]
June 1 opening addressed: https://github.com/ycba-cia/blacklight-collections2/commit/48724d5c608fd0b60ab28bb7d0b5e55720769e76

Examples:
RB: https://collections.britishart.yale.edu/catalog/orbis:11621093
P&D: https://collections.britishart.yale.edu/catalog/tms:10940
IA: https://collections.britishart.yale.edu/catalog/orbis:14473139
REF: https://collections.britishart.yale.edu/catalog/orbis:3157213

**Comment by KraigBinkowski** [comment]
Looks good to me

**Comment by edgartdata** [comment]
Just a reminder to all here that collection access messaging in BlackLight will probably need to be updated when the Center reopens fully to the public in August. We will need to coordinate with Communications ahead of time.
