### ISSUE TITLE
Subject terms should not contain names of People or Places

### ISSUE THREAD

**Issue by mikeapp** [ycba-cia/blacklight-collections2#31]
`Parry, Ann (fl. 1778)` appears in both People and Subject Terms
https://ycba-collections-dev.herokuapp.com/catalog/3622228

Geographic terms/places from Place(s) Represented appear in Subject Terms
https://ycba-collections-dev.herokuapp.com/catalog/3622230

**Comment by yulgit1** [comment]
This is a metadata isssue, terms are coming from the following solr fields:
Subject Terms - topic_facet
People Represented or Subject - topic_subjectActor_ss
Places Represented - geographic_facet

**Comment by yulgit1** [comment]
in the xsl topic_facet and topic_t(which is used as topic_ss in blacklight) are populated in the following templates:

topic (647)
topic_subjectConcept (963)
topic_subjectActor (977) x
topic_subjectEvent (991)
topic_subjectPlace (1005)x
topic_subjectObject (1025)

Will remove these from topic_subjectActor and topic_subjectPlace to address the original reason for this issue.

Question:   Should these be removed from subjectConcept, subjectEvent, and subjectObject as well, to be consistent? Note these fields aren't used in blacklight, so not sure it even matters.

**Comment by yulgit1** [comment]
furthermore 'topic' (was line 647 in xml) maps to

```
    <xsl:template name="topic">
        <xsl:for-each select="lido:objectRelationWrap/lido:subjectWrap/lido:subjectSet/lido:subject">
            <xsl:choose>
                <xsl:when test="@lido:type='iconography'">
                    <xsl:for-each select="lido:subjectConcept/lido:term">
                        <xsl:element name="topic_facet">>
                            <xsl:value-of select="normalize-space(.)"/>
                        </xsl:element>
<xsl:element name="topic_t">
```

should this be kept?

**Comment by yulgit1** [comment]
fixed with:
https://github.com/yulgit1/ybca_xslts/commit/08d7441efaf388ea63f0d54d7674c40481abbf10
