### ISSUE TITLE
BlackLight record counter bug

### ISSUE THREAD

**Issue by edgartdata** [ycba-cia/blacklight-collections2#314]
When I enter a URI directly in Chrome, say https://collections.britishart.yale.edu/catalog/tms:856, top left above the image viewer BlackLight tells me it is the second record out of three, when surely https://collections.britishart.yale.edu/catalog/tms:856 is for only one record. Does anyone else get this too?

![Bug with search for specific record](https://user-images.githubusercontent.com/4093644/128029900-42811211-a017-4bae-bfd7-412544b43291.png)

**Comment by flapka** [comment]
Similar results for me. When I enter the same URL (or a URL for any other object), it displays as 2 of 129. The 129 refers to the number of search results for the most recent search I executed in Blacklight; and if I click on the "Back to Search" link, Blacklight will re-retrieve those search results.

**Comment by yulgit1** [comment]
This is the artifact of a session variable.  It stores your last search for the values of "Previous", "x of y","Next"," and "Back to Search".  It cannot distinguish if you got to this page via a search (where you'd want these), or if you came to the item page from somewhere else (where these shouldn't show).  I've explored timing out the session (but who's to say how long to wait to timeout, maybe it's better to persist longer and not lose this), and adding a HTTP GET parameter from search results (to flag that you are indeed coming to the item page from a search), and concluded it's not worth the depth of customization involved to implement.  So for now you can either click on these links and see the state of your last search (whether from one minute ago or several days day ago) or ignore the links if they don't apply.

**Comment by edgartdata** [comment]
@flapka @yulgit1 Sounds like this would require a lot of time and effort for little benefit?

**Comment by flapka** [comment]
Low priority for me
