### ISSUE TITLE
Image display when primary image ≠ image ranked first

### ISSUE THREAD

**Issue by flapka** [ycba-cia/blacklight-collections2#319]
@yulgit1 @mxgold RB would like to know if it's possible to adjust how images are currently ordered in an object record when the primary image ≠ the image ranked first.

This comes up a lot in RB. The [Helmingham herbal](https://collections-test.britishart.yale.edu/catalog/orbis:9452785) illustrates:
* for sequencing, the front cover has the first ranking; the cover is however rather plain, and doesn't convey anything useful about the primary content, so we'd rather not select it as primary
* the opening at folios 16v-17r are much more appealing as representative of the object content, so we've made it primary
* because 16v-17r is primary, it appears out of sequence, i.e. before all other thumbnails (and absent from where the image's rank should place it, between 15v-16r and 17v-18r)

What's do-able under these circumstances? For items such as the Helmingham example, RB's order of preference would be as follows, depending on feasibility:
1. Upon opening the object record, display the primary image *and* have that thumbnail appear in its proper location within the sequence
2. Upon opening the object record, display the image ranked first *and* have the primary thumbnail appear in its proper location within the sequence (but keep the primary image as the image that shows in the context of search results)
3. [status quo]

**Comment by yulgit1** [comment]
Maybe ingest into NETX a copy of the primary image and rank it so it occurs at the right place in the sequence.

**Comment by edgartdata** [comment]
Same issue treated in https://github.com/ycba-cia/blacklight-collections2/issues/331
