### ISSUE TITLE
Use of back button can result in duplicate IIIF icons

### ISSUE THREAD

**Issue by mikeapp** [ycba-cia/blacklight-collections2#32]
The Javascript fires again?

<img width="459" alt="screen shot 2017-11-09 at 1 59 14 pm" src="https://user-images.githubusercontent.com/1987952/32624123-49f9815e-c556-11e7-8feb-f202f0b58f36.png">

**Comment by yulgit1** [comment]
fixed with 

https://github.com/ycba-cia/blacklight-collections2/commit/0ae40ab0aab6656a7b58a2a87c383727c11f8ce8
