### ISSUE TITLE
IIIF manifest Description concatenation for TMS objects

### ISSUE THREAD

**Issue by edgartdata** [ycba-cia/blacklight-collections2#332]
@yulgit1 Right now the description field of manifests for TMS objects is a concatenation of the first alternate title + dimensions.

Because the primary title and the dimensions are captured in other manifest fields, I wonder if we could get rid of the description? Are there implications on processes?

![IIIF manifest description for TMS objects](https://user-images.githubusercontent.com/4093644/142271889-91a3a76b-72b1-4c5a-8083-b31423fb9cbb.png)

**Comment by edgartdata** [comment]
@yulgit1 @flapka Revisiting this issue to see if you have objections to my suggestion. I note that the IIIF manifest Description (which is first alternate title + dimensions) has the same behavior in UV:
![sketchbook Github issue 332](https://user-images.githubusercontent.com/4093644/154089917-e20eff74-f1de-42fc-905e-97c422049214.png)

**Comment by Lcallery** [comment]
@flapka @yulgit1 To the best of my knowledge- Francis is correct regarding the "description" field.

**Comment by edgartdata** [comment]
@yulgit1 okay to delete the description field when you have a minute.

**Comment by yulgit1** [comment]
Should be all set.
