### ISSUE TITLE
Can date facet incorporate the latestDate_ss field?

### ISSUE THREAD

**Issue by flapka** [ycba-cia/blacklight-collections2#334]
So far as I can tell, our Blacklight date facet (limit) looks only at data in the earliest_date field, ignoring data in latest_date (the latter valid when there are a range of date possibilities). Ideally the facet would act upon data from both. Is that possible?

Apologies if this question has been asked/discussed already.

**Comment by yulgit1** [comment]
Right, each facet takes one solr field, and for range limit facets that field has to be an integer.  Our implementation is with earliestDate_is:

`config.add_facet_field 'earliestDate_is', :label => 'Date', single: true,range: { segments: false }`

There is a latestDate_is field that could be used in another facet in tandem though.

Of note, there is also the 'single: true' parameter,  don't know what it does, if anything.  But I don't think it enables a multi field configuration.

https://github.com/projectblacklight/blacklight_range_limit

**Comment by flapka** [comment]
Thanks @yulgit1 . Your response triggers a memory that we may have discussed this as a group before, concluding that we didn't want the complexity of a second facet for latest date.

I wondered if YUL had implemented a solution to this in their implementations of Blacklight (Quicksearch and the new DCS). Interesting to compare the date facet in the places for this search that results in one item:
* Quicksearch: https://search.library.yale.edu/catalog?utf8=%E2%9C%93&adv%5B1%5D%5Bfield%5D=all_fields&adv%5B1%5D%5Bvalue%5D=Britannia+prout+Jansson+1652&adv%5B2%5D%5Bop%5D=AND&adv%5B2%5D%5Bfield%5D=title&adv%5B2%5D%5Bvalue%5D=&adv%5B3%5D%5Bop%5D=AND&adv%5B3%5D%5Bfield%5D=author&adv%5B3%5D%5Bvalue%5D=&range%5Bpub_date_sort%5D%5Bbegin%5D=&range%5Bpub_date_sort%5D%5Bend%5D=&commit=Search&search_field=advanced
* DCS: https://collections.library.yale.edu/catalog?op=AND&sort=score+desc%2C+pub_date_si+desc%2C+title_si+asc&all_fields_advanced=&fulltext_search=1&search_field=all_fields&fulltext_search=1&q=Britannia+prout+Jansson+1652

Looks like they've figured out how to do it in the DCS, but not in Quicksearch (where it looks like they're taking the average 
of the earliest and latest date -- how strange)

This isn't a high priority -- more of a wish list for a rainy day.
