### ISSUE TITLE
Keywords for frames 

### ISSUE THREAD

**Issue by edgartdata** [ycba-cia/blacklight-collections2#338]
Just capturing here my conversation with Eric yesterday about displaying in BLackLight the types of keywords associated with frames in the Subject Terms section of a frame record. So the result in Blacklight for https://collections.britishart.yale.edu/catalog/tms:65464 would be:

Subject Terms: Frame alteration: no alteration | Frame cross-section: Shallow scotia with frieze | frame ornament: Pierced corner foliate scroll-&-sunflower | Frame feature: crest | Frame feature: emblematic | ...

**Comment by yulgit1** [comment]
Example LIDO
From:
```
<lido:subjectConcept>
<lido:conceptID lido:source="YCBA" lido:type="local">ycba_term_2041836</lido:conceptID>
<lido:term>no alteration</lido:term>
</lido:subjectConcept>
```
To:
```
<lido:subjectConcept>
<lido:conceptID lido:source="YCBA" lido:type="local">ycba_term_2041836</lido:conceptID>
<lido:term>Frame alteration: no alteration</lido:term>
</lido:subjectConcept>
```
etc.

Use convert(varchar(40),thesxreftypes.thesxreftype) as thesxreftype from aatkeywords.txt

Add thesxreftype  to first pass, and concatenate into subjectConcept term

**Comment by edgartdata** [comment]
![YCBA frame with keyword and keyword type in BL record](https://user-images.githubusercontent.com/4093644/151571818-ffd098e9-bd70-4fb1-aaa1-c9ac4ce65a9e.png)


![Frame keyword facet with keyword types](https://user-images.githubusercontent.com/4093644/151569012-7bee3f31-e371-41da-937b-c429802655de.jpg)
