### ISSUE TITLE
Universal Viewer - populate download modal with image selected in the embedded UV 

### ISSUE THREAD

**Issue by yulgit1** [ycba-cia/blacklight-collections2#344]
https://github.com/ycba-cia/blacklight-collections2/commit/3efc7cf071b354250805b4db3caa3eb06c9d15bd
https://github.com/ycba-cia/blacklight-collections2/commit/3abc794c347f54d4bb4710126e48082ebdecd1fd

Before screenshot:
![Screen Shot 2022-02-01 at 3 57 28 PM](https://user-images.githubusercontent.com/2125400/152051254-13a3e9d2-eb1b-44eb-af75-706cd030e2fb.png)

After screenshot:
![Screen Shot 2022-02-01 at 3 56 18 PM](https://user-images.githubusercontent.com/2125400/152051302-172f8753-ee87-4611-9c11-4284062bbd41.png)

**Comment by flapka** [comment]
@yulgit1 @Lcallery 

The after looks nice! Could we remove (do we want to remove) the number that precedes the short caption -- i.e. the "5." in the example above?  To me that number is unnecessary, may cause mild confusion.

**Comment by yulgit1** [comment]
@flapka easy to remove the index number.  But I kept it there to disambiguate for objects where every image has the caption like "Courtesy of YCBA".

**Comment by flapka** [comment]
@yulgit1 @Lcallery. Is it possible (and desirable) for the index number to appear conditionally (if the short caption is null or says "Courtesy of YCBA")?

**Comment by yulgit1** [comment]
@flapka possible, but maybe not desirable for consistency and maintainability reasons (baking "Courtesy of YCBA" into the logic).

**Comment by flapka** [comment]
Yes, I think we can consider this resolved with no additional changes.
