### ISSUE TITLE
P&D sketchbook-John Flaxman-Seventeen Sketches chiefly of Mrs. Siddons

### ISSUE THREAD

**Issue by edgartdata** [ycba-cia/blacklight-collections2#345]
@annabozz 
The online parent record for the whole sketchbook (B1977.14.1897-1913) is online at https://collections.britishart.yale.edu/catalog/tms:14234
It contains 17 pages: from B1977.14.1897 to B1977.14.1913
Imaging will need to rename/reingest and republish interior/individual images with the parent object ID.
new primary selection will be B1977.14.1898- https://collections.britishart.yale.edu/catalog/tms:67367

**Comment by annabozz** [comment]
Contact sheet of images submitted, and Amelia in P&D confirmed that order of images is correct

**Comment by annabozz** [comment]
3/18: renamed images for parent record ingested

future, 3/21: Anna will clean up TMS record for B1977.14.1897-1913 and release images online if timing ok with @edgartdata

**Comment by annabozz** [comment]
3/22 update: 

- images in overall TMS record cleaned up (B1977.14.1897-1913)
- images released online, including masonary image: https://collections.britishart.yale.edu/catalog/tms:14234

**Comment by edgartdata** [comment]
@LaurelOP John Flaxman's sketchbook of 17 sketches of Mrs Siddons is ready for your review: https://collections.britishart.yale.edu/catalog/tms:14234 
All the individual Blacklight records for the individual sketchbook pages have been unpublished from the online catalog.

**Comment by annabozz** [comment]
Thanks @edgartdata  and @LaurelOP 

after ok'ed, I can send Amelia and David the NETX collection to update Image Captions. will wait for now.

**Comment by annabozz** [comment]
@LaurelOP  and @edgartdata 

Just emailed Amelia, David, and Laurel the NetX collections so that Image Captions can be added

**Comment by annabozz** [comment]
Update to implement masonry new image function

Masonry: "Oberon. There sleeps Titania, some time of the night..."

1. duplicate file (ba-obj-14234-0023-pub):
- unpublished online
- moved to NetX "pending deletion" folder
- deleted from TMS

2. image in sequence marked as masonry set as CDS 2 (ba-obj-14234-0007-pub)
