### ISSUE TITLE
P&D sketchbook-Anne Rushout-

### ISSUE THREAD

**Issue by edgartdata** [ycba-cia/blacklight-collections2#346]
@annabozz 
Anne Rushout (B1977.14.9506-9587)  - is actually 3 volumes.
Current parent B1977.14.9506V https://collections.britishart.yale.edu/catalog/tms:55959
Sounds like PD will be adding these two additional parent or group records so there is one group record to represent each volume: B1977.14.9540V and B1977.14.9563V
We will then need to rename/reingest and republish the images with two new sets of object IDs.
New Primary selection given: B1977.14.9531- https://collections.britishart.yale.edu/catalog/tms:45951 .  This image is in volume 1.  Will need primaries for the two new group records.

**Comment by edgartdata** [comment]
@annabozz Please let me know when I need to unpublish B1977.14.9506V's individual page records from the online catalog and publish the TMS records for B1977.14.9540V and B1977.14.9563V to the online catalog.

**Comment by annabozz** [comment]
@edgartdata @mxgold @yulgit1  Please confirm crops of three masonary images below, one for each volume. I assume I am preparing these for ingest the same method as Turner sketchbook image (duplicate, bump up iteration in filename).

And when it's time to publish later at the appropriate step.. 
These are: **CDS primary = 1**
**Rank = ???**



Below: Vol. 1: B1977.14.9506V, range B1977.14.9506- 9539
Masonary image: B1977.14.9531   (new filename: ba-obj-55959-0083-pub)

![B1977 14 9531](https://user-images.githubusercontent.com/74676099/154345491-0bbb93c7-ec9e-4934-90f6-ed27d058279c.png)



Below: Vol 2: B1977.14.9540V, range B1977.14.9540- .9562
Masonary image: B1977.14.9542   (new filename: ba-obj-83376-0026-pub)

![B1977-14-9542](https://user-images.githubusercontent.com/74676099/154345492-92478ab2-3578-48fa-aa07-d25bfe5392b7.png)



Below: Vol. 3: B1977.14.9563V, range B1977.14.9563- .9587
Masonary image: B1977.14.9569    (new filename: ba-obj-83377-0027-pub)

![B1977-14-9569](https://user-images.githubusercontent.com/74676099/154345493-5b877a24-3fe3-43dd-8220-da9ef34a8db8.png)

**Comment by yulgit1** [comment]
@annabozz Rank =  ??? = <a negative number> so it's appears as thumb in masonry but not in IIIF viewer rendering all the items. But this is what will be, but not yet implemented.

**Comment by yulgit1** [comment]
Just noting here as of now we have these blockers:

"Preservica upgrade to v6 is still underway or not completed yet
Some workflows including asset DELETE is still not available"

"Re: IIIF manifest | thumbnails and ordering" is not yet ready

**Comment by annabozz** [comment]
Based on this, will hold off on ingesting duplicate masonary images until ready, and will ask Bob to ingest reorganized pages only (for vols 2 and 3)

**Comment by edgartdata** [comment]
@annabozz To answer your previous question: yes, the crops as you have them are good to use as masonry images. They are consistent with Laurel's preference of showing their border/that they are part of a sketchbook. So they are okay to ingest when the Preservica upgrade is done. Thanks Anna.

**Comment by edgartdata** [comment]
@annabozz 
In TMS today I see that B1977.14.9563 is related to both Vol1 B1977.14.9540V and Vol 2: B1977.14.9540V. Not sure if Amelia could double check which volume B1977.14.9563 is actually in?
![image](https://user-images.githubusercontent.com/4093644/154757575-eb2e50c9-2b34-4760-aa32-ad55b8406da0.png)

**Comment by edgartdata** [comment]
@annabozz I will wait for you to let me know when the order of images for volume 1 is resolved. Once it is clarified I will unpublish the individual page records for volume 1 from the online catalog (I do this by putting these TMS records into one of my personal TMS object packages that only contains objects to not publish online anymore).
The CDS2 levels of the images will be different from what they are today?

**Comment by annabozz** [comment]
Now have confirmation from P&D that order of images in volume 1 spreads is ok.

Questions for @edgartdata and @mxgold
 
1. Ok for me to unpublish the extra records from Volume 1 at this time?

2. Also please let me know when ok to publish newly organized images from Volume 2 and Volume 3 to the online catalogue. 
Is it preferred that they are not published until the page titles go into the Image Caption fields (better to wait) or should go ahead?

**Comment by edgartdata** [comment]
@annabozz 

1. Given that P&D confirmed the order of the images you have for volume 1, yes it is okay to unpublish the vol.2&3 images from vol.1. aka B1977.14.9506V.
2. I would think it is okay to go ahead with getting images ready for vol. 2&3 before the captions/page titles are ready.

**Comment by edgartdata** [comment]
@annabozz I have just flagged Vol 2: B1977.14.9540V and Vol. 3: B1977.14.9563V in TMS now so that they appear in the online catalog tomorrow. 
I will also unpublish from BlackLight the individual page records for vol.1 B1977.14.9506V.

**Comment by edgartdata** [comment]
All 3 Rushout sketchbooks are now online. Thank you to @annabozz @bobhixon and P&D for your work on them! 
https://collections.britishart.yale.edu/catalog/tms:55959
https://collections.britishart.yale.edu/catalog/tms:83376
https://collections.britishart.yale.edu/catalog/tms:83377

**Comment by edgartdata** [comment]
@yulgit1 Documenting here what needs to be done by Imaging for the masonry images to only appear in the masonry view (and not the image ribbon once Seong implements our change request to IIIF manifest):

- Publish the thumbnail image with cds_access_jpeg = 'P'
- Set the width and height limits of the thumbnail
- cdsrank = -1
- cdsprimary = 1

Is it still correct?

**Comment by mxgold** [comment]
My understanding is any CDSrank <1 would result in the image being excluded from the ribbon...that being the case imaging would be likely to use rank=0 rather than -1 (but technically either would work, I guess?) @yulgit1 please correct me if I misunderstand!

**Comment by annabozz** [comment]
masonary views for 3 Rushout sketchbooks now batched ingest; will push through after new ingest hold lifted - will update here when ingested and published online

**Comment by annabozz** [comment]
Masonary views ingested and CDS2 levels altered, and now appearing online first in ribbon.  Expect that images in actual masonary view will be updated within a day!

VOLUME 1: https://collections.britishart.yale.edu/catalog/tms:55959
 
VOLUME 2: https://collections.britishart.yale.edu/catalog/tms:83376
 
VOLUME 3: https://collections.britishart.yale.edu/catalog/tms:83377

**Comment by annabozz** [comment]
**Vol. 1: B1977.14.9506V, range B1977.14.9506- 9539**

Update to implement masonry new image function

Masonry: "Grove Cottage, Wanstead May 18th, 1825"

1. duplicate file (ba-obj-55959-0083-pub):
- unpublished online
- moved to NetX "pending deletion" folder
- deleted from TMS

2. image in sequence marked as masonry set as CDS 2 (bx)

**Comment by annabozz** [comment]
**Vol. 3: B1977.14.9563V, range B1977.14.9563- .9587**

Update to implement masonry new image function

Masonry: "Mr. Mark's Cottage, Wanstead, May 1829"

1. duplicate file (ba-obj-83377-0027-pub):
- unpublished online
- moved to NetX "pending deletion" folder
- deleted from TMS

2. image in sequence marked as masonry set as CDS 2 (ba-obj-83377-0009-pub)
