### ISSUE TITLE
P&D sketchbook-William Hodges-Select Views from India Vol. 1

### ISSUE THREAD

**Issue by edgartdata** [ycba-cia/blacklight-collections2#347]
@annabozz 

TMS parent record B1978.43.1722V only has images for the cover; In addition there are 30 child records: B1978.43.1722-1751 and each of them have images
Imaging will need to rename/reingest and republish interior/individual images to the parent object ID.  
Note: As an album  with tipped in drawings rather than a sketchbook, only single pages/drawings were photographed as opposed to double page spreads.
New primary selection will be https://collections.britishart.yale.edu/catalog/tms:10465

**Comment by annabozz** [comment]
Will begin steps on this sketchbook Monday, 3/28

**Comment by annabozz** [comment]
3/28: Amelia confirmed page order via contact sheet

**Comment by edgartdata** [comment]
Laurel in favor of having the inside images show horizontally so that they are easier to read but leave the covers show vertically.

**Comment by annabozz** [comment]
Images ingested of interior images into NetX (covers already in overall record). Anna working on:

1. Releasing images online
2. ranking media/images in TMS
3. preparing primay, masonary image

**Comment by annabozz** [comment]
Steps above complete!

Will give P&D colleagues access to the NetX collection so that Image Captions can be added. P&D will be able to after @bobhixon adjusts permissions for images, this part of the process I forgot about in the past.

NetX collection name will be:  **P&D Hodges Vol 1: B1978.43.1722V pubs**

**Comment by edgartdata** [comment]
Great, thanks @annabozz !

Per Laurel's request, I will wait until the page-level titles are entered in the master record to unpublish the individual page records from the online catalog.

**Comment by annabozz** [comment]
Imaging work done, NetX collection sent to P&D

**Comment by edgartdata** [comment]
https://collections.britishart.yale.edu/catalog/tms:54650 is ready with its masonry image, page level titles and only one BlackLight record for the sketchbook.

**Comment by annabozz** [comment]
Update to implement masonry new image function

Masonry: "The Taj Mahal"

1. duplicate file (ba-obj-54650-0033-pub):
- unpublished online
- moved to NetX "pending deletion" folder

2. deleted from TMS
- image in sequence marked as masonry set as CDS 2 (ba-obj-54650-0016-pub)
