### ISSUE TITLE
P&D sketchbook-William Hodges- Select Views from India Vol. 2

### ISSUE THREAD

**Issue by edgartdata** [ycba-cia/blacklight-collections2#348]
@annabozz 

TMS parent record B1978.43.1752V only has images for the cover; In addition there are 31 child records: B1978.43.1752-1783 and each of them have images
Imaging will need to rename/reingest and republish interior/individual images to the parent object ID.  
Note: As an album  with tipped in drawings rather than a sketchbook, only single pages/drawings were photographed as opposed to double page spreads.
New primary selection will be B1978.43.1771- https://collections.britishart.yale.edu/catalog/tms:10628

**Comment by edgartdata** [comment]
Laurel in favor of having the inside images show horizontally so that they are easier to read but leave the covers show vertically.

**Comment by annabozz** [comment]
4/5: Amelia confirmed page order via contact sheet

**Comment by annabozz** [comment]
Masonary image and newly renamed files ready for ingest (when IWT ingest resumes)

**Comment by annabozz** [comment]
DONE:
- Images published online, including masonary image
- TMS media images rank sorted

TO DO: 
- Anna will send NetX Collection to Amelia and David on Monday (Amelia out of office rest of week)

otherwise, records all set https://collections.britishart.yale.edu/catalog/tms:54651

**Comment by annabozz** [comment]
Update!

Anna was delayed on sending NetX collection to Amelia and David for this sketchbook for Image Captions- just sent today.

**Comment by edgartdata** [comment]
Amelia has entered all the captions for the Hodges sketchbook Vol. II- B1978.43.1752V in NetX.

**Comment by edgartdata** [comment]
EDG unpublished all the Blacklight records for the individual sketchbook pages.

**Comment by annabozz** [comment]
Update to implement masonry new image function

Masonry: "A View of the Gaut at Etawa on the Banks of the River Jumna"

1. duplicate file (ba-obj-54651-0035-pub):
- unpublished online
- moved to NetX "pending deletion" folder
- deleted from TMS

2. image in sequence marked as masonry set as CDS 2 (ba-obj-54651-0022-pub)
