### ISSUE TITLE
P&D sketchbook-Charles Hamilton Smith-Views of Polar Regions

### ISSUE THREAD

**Issue by edgartdata** [ycba-cia/blacklight-collections2#349]
@annabozz 

Charles Hamilton Smith- Views of Polar Regions: B1978.43.1820- (1)- (75): 
B1978.43.1820 is the TMS parent record: https://collections.britishart.yale.edu/catalog/tms:18924 and only has images of the cover.
Imaging will need to rename/reingest and republish interior/individual images to the parent object ID.  
Note: As an album  with tipped in drawings rather than a sketchbook, only single pages/drawings were photographed as opposed to double page spreads.
New primary selection will  be https://collections.britishart.yale.edu/catalog/tms:71418

**Comment by edgartdata** [comment]
@annabozz @bobhixon Laurel would like for us to work on Charles Hamilton Smith's sketchbook of Views of Polar Regions next (not the Flaxman as previously thought).

**Comment by annabozz** [comment]
Contact sheet of images submitted, and Amelia in P&D confirmed that order of images is correct

**Comment by annabozz** [comment]
Images, including masonary image, now ingested (as of morning of 3/11), Anna will work in coordination of timing with @edgartdata  to publish images online for overall record

**Comment by edgartdata** [comment]
The 75 individual Blacklight records for the sketchbook pages will disappear from the online catalog tomorrow 3/23.

**Comment by edgartdata** [comment]
@LaurelOP @annabozz 
Smith's sketchbook with Views of Polar Regions is ready for your review and page level titles: https://collections.britishart.yale.edu/catalog/tms:18924
All the individual Blacklight records for the individual sketchbook pages have been unpublished from the online catalog and Anna has processed the masonry image.

**Comment by annabozz** [comment]
@LaurelOP and @edgartdata

Just gave Amelia, David, and Laurel access to the NetX collection so that Image Captions can be added

NetX collection name: **P&D Hamilton-Smith Polar Regions pubs**

**Comment by annabozz** [comment]
Update to implement masonry new image function

Masonry: "The Doreathea Nipped in the Ice off Spitzbergen, North View"

1. duplicate file (ba-obj-18924-0078-pub):
- unpublished online
- moved to NetX "pending deletion" folder
- deleted from TMS

2. image in sequence marked as masonry set as CDS 2 (ba-obj-18924-0036-pub)
