### ISSUE TITLE
TextEntryHTML

### ISSUE THREAD

**Issue by edgartdata** [ycba-cia/blacklight-collections2#355]
Use TextEntryHTML instead of doing special processing in blacklight like <% field2 = field.gsub('\n','</br>').html_safe %> to capture the line returns in Objects Module LIDO text entries (used for Published Catalog Entries, Gallery Labels, and Curatorial Comments).

**Comment by yulgit1** [comment]
switched from TextEntry to TextEntryHTML in coboat:
https://github.com/ycba-cia/coboat-github/commit/34fe40e2160a04393382fbca90f31b112ac19156

Deployed to harvester-test to run tonight, to check tomorrow for difference between harvester-test and harvester-bl

- displayEvents (not exhibitions)
- displayObjects
- lido:inscriptionTranscription

**Comment by edgartdata** [comment]
COBOAT does not handle the HTML so reverted the TextEntryHTML back to TextEntry in harvester-test.

**Comment by edgartdata** [comment]
We will be using --- to indicate line returns going forward. To be tested shortly.

**Comment by yulgit1** [comment]
Answer to the above is that the \n continue to exist in the database field, but the TMS UI removes them even if they are there, and furthermore if you open the UI with the \n removed, upon save it will remove the \n.

The solution going forward is to keep \n mapping in blacklight to be backwards compatible, but use triple dashes "---" to indicate line breaks going forward.

It appears to be working with the triple dashes now in this example record:

https://harvester-bl.britishart.yale.edu/oaicatmuseum/OAIHandler?verb=GetRecord&identifier=oai:tms.ycba.yale.edu:83329&metadataPrefix=lido

https://collections.britishart.yale.edu/catalog/tms:83329
