### ISSUE TITLE
Use CDS to determine Online Access facet

### ISSUE THREAD

**Issue by yulgit1** [ycba-cia/blacklight-collections2#36]
Currently using resource_facet with values of "Resource Available Online" or "Resource Not Available Online". Instead create a facet informed by existance of a thumbnail.

https://deliver.odai.yale.edu/info/repository/YCBA/object/21841/type/2
http://deliver.odai.yale.edu/content/repository/YCBA/object/21841/type/2/format/1

Determine where in the workflow this should occur? perhaps in index.rake? (which transforms solr-vufind to blacklight collections form)?

**Comment by yulgit1** [comment]
Currently:
<xsl:when test="lido:resourceWrap/lido:resourceSet/lido:resourceRepresentation/lido:linkResource">
<xsl:text>Resource available online</xsl:text>
</xsl:when>
<xsl:otherwise>
<xsl:text>Resource not available online</xsl:text>
</xsl:otherwise>

<xsl:when test="marc:datafield[@tag='856']/@ind2!=2">
<xsl:text>Resource available online</xsl:text>
</xsl:when>
<xsl:otherwise>
<xsl:text>Resource not available online</xsl:text>
</xsl:otherwise>

**Comment by yulgit1** [comment]
[302,404]
```
require 'faraday'
h = "http://deliver.odai.yale.edu/content/repository/YCBA/object/21841/type/2/format/1"
url = URI(h)
response = Faraday.head url
if response.status == 302
doc['resource_facet'] = "Resource available online"
else
doc['resource_facet'] = "Resource not available online"
end
```

**Comment by yulgit1** [comment]
Rename facet from "Online Access" to "Image Available"?

**Comment by edgartdata** [comment]
What is this facet filtering on? 
What does 'resource available online' mean? All art collection works have online records.
What might be more helpful is 2 facets:
- one for ‘on view’/’not on view’
- the other one for image/no image

**Comment by mxgold** [comment]
because this issue refers to CDS, it concerns the image/no image facet.
Should a separate issue be created (if not already) for on view/not on view (eg filtered location of physical objects)

**Comment by mxgold** [comment]
Facet name change to "images available"  "images unavailable" ?

**Comment by mxgold** [comment]
<img width="264" alt="screen shot 2019-02-14 at 11 28 17 am" src="https://user-images.githubusercontent.com/36539808/52801411-c8bcaf00-304b-11e9-8609-1a3d1561c761.png">
 of note: I've run several searches with result sets that definitely return some works that don't have images available, but only the "resource available online" facet appears (see screenshot)

**Comment by flapka** [comment]
(Stating the obvious, in case it's useful)

For MARC records, the data is current mapping to "online" if the MARC record has an 856 field. This results in many false hits. Presence of 856 does not equal image available.

**Comment by edgartdata** [comment]
@yulgit1 Nice to see the Image available facet! 

Can we replace true with available, and false with unavailable?

Also, can we set the default view mode to the light box mode (3rd choice)?

Can we also default the number of results on each page to be 100?

Can we discuss if there a useful need for the Fabrique light to dark template feature, particularly in the spaces between the images?

Can we have only the title and the name of the creator show under each thumbnail in a results page?

**Comment by edgartdata** [comment]
@flapka Should we do away with the Online Access facet?

**Comment by edgartdata** [comment]
Melissa, I requested for an "on view/not on view" facet in issue #77 . It's in batch 2.

**Comment by mxgold** [comment]
Thanks and sorry!

Sent from my iPhone

On Feb 14, 2019, at 4:52 PM, Emmanuelle Delmas-Glass <notifications@github.com<mailto:notifications@github.com>> wrote:


Melissa, I requested for an "on view/not on view" facet in issue #77<https://nam05.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fycba-cia%2Fblacklight-collections2%2Fissues%2F77&data=02%7C01%7Cmelissa.fournier%40yale.edu%7Ce4e3c8054d20429a0b5808d692c6ae7b%7Cdd8cbebb21394df8b4114e3e87abeb5c%7C0%7C0%7C636857779375879547&sdata=Igu%2FqOi01wmtQqjs%2Bau5xVjDk0WI22xXfIVDUEECehQ%3D&reserved=0> . It's in batch 2.

**Comment by yulgit1** [comment]
Can we replace true with available, and false with unavailable?
(done, will show up next indexing)

Also, can we set the default view mode to the light box mode (3rd choice)?
(done)

Can we also default the number of results on each page to be 100?
(done)

Can we discuss if there a useful need for the Fabrique light to dark template feature, particularly in the spaces between the images?
(to discuss)

Can we have only the title and the name of the creator show under each thumbnail in a results page?
(done)

**Comment by flapka** [comment]
I think I agree with all of the above.

In the lightbox view, the creator name isn't showing up for library collections. For example: http://10.5.96.187:3000/?f%5Bcollection_ss%5D%5B%5D=Rare+Books+and+Manuscripts&view=masonry

**Comment by yulgit1** [comment]
Can we replace true with available, and false with unavailable?
(done, will show up next indexing)

Also, can we set the default view mode to the light box mode (3rd choice)?
(done)

Can we also default the number of results on each page to be 100?
(done)

Can we discuss if there a useful need for the Fabrique light to dark template feature, particularly in the spaces between the images?
(batch 3 issue)

Can we have only the title and the name of the creator show under each thumbnail in a results page?
(done)

ok to close?

**Comment by flapka** [comment]
@yulgit1 @edgartdata 

With apologies for being difficult, there are two things I'd like to work on / discuss before closing.

1. See my comment above above creator names not appearing for library items.

2. As for displaying only title and creator name with the thumbnails: could we discuss adding date, too? I think this is a core piece of information, especially when a work appears in multiple iterations where only the date changes. Note that many online catalogues of major museums include title, creator, and date in the thumbnail view:
* http://collections.vam.ac.uk/search/?listing_type=&offset=0&limit=15&narrow=&extrasearch=&q=glasgow
* https://www.npg.org.uk/collections/search/person.php?LinkID=mp04571&displayStyle=list
* https://www.tate.org.uk/search?q=glasgow&type=artwork
* https://www.metmuseum.org/art/collection/search#!?q=glasgow

**Comment by edgartdata** [comment]
@EdwardTown1 How do you feel about that?

**Comment by flapka** [comment]
@EdwardTown1 @yulgit1 

Showing the date is probably more important for library collections than art collections because many art items will have images, from which an approximate date can often be surmised. 

I do understand the appeal of having a view of search results that is mostly visual. The current middle button for views ("gallery") seems mostly useless. Could we modify it so that it is like the "masonry" view but with images only (no text)?

**Comment by edgartdata** [comment]
@flapka I agree that the middle button for views ("gallery"). Great idea to tweak it so that it is an "image only" view mode! Could we make it so that the images fill the screen real estate without any text? @EdwardTown1 This option would be a 100% visual view mode/search.

**Comment by yulgit1** [comment]
Addressing several things:

Creator not showing for libraries because the field for museum preferred creator is not implemented for libraries.  I think this can be achieved though by adding this field to the Marc xslt.

We can add date.

I will experiment w/ image only gallery view.

**Comment by flapka** [comment]
Thanks. For library material, a "preferred creator" should be the same as "author_ss" -- unless I've misunderstood the meaning of "preferred creator."

**Comment by yulgit1** [comment]
there is auth_author_ss - 100|110|111
and
there is author_ss - 100|110|111 or if not then 245c

FWIW auth_author_ss is in the xslt but not implemented

@flapka - for light box creator does matter which one?

**Comment by flapka** [comment]
Thanks Eric. Preferred creator should map from auth_author_ss (100|110|111)

**Comment by flapka** [comment]
@edgartdata @EdwardTown1 

Copying @edgartdata 's comment from issue #83 back to the original thread in this issue.
> @flapka @yulgit1 Ed and I have discussed this and it is okay to go ahead to add date after the names of the creators, separated with a coma, on the same line.

The trouble is that names for library material are in the form last name, first name, life dates, e.g, Smith, James, 1724-1788. I worry that adding the date of the work right after a name in this form could cause lots of confusion, e.g. Smith, James, 1724-1788, 1756. 

It'd be less confusing on a 3rd line, or after the title. though obviously we don't want a date to be interpreted as part of the title either.

I'd prefer no date at all to putting a date right after the creator name (separated only by a comma).
