### ISSUE TITLE
On-site Access facet values

### ISSUE THREAD

**Issue by edgartdata** [ycba-cia/blacklight-collections2#366]
Right now they are:

- Accessible by request in the Study Room
- Accessible in the Reference Library
- Accessible by appointment in the Study Room
- On view
- Not on view

Can we streamline this language?

**Comment by flapka** [comment]
I discussed this today with RBM and with Charlotte (for the SR perspective). We think it would be preferable to fold "Accessible by appointment in the Study Room" into the existing "Accessible by request in the Study Room" -- maintaining the latter label. 

The offsite Archives collections do require an email to arrange access, but that becomes evident enough in the object records, and an email is a type of "request."

@rchatalbash What do you think?

**Comment by rchatalbash** [comment]
That sounds fine to me. - Rachel

From: Francis Lapka ***@***.***>
Reply-To: ycba-cia/blacklight-collections2 ***@***.***>
Date: Monday, May 2, 2022 at 3:45 PM
To: ycba-cia/blacklight-collections2 ***@***.***>
Cc: "Chatalbash, Rachel" ***@***.***>, Mention ***@***.***>
Subject: Re: [ycba-cia/blacklight-collections2] On-site Access facet values (Issue #366)


I discussed this today with RBM and with Charlotte (for the SR perspective). We think it would be preferable to fold "Accessible by appointment in the Study Room" into the existing "Accessible by request in the Study Room" -- maintaining the latter label.

The offsite Archives collections do require an email to arrange access, but that becomes evident enough in the object records, and an email is a type of "request."

@rchatalbash<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Frchatalbash&data=05%7C01%7Crachel.chatalbash%40yale.edu%7Cedeb48970c0845e9ad4f08da2c744232%7Cdd8cbebb21394df8b4114e3e87abeb5c%7C0%7C0%7C637871175089101327%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=6h5ASx6WRuSOVKOe3ngeFrhJgIqfOQuP%2Fu%2FuiYJ11Cw%3D&reserved=0> What do you think?

**Comment by edgartdata** [comment]
@flapka @rchatalbash thank you for following up on this issue.

**Comment by edgartdata** [comment]
On view in the galleries
Request in the Study Room
Available in the Reference Library
Not on view

**Comment by edgartdata** [comment]
On view in the galleries
View by request in the Study Room
Available in the Reference Library 
Not on view

**Comment by yulgit1** [comment]
new mappings to run overnight:
https://git.yale.edu/ermadmix/camel_collections2/commit/001a8717b378f1c92cf04776ed483e6e59a92b27
https://git.yale.edu/ermadmix/camel_collections2/commit/f6f4f896ec93ce177dcaee167dc56a53268d63ba

```
case "Paintings and Sculpture":
                    if (onview_str.equals("On view")) {
                        doc.addField("detailed_onview_ss", "On view in the galleries");
                    } else {
                        doc.addField("detailed_onview_ss", "Not on view");
                    }
                    break;
                case "Prints and Drawings":
                    if (onview_str.equals("On view")) {
                        doc.addField("detailed_onview_ss", "On view in the galleries");
                    } else {
                        doc.addField("detailed_onview_ss", "View by request in the Study Room");
                    }
                    break;
                case "Frames":
                    if (onview_str.equals("On view")) {
                        doc.addField("detailed_onview_ss", "On view in the galleries");
                    } else {
                        doc.addField("detailed_onview_ss", "Not on view");
                    }
                    break;
                case "Rare Books and Manuscripts":
                    doc.addField("detailed_onview_ss", "View by request in the Study Room");
                    break;
                case "Reference Library":
                    doc.addField("detailed_onview_ss", "Available in the Reference Library");
                    break;
                case "Institutional Archives":
                    doc.addField("detailed_onview_ss", "View by request in the Study Room");
                    break;
                default:
```

**Comment by yulgit1** [comment]
@edgartdata Number On-site Access doesn't seem right for frames.  I would expect many more to be on view.  A TMS data issue perhaps? Screenshot:

![Screen Shot 2022-05-20 at 11 17 03 AM](https://user-images.githubusercontent.com/2125400/169559446-a51d8c33-03e9-4ced-a594-90e43e8373ee.png)

**Comment by edgartdata** [comment]
@yulgit1 It is because TMS frame records do not have location. I am not sure why that one frame does. Its location is correct but in general no one updates the locations of frames.
For now can we please not include frames in the on-site access facet?
Going forward, could we think of a process by which XML frame records inherit the location of the paintings they share the accession number with?

**Comment by yulgit1** [comment]
Change to not include frames in on-sote access facet:
https://git.yale.edu/ermadmix/camel_collections2/commit/50219c92c9e16635c22c8f94432233eb342269c6

Considered the using the tandem Bnum to get the frame value, but decided against this.  It would require a connection the TMS DB, another point of failure, and slow down the ingest process.

**Comment by flapka** [comment]
Thanks @yulgit1 . The old value "Accessible request in the Study Room" did indeed include three RBM items that have been suppressed in Voyager. I've now used the delete mechanism to remove the three from Blacklight.

**Comment by edgartdata** [comment]
@yulgit1 The 28 P&D are all individual Blacklight records for individual TMS records for the pages of Hodges' third volume of Views of India. The overall/entire sketchbook Blacklight and TMS record is B1978.43.1784V https://collections.britishart.yale.edu/catalog/tms:54652 
I unpublished the Blacklight page records too soon. Sorry. They will disappear out of the facet once @annabozz and Amelia do their magic.

**Comment by edgartdata** [comment]
@KraigBinkowski Do you know why these 28 Reference Library records https://collections.britishart.yale.edu/?f%5Bdetailed_onview_ss%5D%5B%5D=Accessible+in+the+Reference+Library get the old "accessible in the Reference Library" status?

**Comment by flapka** [comment]
@rchatalbash @mollyED @LaurelOP @KraigBinkowski 

Marginally related to the above, but with new strands (and in the context of object pages):

1. Access language in P&D object pages already matches the value used in the access facet, i.e. "View by request in the Study Room". The RBM and IA language still uses the old facet values (examples: [RBM](https://collections.britishart.yale.edu/catalog/orbis:1920979), [IA](https://collections.britishart.yale.edu/catalog/orbis:14421379)). Could we update the language to match what we have for P&D?
2. The Study Room and Reference library are now open to non-Yale ID holders, which contradicts information in our Blacklight banner. Could we update the langue to something like: "The Center is free and open to the public. The Reference Library and Study Room are open by appointment only."
3. We need a similar change in our object pages for Study Room collections (P&D, RBM, IA). Could we update the "Note" to say: "Note: The Study Room is open by appointment. Please visit the Study Room page on our website for more details."
4. For Ref objects, perhaps we should update the "Note" to something like: "Note: The Reference Library is open by appointment. Please visit the Reference Library page on our website for more details. For scans from the reference collection please email ycba.reference@yale.edu."?

**Comment by edgartdata** [comment]
For 1. you mean the on-site access status language that is in the individual BL RBM and IA records.
2. Thanks for catching the discrepancy between the BL and YCBA banners @flapka 
3. Good point about keeping the Notes which is under the Request link in synch with the new language and the banner. I don't see such a note for P&D items?
4. @KraigBinkowski Is the language Francis suggests okay with you?

**Comment by KraigBinkowski** [comment]
Yes, the suggested note language looks good for REF

**Comment by flapka** [comment]
@edgartdata 
1. Yes. The language that appears near the "request" (RBM) / "email" (archives) links. 
3. I think the note is there for most P&D objects ([example](https://collections.britishart.yale.edu/catalog/tms:4110)). The exception I think is with the Hodges ([example](https://collections.britishart.yale.edu/catalog/tms:10973)).

**Comment by edgartdata** [comment]
@flapka for 2.: right. The page from Hodges' Vol.3 of Views of India you note above https://collections.britishart.yale.edu/catalog/tms:10973 does not have a _Note_ under _View by request in Study Room_ because I messed up and stopped its data to go from TMS to LIDO (I will be talking with Laurel if we can bump this sketchbook up in our list of sketchbooks to work on). But the overall Hodges' Vol.3 of Views of India aka B1978.43.1784V aka https://collections.britishart.yale.edu/catalog/tms:54652 does have the _Note_.

**Comment by yulgit1** [comment]
resolved: https://github.com/ycba-cia/blacklight-collections2/commit/a53cdb8e52428d7184577e32b9772f99e9103af4

**Comment by edgartdata** [comment]
@LaurelOP I am not sure why https://collections-test.britishart.yale.edu/catalog/tms:20200 still has 
Accessible by request in the Study Room ?

**Comment by LaurelOP** [comment]
@edgartdata Nor I! It appears to the the only one from that group with the issue. Is there a box that needs to be ticked or something?

**Comment by yulgit1** [comment]
This tms:20200, does not have a LIDO record anymore, so the on-site access is not getting updated.  

https://harvester-bl.britishart.yale.edu/oaicatmuseum/OAIHandler?verb=GetRecord&identifier=oai:tms.ycba.yale.edu:20200&metadataPrefix=lido'

The alternatives are either to delete it from solr using the http://10.5.96.187:3001/home/index tool, or set TMS so there is a LIDO for this.

**Comment by edgartdata** [comment]
@yulgit1 For some reason tms:20200 was not checked for public access. I changed that in TMS and its LIDO record should get picked up tomorrow.

**Comment by edgartdata** [comment]
Unpublished the Blacklight records for the individual pages for Hodges Volume III. This should resolve this issue. Will check tomorrow.
