### ISSUE TITLE
P&D Clarkson Stanfield sketchbook B1988.4

### ISSUE THREAD

**Issue by edgartdata** [ycba-cia/blacklight-collections2#368]
@annabozz Clarkson Stanfield sketchbook B1988.4 https://collections.britishart.yale.edu/catalog/tms:2810 has 29 pages. Looks like all of them have been digitized. 

@LaurelOP What masonry image would you like?

**Comment by LaurelOP** [comment]
@edgartdata Image 5, the watercolor of the boats, please.

**Comment by annabozz** [comment]
masonry image set, NetX collection sent to P and D

Imaging work done!

**Comment by edgartdata** [comment]
Titles done.
