### ISSUE TITLE
P&D William Blake Songs of Innocence and Experience B1992.8.13V Bentley copy L

### ISSUE THREAD

**Issue by edgartdata** [ycba-cia/blacklight-collections2#369]
@annabozz Blake Songs of Innocence and Experience B1992.8.13V Bentley copy L https://collections.britishart.yale.edu/catalog/tms:57619 has 54 pages, all of them digitized.

Crop out the color bars but do not photoshop the foam out.

@LaurelOP What masonry image would you like?

**Comment by LaurelOP** [comment]
@edgartdata   Let's do the combined title page: https://collections.britishart.yale.edu/catalog/tms:3739

**Comment by edgartdata** [comment]
To work on before the Bodichon and Hodges vol.3

**Comment by annabozz** [comment]
Started this today- more next week!

**Comment by edgartdata** [comment]
Image order verified by P&D. 
P&D to work on titles next week.

**Comment by annabozz** [comment]
Done: 
- images Ingested and moved to proper permission folder in NetX (Bob)
- created collection of pubs in NetX 

To Do:
- clean up images in TMS
- ingest primary image
THEN
- send collection to P&D for image captions

**Comment by edgartdata** [comment]
@edgartdata to check that B1992.8.13(9) https://collections.britishart.yale.edu/catalog/tms:3781 is not online anymore as an individual Blacklight record on 7/21.

**Comment by annabozz** [comment]
Update to implement masonry new image function

Masonry: "Plate 2, Combined Title Page"

1. duplicate file (ba-obj-57619-0090-pub): 
- unpublished online
- moved to NetX "pending deletion" folder
- deleted from TMS

2. image in sequence marked as masonry set as CDS 2 (ba-obj-57619-0031-pub)
