### ISSUE TITLE
P&D Bodichon Sketchbook B1991.23.2

### ISSUE THREAD

**Issue by edgartdata** [ycba-cia/blacklight-collections2#370]
@annabozz Bodichon Sketchbook B1991.23.2 https://collections.britishart.yale.edu/catalog/tms:46116 has 21 pages (cataloguing still working on it), all of them digitized.

@LaurelOP What masonry image would you like?

**Comment by LaurelOP** [comment]
@edgartdata B1991.23.2 (19), please. ( A double-page spread with a view to yellowed fields and distant mountains)

**Comment by annabozz** [comment]
Last week - Amelia confirmed order of images
This week - Anna finished imaging work (which was minimal), marked primary, and passed to Amelia and David for caption work (Imaging part finished)

**Comment by edgartdata** [comment]
Emmanuelle deleted the individual Blacklight records for the individual pages.

**Comment by annabozz** [comment]
Update to implement masonry new image function

Masonry: "Landscape of Hills and Valleys with an Aqueduct Bridge"

1. duplicate file (ba-obj-46116-0025-pub):
- unpublished online
- moved to NetX "pending deletion" folder
- deleted from TMS

2. image in sequence marked as masonry set as CDS 2 (ba-obj-46116-0021-pub)
