### ISSUE TITLE
P&D Hodges Views of India Vol.3

### ISSUE THREAD

**Issue by edgartdata** [ycba-cia/blacklight-collections2#371]
@annabozz Hodges Views of India vol.3 B1978.43.1784V https://collections.britishart.yale.edu/catalog/tms:54652 has 28 pages B1978.43.1784-B1978.43.1811 all digitized.

@LaurelOP What masonry image would you like?

**Comment by LaurelOP** [comment]
@edgartdata https://collections.britishart.yale.edu/catalog/tms:10892 please.

**Comment by yulgit1** [comment]
To be clear, the reason why the Hodges doesn't have the full "Access" field with link and note is that that is dependent on the new On-site Access language.  As the LIDO is suppressed for Hodges the new language isn't getting updated.

**Comment by annabozz** [comment]
@LaurelOP @edgartdata 

Depending on preference, I will start working on either Hodges vol. 3 or Blake tomorrow (Friday)

**Comment by LaurelOP** [comment]
@annabozz @edgartdata 

Sorry for the delayed reply! I've conferred with David, and it's fine for you to begin on the Hodges tomorrow. Thank you!

**Comment by annabozz** [comment]
Today's update: 

- Rank and permissions adjusted so overall collection online now
https://collections.britishart.yale.edu/catalog/tms:54652

- NetX collection just sent to P&D for Image Captions


**Revisiting earlier comment: Do we want endpapers to be imaged since one missing?**

**Comment by edgartdata** [comment]
Volumes I and II https://collections.britishart.yale.edu/catalog/tms:54650 https://collections.britishart.yale.edu/catalog/tms:54651 do not have endpapers so let's keep them consistent with Volume III

**Comment by annabozz** [comment]
> Volumes I and II https://collections.britishart.yale.edu/catalog/tms:54650 https://collections.britishart.yale.edu/catalog/tms:54651 do not have endpapers so let's keep them consistent with Volume III

@LaurelOP @edgartdata  Hmmm.. maybe I should un-publish the one endpaper from this volume then? See second to last image at end of record

**Comment by edgartdata** [comment]
I'd say yes, let's not show any endpapers until we can publish them all for all 3 sketchbooks. @LaurelOP does that sound okay?
