### ISSUE TITLE
Search results from creator link in an object record

### ISSUE THREAD

**Issue by flapka** [ycba-cia/blacklight-collections2#374]
When I click the hyperlink on a creator name while viewing an object record, the results set that follows includes wonky values in the creator facet. See for example this URL/screenshot: 

https://collections.britishart.yale.edu/?f%5Bauthor_ss%5D%5B%5D=Luigi+Balugani%2C+1737%E2%80%931770%2C+Italian

![image](https://user-images.githubusercontent.com/7634899/166063632-ceda851b-0755-4175-9ac0-324576b99f04.png)

The values in the creator facet seem to be for the entire catalog, rather than for the records resulting from clicking on the name in the object record.

No similar problem for general searches, e.g. on Luigi Balugani:
https://collections.britishart.yale.edu/?utf8=%E2%9C%93&search_field=Creator&q=luigi+balugani

Is this a simple-to-fix bug?

**Comment by yulgit1** [comment]
That's craziness.  Will have to investigate, sounds like an internal error.  Heroku, the cloud provider's deployment pipeline is currently experiencing some big outage so couldn't fix it even if I had a solution.  Will look next week.

**Comment by yulgit1** [comment]
OK, not so crazy, blacklight has parameters to exclude filters from facets for multiselect.  For some reason (maybe early testing that I don't remember?) these were on, but can be disabled.

`config.add_facet_field 'author_ss', label: 'Creator', :tag => 'author_ss', :ex => 'author_ss', :limit => 20`
to
`config.add_facet_field 'author_ss', label: 'Creator', :limit => 20`

Again waiting on the GitHub/heroku oauth breach to resolve, so as to be able to resume pushing changes.
https://github.blog/2022-04-15-security-alert-stolen-oauth-user-tokens/

But, this configuration has been this way from at least 2019, surprising it was first noticed now.

**Comment by flapka** [comment]
Thanks @yulgit1 . Perhaps it went unnoticed because clicking on creator names in an object record in an uncommon action?

**Comment by edgartdata** [comment]
I just searched for "balugani" then selected one P&D record, and once in a record I clicked on his full name. The names appearing then in the Creator facet make sense. I supposed this reflects Eric's change to exclude multiselect from facet?

![image](https://user-images.githubusercontent.com/4093644/168165448-48d53c74-6dd4-4f57-9292-38fb9e66cd6a.png)

**Comment by yulgit1** [comment]
@edgartdata Beat me to the punch.  Yes I just deployed the fix to this via a heroku/github/oauth issue workaround.  So I think this issue can close.
