### ISSUE TITLE
Querying for range of accession numbers

### ISSUE THREAD

**Issue by edgartdata** [ycba-cia/blacklight-collections2#376]
Might be possible to leverage the search type in the dropdown to the right of the search field, by creating a new search type in blacklight using the standard rather than dismax parser, and configuring that parser in solr itself.  But this is a heavy lift and might be more than time permits.

**Comment by yulgit1** [comment]
Added "Fielded" Search Type (see screenshot below).  This enables a solr parser that has the capability to do searches based on fields and ranges such as:

callnumber_ss:["B2017.41.1" TO "B2017.41.99"]


![Screen Shot 2022-05-23 at 1 47 29 PM](https://user-images.githubusercontent.com/2125400/169877725-7062edc5-f186-44cf-95a5-1e43861d706f.png)

https://github.com/ycba-cia/blacklight-collections2/commit/2e506900493e937114cc65f76b0d818b1672a7cf

**Comment by edgartdata** [comment]
@yulgit1 I have tried [B1978.43.1786 TO B1978.43.1800] and B1978.43.1786 TO B1978.43.1800 but I am obviously not formatting the query correctly.
