### ISSUE TITLE
plus sign (+) in call number parameter passed to Aeon

### ISSUE THREAD

**Issue by flapka** [ycba-cia/blacklight-collections2#377]
I notice today a small glitch in how call numbers are passed from BL to Aeon:

Some RBM call numbers include the plus sign (+) to indicate that the volume is in the range of Oversize shelving. [This Palladio](https://collections.britishart.yale.edu/catalog/orbis:3456690) is an example. Requesting this item in the Center's catalog sends a call number parameter that varies slightly from the same request from Orbis:
* Blacklight: &CallNumber=NA2515%20.V587%201660+%20Oversize
* Orbis: &CallNumber=NA2515%20.V587%201660%2B%20Oversize

The Orbis request translates the + to %2B. That makes a difference in the Aeon web form, where our Blacklight '+' disappears in the  call number field, whereas the Orbis '%2B' populates the call number with a '+'. Could we mimic what Orbis does so that the plus sign is communicated to Aeon? The absence of the plus in the Aeon request can send staff to the wrong place in the stacks to look for the book.

**Comment by yulgit1** [comment]
Redeployed with fix, should be all set.

https://github.com/ycba-cia/blacklight-collections2/commit/96e7f55060b10b5cebbfd9e8760844ce950190a7

**Comment by flapka** [comment]
Wonderful. Thanks for the swift fix!
