### ISSUE TITLE
standardized rights logos

### ISSUE THREAD

**Issue by edgartdata** [ycba-cia/blacklight-collections2#383]
@yulgit1 For the logos with text (as we currently have them), would it be possible to make them smaller, on the model of the one in https://collections-test.britishart.yale.edu/catalog/tms:1505 for Copyright undetermined? 

I will also be talking with Julie Fry to get her design input, knowing that Blacklight does not have much flexibility/options when it comes to graphic design unfortunately.

**Comment by yulgit1** [comment]
@edgartdata Which do you prefer of the screenshots below:

165px (default)
<img width="756" alt="Screen Shot 2022-06-29 at 11 42 50 AM" src="https://user-images.githubusercontent.com/2125400/176478857-dee9518b-1b95-49a8-bc11-d49ceda6ebbe.png">


150px
<img width="755" alt="Screen Shot 2022-06-29 at 11 43 20 AM" src="https://user-images.githubusercontent.com/2125400/176478955-2afdb485-6b70-4748-898d-c067205040e3.png">


135px
<img width="751" alt="Screen Shot 2022-06-29 at 11 43 48 AM" src="https://user-images.githubusercontent.com/2125400/176479080-6499c58b-d7e1-4a67-a4fb-b58fd917f6f5.png">

even smaller?

note: when screen width is smaller (like phone view) the image resizes smaller to fit width (the same smaller no matter above size):
<img width="354" alt="Screen Shot 2022-06-29 at 11 47 50 AM" src="https://user-images.githubusercontent.com/2125400/176480151-e453f784-9027-4288-bd17-a727cf600b4f.png">

**Comment by edgartdata** [comment]
@yulgit1 I like the 135px because it is flush with the Request photo button.
@mxgold What do you think for now?
