### ISSUE TITLE
Bardwell sketchbook B1977.14.9618V

### ISSUE THREAD

**Issue by edgartdata** [ycba-cia/blacklight-collections2#385]

**Comment by annabozz** [comment]
This should go relatively quickly since the overall record double page spreads are already in NetX

**Comment by annabozz** [comment]
Update:

- emailed Laurel today to ask which view should be primary image and if extra object should be shown
- TMS media records already set, NetX records already set (images already existed in overall record)
- made PDF contact sheet, will send to P&D on Monday

TO DO:
- ingest primary
- expose records

**Comment by annabozz** [comment]
Update: 

Order of pages confirmed by P&D, I exposed the pages cover to cover in overall record: 
(didn't show extra item for now until confirmed whether to expose online)

I will ingest and expose online the primary when selected, then will send to P&D for captions

**Comment by annabozz** [comment]
Primary confirmed and Laurel prefers not to include the extra slip of paper.

Imaging work now done on this object:
https://collections.britishart.yale.edu/catalog/tms:58388

Email sent to Amelia and David re: ready for image captions

**Comment by edgartdata** [comment]
I have unpublished the individual page records like https://collections.britishart.yale.edu/catalog/tms:58393. I will check that they are not in the online collections catalog tomorrow.

**Comment by edgartdata** [comment]
Done. Move the collective title as repository title. Change medium field. Attend to subject terms.
Next Bodichon.
P&D will come up with next list of sketchbooks.

**Comment by edgartdata** [comment]
P&D will check what title the Lewis Walpole Library recently exhibited our sketchbook with, and enter a new title in TMS. This TMS record will no longer need a Collective Title.

**Comment by annabozz** [comment]
Update to implement masonry new image function

- duplicate file (ba-obj-58388-0058-pub) unpublished and put in NetX "pending deletion" folder
- masonry image set as CDS 2 (ba-obj-58388-0036-pub)
