### ISSUE TITLE
Addition of on-site access status to the masonry view

### ISSUE THREAD

**Issue by edgartdata** [ycba-cia/blacklight-collections2#393]
<img width="941" alt="Masonry view with on-site access status" src="https://user-images.githubusercontent.com/4093644/182689421-5e4b8ed4-2173-451c-8f7a-5bc2ebf3b97b.png">

**Comment by edgartdata** [comment]
Do we want the on-site status for all items from all collections or specific items/collections?

**Comment by edgartdata** [comment]
Final decision:

- Print "On View" or "Not on View" for P&S items only.
- Do not print any on-site locations for P&S, RBM and Reference Library items.

**Comment by edgartdata** [comment]
@LaurelOP Can you please confirm for the record here that you are okay with the plan above, i.e. not adding any on-site access statuses to P&D items in the masonry view? Thanks.

**Comment by LaurelOP** [comment]
I confirm. Let's not add on-site access statuses to P&D items. Many thanks.

**Comment by yulgit1** [comment]
resolved:
https://github.com/ycba-cia/blacklight-collections2/commit/c7f3f8f9a2588561dad464aec687e13c848720d6
