### ISSUE TITLE
Winstanley sketchbook B1977.14.4081

### ISSUE THREAD

**Issue by edgartdata** [ycba-cia/blacklight-collections2#402]
Hamlet Winstanley, Sketchbook contains 81 drawings and 2 engraved self-portraits (B1977.14.4081) https://collections.britishart.yale.edu/catalog/tms:14933
@LaurelOP What is the hero image for the masonry view?

**Comment by annabozz** [comment]
Individual pages already photographed/ingested into record cover to cover with appropriately file names for this sketchbook.

B1977.14.4081 (overall record)
- edited CDS levels to make sure all records published online
- set CDS Primary = 2 for masonry image: ba-obj-14933-0034-pub
- checked TMS records

**Comment by annabozz** [comment]
- sent NetX collection to Amelia and David for Image Caption step

**Comment by edgartdata** [comment]
I deleted the BlackLight records for the individual pages of the sketchbook. The individual pages like https://collections.britishart.yale.edu/catalog/tms:70703 should not be online anymore on 10/13.
