### ISSUE TITLE
Maria Leycester, Scotland and Cheshire Sketchbook, B1992.9.3

### ISSUE THREAD

**Issue by edgartdata** [ycba-cia/blacklight-collections2#405]
Maria Leycester, Scotland and Cheshire Sketchbook, B1992.9.3 https://collections.britishart.yale.edu/catalog/tms:3987
Has 48 page records in TMS but I am not sure that there aren't more pages in the sketchbook.

@LaurelOP What would be the masonry view image for this sketchbook?

**Comment by LaurelOP** [comment]
Let's use B1992.9.3(19), the View of Loch Ard, for the masonry view. https://collections.britishart.yale.edu/catalog/tms:74075

**Comment by annabozz** [comment]
Individual pages already photographed/ingested into record cover to cover with appropriately file names for this sketchbook.

 B1992.9.3 (overall record)

- edited CDS levels to make sure all records published online
- set CDS Primary = 2 for masonry image: ba-obj-3987-0021-pub
- checked TMS records

TO DO: 
- send NetX collection to Amelia and David for Image Caption step

**Comment by annabozz** [comment]
NetX collection sent to Amelia and David

**Comment by annabozz** [comment]
@edgartdata @yulgit1 

While working on this project, Amelia discovered that for the individual records, there's no media linked to TMS (B1992.9.3(1) through (12)). The images do appear in NetX. I looked back in my emails and something had happened possibly back in 2017 that caused this inconsistency-a one-off problematic ingest. 

Even though this won't affect the overall record, would I be able to have a refresher on linking images into the Media TMS? My questions are:
1. what size should I format them too
2. do I drop them in the "screen" or "thumbnails" folder
3. I understand the folder hierarchy of obj then the first three numbers of the file name

**Comment by yulgit1** [comment]
In the workflow the main image (screen) is a jpeg derivative of the tiff default size.  The thumbnail is 192x192.  You'd drop them in the corresponding "screen" and "thumbnail" in S@Y, using that filename hierarchy path like obj/003/987/ba-obj-3987-0001-pub.jpg.  Is that what you're asking?

**Comment by annabozz** [comment]
Thanks Eric- what is the preferred size for the jpeg derivative?

**Comment by yulgit1** [comment]
Spot checked a few such as:

ycbamedia-887111-bac\TMSmedia\Images\Screen\obj\000\034\ba-obj-34-0001-pub.jpg

They seem to fall in the range of 1500 or 2000px long side.

**Comment by yulgit1** [comment]
I don't know about the automatic thumbnail function.  But if thumbnails are going into like:

ycbamedia-887111-bac\TMSmedia\Thumbnail\Screen\obj\000\034\ba-obj-34-0001-pub.jpg

Should be good.

**Comment by annabozz** [comment]
Thanks!

I linked all the missing screen and thumbnail media into TMS for the individual records

Imaging work is completed on this object, and, Amelia added Image Captions

**Comment by edgartdata** [comment]
I deleted the BlackLight page records.
