### ISSUE TITLE
remove boolean qualifiers from author_ss so facets won't have the boolean qualifier

### ISSUE THREAD

**Issue by yulgit1** [ycba-cia/blacklight-collections2#406]
For this record for the William III sculpture https://collections.britishart.yale.edu/catalog/tms:1453 John Cheere’s name is prefaced with “or” which means that clicking on “or John Cheere” only returns this one record, and not any other records for other objects that are by John Cheere, like this one https://collections.britishart.yale.edu/catalog/tms:66161
 
Of course this mechanism was put in place for and works great for objects “after so and so”, like this [print after Turner](https://collections.britishart.yale.edu/catalog/tms:1453) because we would not want to confuse objects made directly by Turner with objects made by other artists looking at Turner. But since “or” is not an attribution qualifier the way “after” is, would it be possible to not link the “or” so as to provide a search that reflects what we have in the collection? I imagine, if possible, we would also want to do that for “and” and if there are other prefixes like that.

**Comment by yulgit1** [comment]
Resolved:
https://git.yale.edu/ermadmix/camel_collections2/commit/c530a697692b6ce2d699773889e7c4a74e24377c

To be indexed tonight.

Tested with:
29444,1453,7874,107

**Comment by yulgit1** [comment]
EDG: "What we want to do is keep all the prefixes you list below in the BL (and LUX) records but instead of having the whole string “or John Cheere” as generating a new query when clicked on, we just want “John Cheere” to generate the query when clicking on his name in that record, while still keeping “or” in front of it in the record.
 
[For now, let’s reinstate these prefixes as soon as possible in the catalog please and next week when you feel better we can talk further about the query mechanism if that’s helpful.](webextlink://For now, let’s reinstate these prefixes as soon as possible in the catalog please and next week when you feel better we can talk further about the query mechanism if that’s helpful.) For example with other attribution qualifiers like “after John Cheere”, the whole string starting with “after” would need to generate a new query returning works “after John Cheere”. I hope that makes sense."

**Comment by yulgit1** [comment]
reinstated, should revert tomorrow

**Comment by yulgit1** [comment]
I've created a new field author_removed_ss, with the and / or removed.  Indexing will run overnight.

The new field will be used for facets.  And the tombstone creator field will display the full original author_ss, but link using this new author_removed_ss.

Tomorrow if indexing looks ok, will add the logic to blacklight for display.

**Comment by edgartdata** [comment]
@yulgit1 Yes, "or/and" are reinstated this morning. Thanks.

How can I tell if indexing is ok?

**Comment by yulgit1** [comment]
This indexing is OK. There is now a author_removed_ss you can see in the json.

I've have just modified blacklight for the new indexing.  Try clicking the links, let me know if this is ok, and I'll promote to prod:

https://collections-test.britishart.yale.edu/catalog/tms:29444
https://collections-test.britishart.yale.edu/catalog/tms:1453
https://collections-test.britishart.yale.edu/catalog/tms:7874

I was hoping to be able to keep the boolean qualifier parts out of the hyperlink but couldn't find a good way to that.

**Comment by edgartdata** [comment]
@yulgit1 Yes, indexing is working well now.
For example, in the record https://collections.britishart.yale.edu/catalog/tms:21987 clicking on "**and** James McArdell, ca. 1729–1765, Irish" in that record launches a query that returns all 83 objects by James McArdell: https://collections.britishart.yale.edu/?f[author_removed_ss][]=James%20McArdell,%20ca.%201729%E2%80%931765,%20Irish

I am not worried about the boolean operators (and; or) still being underlined with the name of the artists.
