### ISSUE TITLE
Add additional caption for specific page to Download/Print

### ISSUE THREAD

**Issue by edgartdata** [ycba-cia/blacklight-collections2#408]
@yulgit1 In addition to the overall title for the whole sketchbook, can we add the caption for the chosen page when downloading or printing a specific page?

In the example below, this page in Hodges Vol. 2 of Views of India https://ycba-collections-dev.herokuapp.com/catalog/tms:54651 is called "A Mosque at Ghazipur", which we would want to see as the second title in https://ycba-collections-dev.herokuapp.com/print/tms:54651/1/2
![Printed caption](https://user-images.githubusercontent.com/4093644/193303397-52bfe8d0-f838-4db9-860f-abc3d028eec7.png)

Similarly, the download caption should also have "A Mosque at Ghazipur" after the title for the whole sketchbook.
![image](https://user-images.githubusercontent.com/4093644/193304453-08fd4e92-47a9-4237-90b3-cc9e46e2fd8b.png)

**Comment by yulgit1** [comment]
Caption added to copyable caption and print page:

88b6c0b15b2373d268b688802c5954cc75777031
5534ec832ebaf5a239eedf9cb80e9ae59f254fbe
6ff589beeb167a26724a5f1ecb8ead2fbb99bd80
2c2c520272f19173ed10f2fb544aeb74007a7fc9
