### ISSUE TITLE
publish bib altnums for altnumdescription "Web Resource" as well as "LC Call Number"

### ISSUE THREAD

**Issue by yulgit1** [ycba-cia/blacklight-collections2#409]
EDG: "At some point we also added that the Alt Num Description must be “LC Call Number”, but I think this is misleading and instead some TMS citations use "Web resource"...Right now we are at the very beginning of this transition mode between replacing “LC Call Number” with “Web resource” for true http resources.”

**Comment by yulgit1** [comment]
resolved in coboat test:
https://github.com/ycba-cia/coboat-github/commit/d0123bb1bfd34854182cc21eb9a069384ae5e834

test tomorrow:

https://interactive.britishart.yale.edu/slavery-and-portraiture/327/commentary-by-ken-gonzales-day

should be in:
https://harvester-test.britishart.yale.edu/oaicatmuseum/OAIHandler?verb=GetRecord&identifier=oai:tms.ycba.yale.edu:54430&metadataPrefix=lido

if so promote to prod.

**Comment by yulgit1** [comment]
test ok, promoted to prod:
https://github.com/ycba-cia/coboat-github/commit/b548c5f2a3cfc62ec7a0726af3827d53817145a0

on monday:

https://interactive.britishart.yale.edu/slavery-and-portraiture/327/commentary-by-ken-gonzales-day

should be in:
https://harvester-bl.britishart.yale.edu/oaicatmuseum/OAIHandler?verb=GetRecord&identifier=oai:tms.ycba.yale.edu:54430&metadataPrefix=lido

**Comment by edgartdata** [comment]
![image](https://user-images.githubusercontent.com/4093644/197530370-d09ca46b-6987-4c23-8023-cd0862316973.png)

This is how it is entered in TMS:
![image](https://user-images.githubusercontent.com/4093644/197531016-6d1e1e16-6f2f-4621-b1c1-8584033a1fcc.png)

@yulgit1 Would it be okay if we were to add the date the link was last accessed after the citation as @KraigBinkowski and I have been thinking about? So for example it would read like this: Ken Gonzales-Day, Commentary on a Bust of a Man by the Studio of Francis Harwood, , Yale Center for British Art, Accessed on 11/24/15, 18.56 minutes, http://interactive.britishart.yale.edu/slavery-and-portraiture/327/commentary-by-ken-gonzales-day **(accessed on 10/24/2022)** [Website]

Also, can you please add a space between the last word of the citation and [Website]?

**Comment by edgartdata** [comment]
Oh good catch Kraig. What field is it currently entered in TMS? My sense is that we should use the field that's already used and I can work with David and Eric to add that new date element to the bib concatenation.

**Comment by KraigBinkowski** [comment]
We have been using the "Date" field on the front page of the record for the "Accessed on..." note.

**Comment by edgartdata** [comment]
Great so let's use this format below with the Begin and End Dates being the year:
![image](https://user-images.githubusercontent.com/4093644/197548957-bc089c6b-0310-4d57-8bab-eddf575ea4d6.png)

**Comment by edgartdata** [comment]
@yulgit1 Can you add the Date label after the http link?

**Comment by yulgit1** [comment]
@KraigBinkowski @edgartdata 

Other than adding the space before "[Website]" is this good as is?

Screenshot TMS:
<img width="308" alt="Screen Shot 2022-10-26 at 12 59 12 PM" src="https://user-images.githubusercontent.com/2125400/198088795-9c34c26f-d726-4fa9-ada2-9d09d5abf745.png">

Screenshot BL:
<img width="1081" alt="Screen Shot 2022-10-26 at 12 59 59 PM" src="https://user-images.githubusercontent.com/2125400/198088936-4038ca83-bbd9-45e3-87a4-67027b73180e.png">

From:
https://collections.britishart.yale.edu/catalog/tms:54430

**Comment by KraigBinkowski** [comment]
I think that looks good.

**Comment by edgartdata** [comment]
@yulgit1 Where is this field in TMS?
![image](https://user-images.githubusercontent.com/4093644/198330834-c70d3d11-e6f0-4193-a14a-fa129064cd21.png)

**Comment by edgartdata** [comment]
@yulgit1 whenever you have a minute to add a space before [website]. Thanks!

**Comment by yulgit1** [comment]
Space added before [Website] on Bibliography page.

https://github.com/ycba-cia/blacklight-collections2/commit/3dfd6a604dec006ec7ed866ea06aaed2f208e09b
