### ISSUE TITLE
Creator facet

### ISSUE THREAD

**Issue by yulgit1** [ycba-cia/blacklight-collections2#41]
sort by alphabetical so unknown doesn't list at top,

possibly use an indexing of <lido:nameActorSet> with the lido:pref="preferred" attribute rather than existing author_ss

**Comment by yulgit1** [comment]
**sort by alphabetical so unknown doesn't list at top,**

use :sort => 'index'

however this is worse as low hit count, special characters go up to top,ex :

"BB," 1905-	1
"Old Calabar,", pseud.	1
"Yerenrag" (J. F. Garneray), 1755–1837	1
(?) Charles Ansell, ca.1752–active 1790, British	5
(?) George Moutard Woodward, ca. 1760–1809, British	1
(?) George Townshend, 1724–1807, British	1
(?) Henry Kingsbury, active 1750–1780, British	2

**Comment by yulgit1** [comment]
**possibly use an indexing of lido:nameActorSet with the lido:pref="preferred" attribute rather than existing author_ss**

this is indexed in auth_author_t  and auth_author_facet

**Comment by yulgit1** [comment]
Question: Create new element which is just "preferred" from lido for the Creator Facet, leaving show page the same author_ss?

Need to ensure lido and marc are the same format (firstname/lastname, name only/not-qualifiers) for this new element to work.

**Comment by yulgit1** [comment]
Explore authority mappings to ensure consistent labeling.

**Comment by mikeapp** [comment]
Looks like Vufind currently has correct order.  Blacklight only has primary.  
https://collections.britishart.yale.edu/vufind/Record/3622510 
https://ycba-collections-dev.herokuapp.com/catalog/3622510

**Comment by edgartdata** [comment]
@yulgit1 I am not sure if I should start a new issue for this?

We have talked about this problem before: the names of people appearing in the Creator facet should not be followed by their life dates and nationalities.

@flapka I think we agree on this but please confirm.

If you do agree, then the correct XPath for names of creators in LIDO DEV is:
lido:event[lido:eventType/lido:term='production']/lido:eventActor/lido:actorInRole/lido:actor/lido:nameActorSet/lido:appellationValue[@lido:pref='preferred']

**Comment by flapka** [comment]
@egardata @yulgit1 
I agree that the creator facet should not include prefatory qualifiers and role information. 

But for library material, at least, the creator data should include information that serves to disambiguate one name from another, and this *does* include dates and (less frequently) occupation etc.  Which is to say: for the auth_author (creator) facet we want to include everything in the MARC 100/110/111 field -- except subfield $e (which records role). This would required a tweak to the current MARC XSLT.

This leads to another question: In the Vufind mapping (Excel spreadsheet), there was a field called author_role (which is where we'd put subfield $e). Will there be an equivalent going forward?

**Comment by yulgit1** [comment]
questions re lido:
1) Currently 'author_ss' is the creator facet, index, and show page field.  Are you saying facet should be auth_author (leaving index and show page 'author_ss'?
2) currently auth_author is like the xpath Emmanuelle identifies above in LIDO DEV.  But it also pulls 'alternative' as well as 'preferred, leading to multiple auth_authors ex: http://10.5.96.187:3000/catalog/tms:1000.json
Should the 'auth_author_ss' just be the 1 preferred?

**Comment by yulgit1** [comment]
re marc:
Looks like 110/110/111 is already implemented: 'auth_author_ss'
https://git.yale.edu/ermadmix/ycba_xslts/blob/master/marc-preblacklight-ycba.xsl#L2641
Although it is not excluding subfield $e. I can exclude it though, is there a marc record I can use to test?

And I can add author_role for that 100/110/111 subfield 'e' if you like.  Again would need a sample marc record to test.

**Comment by flapka** [comment]
@yulgit1 re marc
Correct (thanks). Needs just a little tweak to exclude subfield $e.

Here's a straightforward example: http://10.5.96.187:3000/catalog/orbis:12632365

Subfield $e (role) is repeatable, and here's an example with repeated values, if you want to test it too: http://10.5.96.187:3000/catalog/orbis:3322526

We haven't discussed (to my knowledge) what to do with the role data. My 2 cents: Obviously I want to leave it out of the creator facet. In a record view, it would be fine for it appear it as it currently does, intermediately following the name (as in the two examples above) -- though I'd entertain other possibilities if the art collections want to do something else with such data.

**Comment by flapka** [comment]
@yulgit1 Need a quick tweak to the xslt mapping to remove all of this from the template for "author":

            <xsl:when test="marc:datafield[@tag='245']/marc:subfield[@code='c']">
                <xsl:element name="author_ss">
                    <xsl:value-of
                        select="normalize-space(marc:datafield[@tag='245']/marc:subfield[@code='c'])"
                    />
                </xsl:element>
            </xsl:when>

245 subfield $c is not appropriate for this field. Here's an example of why (notice the repeated and inappropriate text preceded by the "creator" label).

Thanks!

**Comment by edgartdata** [comment]
@flapka fixed? close?

**Comment by flapka** [comment]
Yes, looks fixed. Thanks!

Example: http://10.5.96.187:3000/catalog/orbis:582568
