### ISSUE TITLE
Links to objects from publications records in BlackLight

### ISSUE THREAD

**Issue by yulgit1** [ycba-cia/blacklight-collections2#411]
Making separate issue for this.  Got conflated with https://github.com/ycba-cia/blacklight-collections2/issues/193

**Comment by yulgit1** [comment]
@KraigBinkowski @edgartdata @flapka 

Please see:

https://collections-test.britishart.yale.edu/catalog/orbis:583000

This is the ref with the biggest number of object references (1223).  Unfortunately cannot both render and sort or paginate 1223, as it times-out.  So had to put a cap of 250 displayed, you see in that example "Referenced YCBA Works".

 Also see:
[pub_object_count.xlsx](https://github.com/ycba-cia/blacklight-collections2/files/9863172/pub_object_count.xlsx)

This lists the number of referenced objects for each publication, count descending.  The cap will only affect the first 4 of over 4000 with object references.  Note there are 38000 reference library total.  So hopefully capping 4 of 38000 should be too bad in the grand scheme of things.

Let me know If this is OK to promote to PROD.

**Comment by KraigBinkowski** [comment]
with those four, 250 makes a loooong list. Do we think it might be ok to cap it even lower? maybe at 150? that would implicate 9 records I think. What do others think?

**Comment by edgartdata** [comment]
Instead of having a long list of objects or arbitrarily deciding the length of the list, why not have one unique BL link to the group of objects in the book [(like what we do with objects in exhibitions)](https://collections-test.britishart.yale.edu/?f[exhibition_history_ss][]=Classic+Ground+-+British+Artists+and+the+Landscape+of+Italy%2C+1740-1830+%28Yale+Center+for+British+Art%2C+1981-07-29+-+1981-09-20%29) and then let users use the BL facets to narrow down their search further?

**Comment by yulgit1** [comment]
That is brilliant.  One link to result set based on orbis (ilsnumber) like screenshot:

![Screen Shot 2022-10-25 at 4 27 18 PM](https://user-images.githubusercontent.com/2125400/197875061-bbccf031-a24b-45f4-8059-7dd7bf62bd43.png)

https://collections-test.britishart.yale.edu/?utf8=✓&search_field=Fielded&q=ilsnumber_ss%3A583000

OK @KraigBinkowski @flapka?

**Comment by KraigBinkowski** [comment]
That sounds like a great idea
K

Sent from my Iphone, please excuse misspellings, brevity, and terseness.

On 25 Oct 2022, at 4:31 pm, yulgit1 ***@***.***> wrote:

﻿

That is brilliant. One link to result set based on orbis (ilsnumber) like screenshot:

[Screen Shot 2022-10-25 at 4 27 18 PM]<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F2125400%2F197875061-bbccf031-a24b-45f4-8059-7dd7bf62bd43.png&data=05%7C01%7Ckraig.binkowski%40yale.edu%7C1554636599064425431808dab6c7ecb5%7Cdd8cbebb21394df8b4114e3e87abeb5c%7C0%7C0%7C638023267040356913%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=UyVs1ExHPGXh6oNrSV%2BNDIWDn5Ei9e6gVYVo5EgW%2FYg%3D&reserved=0>

https://collections-test.britishart.yale.edu/?utf8=✓&search_field=Fielded&q=ilsnumber_ss%3A583000<https://collections-test.britishart.yale.edu/?utf8=%E2%9C%93&search_field=Fielded&q=ilsnumber_ss%3A583000>

OK @KraigBinkowski<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FKraigBinkowski&data=05%7C01%7Ckraig.binkowski%40yale.edu%7C1554636599064425431808dab6c7ecb5%7Cdd8cbebb21394df8b4114e3e87abeb5c%7C0%7C0%7C638023267040356913%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=otRtbXCceEgVcZoYYjdPZw%2FKffmEBymqqQFskCh%2BB%2Bg%3D&reserved=0> @flapka<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fflapka&data=05%7C01%7Ckraig.binkowski%40yale.edu%7C1554636599064425431808dab6c7ecb5%7Cdd8cbebb21394df8b4114e3e87abeb5c%7C0%7C0%7C638023267040356913%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=ahy1hsWNYLvwGCxAQbb%2Beco98kU0ff%2BX8HCh2rNAAbs%3D&reserved=0>?

**Comment by yulgit1** [comment]
Implemented, please see:

https://collections-test.britishart.yale.edu/catalog/orbis:583000 (biggest with 1223 referenced works)
https://collections-test.britishart.yale.edu/catalog/orbis:9425121 (example with 1 referenced work)
https://collections-test.britishart.yale.edu/catalog/orbis:582683 (example w/o referenced work, (nothing added))

OK to push to prod? @edgartdata @KraigBinkowski @flapka

**Comment by flapka** [comment]
The functionality is great! 

My only quibble or concern is that the link may be too subtle. If others agree, maybe we could do something to make it more prominent. Would it, for example, be worth treating as tabbed content, even though it's so short?

**Comment by edgartdata** [comment]
I agree with @flapka I think these links should go in a tab on the RBM and Ref Lib BL records.

**Comment by yulgit1** [comment]
In tabs now:

https://collections-test.britishart.yale.edu/catalog/orbis:583000 (biggest with 1223 referenced works)
https://collections-test.britishart.yale.edu/catalog/orbis:9425121 (example with 1 referenced work)
https://collections-test.britishart.yale.edu/catalog/orbis:582683 (example w/o referenced work, (nothing added))

OK to push to prod? @edgartdata @KraigBinkowski @flapka

**Comment by KraigBinkowski** [comment]
I think this looks great - I would push to prod.

**Comment by flapka** [comment]
I think the tab works nicely, for prominence.. I suggest tweaking the link language slightly. Perhaps: "View the [x work(s)] referenced in this item" or something in that vein.

**Comment by yulgit1** [comment]
published to prod with language tweak.
