### ISSUE TITLE
Exhibition links between online catalog and Drupal

### ISSUE THREAD

**Issue by yulgit1** [ycba-cia/blacklight-collections2#419]
deployed:
https://github.com/ycba-cia/blacklight-collections2/commit/54a55d5baac2081736e8db8fff427cd5430e2adc
https://github.com/ycba-cia/blacklight-collections2/commit/2448007264609a87110fdb75fac2cc6176dd7ea7

ex:
https://collections.britishart.yale.edu/catalog/tms:268
https://collections.britishart.yale.edu/catalog/tms:25369

**Comment by edgartdata** [comment]
Also see https://github.com/ycba-cia/blacklight-collections2/issues/193 for longer discussion of links to Drupal.
