### ISSUE TITLE
genre facet

### ISSUE THREAD

**Issue by yulgit1** [ycba-cia/blacklight-collections2#42]
keep open

project with Francis to enhance this facet + MARC mappings.

**Comment by yulgit1** [comment]
currently for genre_t and genre_facet:
```
    <xsl:template name="genre">
        <xsl:variable name="codes">abvxyz</xsl:variable>
        <xsl:for-each select="marc:datafield[@tag='655']">
            <xsl:element name="genre_t">
                <xsl:for-each select="marc:subfield[contains($codes,@code)]">
                    <xsl:value-of select="normalize-space(.)"/>
                    <xsl:if test="following-sibling::marc:subfield[contains($codes,@code)]">
                        <xsl:text> </xsl:text>
                    </xsl:if>
                </xsl:for-each>
            </xsl:element>
           ...
```

**Comment by edgartdata** [comment]
@flapka I see a note from earlier to enhance this facet + MARC mappings. Can we tackle this? some genres for the art collection are AAT terms, others are local terms, in case we were trying to harmonize between the art and library collections.

**Comment by flapka** [comment]
@edgartdata This is a toughie. Broadening your question, I see 4 (I think) categorizations, offered as facets, that could benefit from better harmonization of art-library data. In order of difficulty of harmonization (most difficult to least):
* Genre
* Medium
* Work type
* Classification

Genres recorded for library material just don't overlap much with the terms emphasized in records for art collections. The library genres primarily describe bibliographic genres -- and I wonder if our users would prefer to have separate facets for something like genre (bibliographic) and genre (art).

The other categories merit greater consideration for harmonization. Classification wouldn't be too difficult. Medium and work type would require quite a bit of data massaging (for library records) -- perhaps doable in the long run, but probably not before July 1.

**Comment by edgartdata** [comment]
@flapka Genres for the art collection are 20 controlled terms: portrait, landscape, botanical subject, literary subject, religious and mythological subject, cityscape, animal art, sporting art... Any correspondence with your collection?

**Comment by edgartdata** [comment]
@yulgit1 to add 655 to the Work Type facet (delete sub-division, capital letters, and the S at the end of ther RB terms).
@flapka will suggest a meeting with Elisabeth, Ed, and P&D colleagues to decide of the level of granularity of harmonized work types across our collections.

**Comment by yulgit1** [comment]
@flapka, after discussion in todays meeting not sure if i should I go ahead with implementing 655 in Work Type.  Yes? No?

**Comment by flapka** [comment]
@yulgit1 I think yes, with the textual manipulation described above: use only subfield $a, make lowercase, remove terminal 's'

**Comment by yulgit1** [comment]
addressed in:
https://git.yale.edu/ermadmix/camel_collections2/commit/ca2e0bfee3f8405f01825af1fbe412bee241c59c

and 

https://git.yale.edu/ermadmix/ycba_xslts/commit/3b06f85af7c87b4dd3f8f7a581c20ef431672131

will be indexed over the weekend

**Comment by edgartdata** [comment]
@flapka @yulgit1 Should i see the RB work types coming through the Work Type facet now?

**Comment by yulgit1** [comment]
@edgartdata Not yet.  I tested 1 and it worked, but the weekend index ran and no records updated, no clue why.  I set the marc index to run tonight with some logging, will check in the morning.

**Comment by flapka** [comment]
@yulgit1 @edgartdata Library data (from field 655) now shows up in the work type facet. In same cases the final 's' and period are successfully stripped from the headings (e.g. "wood engraving"), in others cases they aren't (e.g. "memorial cards."). Eric, do you have an idea of what may be causing these different outcomes?

**Comment by yulgit1** [comment]
@flapka the period is the last character not the 's', so the s isn't stripped

**Comment by yulgit1** [comment]
@flapka - modified this to strip "." and "s", will run indexing tonight

https://git.yale.edu/ermadmix/camel_collections2/commit/abf0d5933a113ff04e22b2de9272567a639a850e

**Comment by yulgit1** [comment]
@flapka - ok?

**Comment by yulgit1** [comment]
Francis reviewing marc source...
