### ISSUE TITLE
Empty collection results necessary?

### ISSUE THREAD

**Issue by edgartdata** [ycba-cia/blacklight-collections2#420]
All, following the "Referenced YCBA Works" in https://collections-test.britishart.yale.edu/catalog/orbis:583000 correctly returns all the P&S and P&D works illustrated or discussed in the book but the Collection facet also show 0 results for Archives, Frames, Rare Books and Reference Library. Do we want these null results to be displayed in the Collection facet?

![image](https://user-images.githubusercontent.com/4093644/203084121-ecff8a9a-f32c-4d5c-b610-a8d4512a54e2.png)

**Comment by flapka** [comment]
No, I think null results should not be displayed -- to be consistent with how our facets display in other contexts. 

For the fielded:ilsnumber search, null results appears in other facets too, e.g. Classification and Period.

![image](https://user-images.githubusercontent.com/7634899/203086231-5fa860e7-b306-4806-a9b8-81708a6fbec8.png)


![image](https://user-images.githubusercontent.com/7634899/203086063-e603df52-651e-4b5e-b020-9cb0e9513f48.png)

**Comment by edgartdata** [comment]
Medium and Subject Terms as well so I think it might be something to reset overall/on all the facets.

**Comment by yulgit1** [comment]
Fixed.  Added facet.mincount=1 in solrconfig.xml in: 

https://ciaindex.britishart.yale.edu/solr/#/~cores/ycba_blacklight_prod
https://ciaindex.britishart.yale.edu/solr/#/~cores/ycba_blacklight

```
<requestHandler name="/query" class="solr.SearchHandler">
    <lst name="defaults">
      <str name="echoParams">explicit</str>
      <str name="wt">json</str>
      <str name="indent">true</str>
      <str name="facet.mincount">1</str>
    </lst>
  </requestHandler>
```
