### ISSUE TITLE
Rights Statement badge display and link for "No Copyright - Contractual Restrictions"

### ISSUE THREAD

**Issue by mxgold** [ycba-cia/blacklight-collections2#421]
For works with TMS ORT "contract restricted" badge display and link in Blacklight to the rights statement ["No Copyright - Contractual Restrictions"](https://rightsstatements.org/page/NoC-CR/1.0/?language=en)  needs to be implemented.

[YCBA Standardized Rights Implementation mapping](https://docs.google.com/spreadsheets/d/19nfSflTxg52-WUYX3-tyqMWk5qfqHh3pgE9jLxzFQVg/edit?usp=sharing)

**Comment by yulgit1** [comment]
Resolved:

https://collections.britishart.yale.edu/catalog/tms:1200
https://collections.britishart.yale.edu/catalog/tms:51893

Note :Tombstone Copyright Status still says "Copyright Undetermined" "Public Domain" respectively for above 2 examples.  To change, use TMS, and allow to index overnight.
