### ISSUE TITLE
update reference library holding message

### ISSUE THREAD

**Issue by yulgit1** [ycba-cia/blacklight-collections2#427]
From @KraigBinkowski:

The note in the Holdings area of a bib record in the online catalogue currently states:
Note: The Reference Library is open by appointment. Please visit the [Reference Library page](https://britishart.yale.edu/reference-library-and-photograph-archives) on our website for more details. For scans from the reference collection please email [ycba.reference@yale.edu](mailto:ycba.reference@yale.edu).
 
We are now open to Yale affiliates without an appointment – could we perhaps change this note to:
Note: Non-Yale users must make an appointment to use the Reference Library. Please visit the [Reference Library page](https://britishart.yale.edu/reference-library-and-photograph-archives) on our website for more details. For scans from the reference collection please email [ycba.reference@yale.edu](mailto:ycba.reference@yale.edu).
 
Thanks and please let me know if you have any questions. I believe that the Study Room is still requiring appointments so the Rare Books note would remain as it is.

**Comment by yulgit1** [comment]
updated:
https://github.com/ycba-cia/blacklight-collections2/commit/bc4e8f3117eca681bcb00346a99bde680a1f84e3

**Comment by edgartdata** [comment]
Closing this as it was taken care of in https://github.com/ycba-cia/blacklight-collections2/issues/436
