### ISSUE TITLE
New text for online catalog banner while the museum is closed

### ISSUE THREAD

**Issue by edgartdata** [ycba-cia/blacklight-collections2#428]
@yulgit1 Could you please change the banner text to:
“The YCBA will close for building renovation on February 27, 2023. While the museum is closed, access to the collections will be by appointment only.” 
Kristin Dwyer suggested the text above from the new language for the “Accessing Collections” that was approved by Courtney.

https://britishart.yale.edu/using-collections 
While the Yale Center for British Art is [closed](https://britishart.yale.edu/news-and-press/yale-center-british-art-close-public-building-conservation-2023), access to the collections will be by appointment only. Requests for an appointment should be made at least two weeks in advance of the proposed date to the relevant curatorial department. Each request should list the specific objects desired for viewing. Group size will be limited to a maximum of four visitors. Collections staff will make every effort to provide access to objects. Due to construction and transportation constraints some objects may unavailable for the duration of the project. Feel free to contact the relevant curatorial department in advance of making a request to discuss specific objects.

**Comment by yulgit1** [comment]
changed:
https://github.com/ycba-cia/blacklight-collections2/commit/f39449d755bcacaed3175edba470cdaf48d118ff
