### ISSUE TITLE
work type facet

### ISSUE THREAD

**Issue by yulgit1** [ycba-cia/blacklight-collections2#43]
currently object_name_ss

The mapping needs to be refined for the art collection. The appropriate LIDO element is <lido:objectWorkType> when the lido:type="Object name" only

**Comment by yulgit1** [comment]
object_name_ss currently under:
<xsl:for-each select="lido:objectClassificationWrap/lido:objectWorkTypeWrap/lido:objectWorkType">
...
<xsl:when test="lido:conceptID/@lido:type='Object name'">

**Comment by edgartdata** [comment]
Close this issue. These are data mistakes to be corrected in TMS.
