### ISSUE TITLE
Update name of fielded search for provenance

### ISSUE THREAD

**Issue by edgartdata** [ycba-cia/blacklight-collections2#438]
@yulgit1 Can you please change the name of the search field from "Available Provenance" to "Search Provenance"? Thanks.

![BL provenance search](https://user-images.githubusercontent.com/4093644/217562099-ed3be7e7-fc15-4603-9f5d-b16c772f13a9.png)

**Comment by yulgit1** [comment]
Changed:
https://github.com/ycba-cia/blacklight-collections2/commit/92b3e9a76b7b7afeea8f847fc5b767d26768f69c
