### ISSUE TITLE
Replace "Support (PTG)" with "Unframed"?

### ISSUE THREAD

**Issue by edgartdata** [ycba-cia/blacklight-collections2#439]
For paintings, we use “Support (PTG)” as a qualifier to explain what the dimensions are for. 

For example, the dimensions for [Mortimer West Gate painting](https://collections.britishart.yale.edu/catalog/tms:1240), currently read: 
Support (PTG): 27 7/8 x 35 3/4 inches (70.8 x 90.8 cm) and Frame: 33 1/2 × 41 1/2 × 4 inches (85.1 × 105.4 × 10.2 cm)

This term is not user friendly and we want to replace it with one that is more precise and more user friendly. 

Today “Support (PTG)” is only used for paintings unframed dimensions so I would like to suggest we replace it with “Unframed” in TMS and in the online catalog.

Any objections before we do a bulk change in TMS? I have checked with registrars who have no objections and defer to curators on this.

**Comment by yulgit1** [comment]
No objections, something to do before the next LUX delivery.

**Comment by edgartdata** [comment]
I'd like to get confirmation to go ahead from curators. @EdwardTown1 @LaurelOP what do you think?

**Comment by LaurelOP** [comment]
I don't have any objections, but really defer to @EdwardTown1 here.

**Comment by yulgit1** [comment]
Per recent conversations, Support (PTG) will be implicit.

https://github.com/ycba-cia/coboat-github/commit/9bc2ea838f74f1dba4e3ee8b55cdb06657c8afde

**Comment by yulgit1** [comment]
Also have to not concat colon when not vending extent.

https://git.yale.edu/ermadmix/ycba_xslts/commit/3e0c5a441690453f5641e6c15e130241d413e20d

**Comment by edgartdata** [comment]
@yulgit1 For paintings only, before the frame dimensions, could you replace "and" with a comma?

So instead of this:
27 7/8 x 35 3/4 inches (70.8 x 90.8 cm) and Frame: 33 1/2 × 41 1/2 × 4 inches (85.1 × 105.4 × 10.2 cm)

we would have this:
27 7/8 x 35 3/4 inches (70.8 x 90.8 cm), Frame: 33 1/2 × 41 1/2 × 4 inches (85.1 × 105.4 × 10.2 cm)

**Comment by yulgit1** [comment]
Comma separator for LIDO frame dimensions deployed:
https://github.com/ycba-cia/blacklight-collections2/commit/7ae4c6a4aa465c69090208f441cc10da83251b8d
