### ISSUE TITLE
cap image request title param < 255 characters length 

### ISSUE THREAD

**Issue by yulgit1** [ycba-cia/blacklight-collections2#441]
resolved: https://github.com/ycba-cia/blacklight-collections2/commit/dceb7b4379293dbfb06177424f20814dd12ce2ee

Example:
https://collections.britishart.yale.edu/catalog/orbis:12462697

before:
Voyage dans la Russie méridionale et la Crimée : par la Hongrie, la Valachie et la Moldavie / exécuté en 1837 par Mr. Anatole de Demidoff ; édition illustrée de soixante-quatre dessins par Raffet. ; Dédié à S.M. Nicolas Ier, empereur de toutes les

after:
Voyage dans la Russie méridionale et la Crimée : par la Hongrie, la Valachie et la Moldavie / exécuté en 1837 par Mr. Anatole de Demidoff ; édition illustrée de soixante-quatre dessins par Raffet. ; Dédié à S.M. Nicolas Ier, empereur de to

**Comment by flapka** [comment]
Thanks @yulgit1 ! I think we can count this resolved.
