### ISSUE TITLE
Add dimensions to BL list view mode for TMS collections

### ISSUE THREAD

**Issue by edgartdata** [ycba-cia/blacklight-collections2#442]
@yulgit1 Could we please have dimensions just after Medium in the list view for TMS collections? https://collections.britishart.yale.edu/?q=fishing&search_field=all_fields&utf8=%E2%9C%93&view=list

**Comment by yulgit1** [comment]
All set:
https://github.com/ycba-cia/blacklight-collections2/commit/b106514d742353db60bc961e5cd24c0f90aad711

**Comment by yulgit1** [comment]
Request:
For the Ref Lib and RBM collections, would it be possible to use “Physical Description” instead of “Dimensions” in the list view for these collections?

**Comment by yulgit1** [comment]
Addressed:
https://github.com/ycba-cia/blacklight-collections2/commit/6e978db192d439f8a2cf380ecb0ca10a401ee1d5

https://collections.britishart.yale.edu/?f%5Bcollection_ss%5D%5B%5D=Rare+Books+and+Manuscripts&view=list
https://collections.britishart.yale.edu/?f%5Bcollection_ss%5D%5B%5D=Paintings+and+Sculpture
