### ISSUE TITLE
subject terms facet

### ISSUE THREAD

**Issue by yulgit1** [ycba-cia/blacklight-collections2#45]
For the art collections, this facet should only be mapped to <lido:subjectConcept> when lido:type="subjectConcept" and lido:type="subjectObject”

alphabetical

**Comment by yulgit1** [comment]
Limited this facet:

https://github.com/ycba-cia/blacklight-collections2/commit/0d3feb954eb66eba8c1b2151d61bb85ed39e1e29

alphabetical makes it worse (fields with 1 hit, starting with quoted fields comes to top), so leaving as is

**Comment by yulgit1** [comment]
Related to #31

In #31 there is the call for removing from Actor and Place.  Does this mean remove from Event as well (leaving 'topic' only mapped to template topic, Concept and Object) (see below)?

in the xsl topic_facet and topic_t(which is used as topic_ss in blacklight) are populated in the following templates:

topic (647)
topic_subjectConcept (963)
topic_subjectActor (977) x
topic_subjectEvent (991) x
topic_subjectPlace (1005)x
topic_subjectObject (1025)

**Comment by edgartdata** [comment]
numerical order for subject terms in the subject facet would be better.

**Comment by edgartdata** [comment]
The subject facet for the art collections should only have subjectConcept, subjectEvent, and subjectObject. 

SubjectPlace will go to the Places Represented facet. SubjectActors will go to the People Represented facet.

**Comment by flapka** [comment]
@yulgit1 @edgartdata Library subjects are missing from the subject terms facet. I think that's a new development, or did I miss something?

**Comment by yulgit1** [comment]
@flapka - what exactly are you seeing? As far as I can tell limiting collection by RB or REF shows a full array of subject terms.

**Comment by flapka** [comment]
Gah, sorry, I'm guilty of not looking past the first 20 or so terms in the facet (which all came from art collections). Nothing broken!
