### ISSUE TITLE
Multiple image download

### ISSUE THREAD

**Issue by edgartdata** [ycba-cia/blacklight-collections2#450]
@yulgit1 It is possible to download multiple images from one record but users have to select each image at a time, for example for https://collections.britishart.yale.edu/catalog/tms:54650

Would it be possible to download all images at once in the order they appear in the image viewer?

**Comment by yulgit1** [comment]
The current setup works on an image by image basis. It might be possible to use javascript and scrape the whole manifest for download.

**Comment by yulgit1** [comment]
Please see a new "Print All" button. Screenshot:

![Screen Shot 2023-03-31 at 4 37 02 PM](https://user-images.githubusercontent.com/2125400/229225892-f0340388-f963-46f3-945e-992b78e0e864.png)

Kind of slow, especially when many images, but there if needed.

**Comment by edgartdata** [comment]
Oh this looks very promising! The images take a bit of time to load though and then they disappear if i go to another webpage.

**Comment by yulgit1** [comment]
In case it's not obvious, for download click "Print All", Click the "Print this page" once all the images load and save as PDF.

**Comment by edgartdata** [comment]
Yes, I am doing that but images have trouble loading. 
This sketchbook is a good test candidate: https://collections.britishart.yale.edu/catalog/tms:54650

**Comment by yulgit1** [comment]
Printed the Hodges 54650 as a PDF.  Only took a few seconds, and renders the 32 images page by page nicely.
