### ISSUE TITLE
Add “On view at YUAG” to the list view for appropriate objects from P&S, P&D, and RBM

### ISSUE THREAD

**Issue by edgartdata** [ycba-cia/blacklight-collections2#456]

**Comment by yulgit1** [comment]
Resolved.

https://github.com/ycba-cia/blacklight-collections2/commit/0ee960a8959498943e1f422b490c206287508ce9
https://github.com/ycba-cia/blacklight-collections2/commit/d99efbd8f12f2d674927b721b1ae2c312daa85bd
