### ISSUE TITLE
Result boosting

### ISSUE THREAD

**Issue by edgartdata** [ycba-cia/blacklight-collections2#459]
Do in the test catalog first:
o	Add the contributors brought in by the library collections
o	Boost watercolors by Turner before paintings by unknown or Derby

**Comment by flapka** [comment]
The current boosting specs have an undesirable impact when search results are limited to RBM: https://collections.britishart.yale.edu/?f%5Bcollection_ss%5D%5B%5D=Rare+Books+and+Manuscripts&q=&search_field=simple_search. 

Previously, RBM objects with images available have appeared first, and that's an outcome that we'd like to retain. After Tim starts, we might also entertain discussion of whether we'd want certain creators boosted for RBM objects (as a secondary criterion).

**Comment by yulgit1** [comment]
@flapka I lowered the boosting of the 14 featured artists for library (when author_sort_s is of form "FN,LN,") in test please see difference between

https://collections.britishart.yale.edu/?f%5Bcollection_ss%5D%5B%5D=Rare+Books+and+Manuscripts
https://collections-test.britishart.yale.edu/?f%5Bcollection_ss%5D%5B%5D=Rare+Books+and+Manuscripts

Note there are still ones in test without images ranked high due to settings:

```
has_image_ss:"available"^13 
onview_ss:"On view at the Yale University Art Gallery"^12
type_ss:"Paintings"^11.5
```
I could try tweaking has_image_ss even higher maybe?  Let me know.

**Comment by flapka** [comment]
Thanks @yulgit1. I think we'd like the results with images much higher still -- so that it trumps all other criteria (for RBM material, at least). How high could we boost it?

**Comment by yulgit1** [comment]
@flapka Please compare now:

https://collections.britishart.yale.edu/?f%5Bcollection_ss%5D%5B%5D=Rare+Books+and+Manuscripts
https://collections-test.britishart.yale.edu/?f%5Bcollection_ss%5D%5B%5D=Rare+Books+and+Manuscripts

**Comment by flapka** [comment]
That's much better. I'd consider it fixed.

After Tim starts (as curator), we can get his thoughts on whether there are other criteria that might be used in the boosting. I wonder: would it be possible to boost things that have been in exhibitions (and if so, could more exhibitions = more boosted)?

**Comment by yulgit1** [comment]
OK, I will implement in prod.  

Also as far as boosting by number of exhibitions it would be difficult but possible, the indexer would have to get a count of the exhibition field and use a boost function:
https://stackoverflow.com/questions/6240092/solr-function-query-that-operates-on-count-of-multivalued-field
https://solr.apache.org/guide/6_6/the-dismax-query-parser.html

**Comment by edgartdata** [comment]
@flapka Would you like to open a new/separate issue about boosting RBM items that have been in exhibitions?
