### ISSUE TITLE
place represented facet

### ISSUE THREAD

**Issue by yulgit1** [ycba-cia/blacklight-collections2#46]
as a project:
hierarchical or authority or coordinates (metadata issue-how?)

use a maps widget: https://github.com/projectblacklight/blacklight-maps

**Comment by edgartdata** [comment]
The map requires coordinates. In the future can we look into reusing the Getty TGN's coordinates to generate a map, instead of us having to copy them into a system that copies them into TMS tables on data export?

**Comment by edgartdata** [comment]
Is it a linked open data?

**Comment by edgartdata** [comment]
@yulgit1 @flapka Does LoC have authority files for names of places? If not, do you use other authorities?

**Comment by flapka** [comment]
Yes, the LC authority file includes places -- and the authority records for at least some (or most? all?) include coordinate information in some of the data serializations. It looks like the coordinate information comes from geonames? Example: http://id.loc.gov/authorities/names/n79084149.marcxml.xml

**Comment by edgartdata** [comment]
I am not sure the LOD version of Getty TGN references Geonames. I don’t even see LC in it. I hope I’m wrong!

**Comment by yulgit1** [comment]
@edgartdata @flapka @miriamschroers Are there any action items here? Should this move out of batch 2?  Is the facet ok as is? I think a map just for place represented would take over too much of the screen and getting the coordinates in the index to do this would be non-trivial anyway.

**Comment by flapka** [comment]
This sounds to me like an after-July-1 project.

**Comment by edgartdata** [comment]
Do we want this facet to represent cases when a library item is about a place rather than a visual representation of that place? April 23 discussion item.

**Comment by KraigBinkowski** [comment]
In general, I am in favor of providing reference results with materials "about" an artist, a place, or thing when objects are searched as being "of". This, to me, is one of the real benefits to being able to search library materials alongside museum objects, otherwise an orbis search does the same thing.

**Comment by edgartdata** [comment]
Elisabeth is okay with bringing RB subject headings that have to do with locations/places treated as subjects in her collection.

**Comment by KraigBinkowski** [comment]
In case it wasn't clear from above - I am fine with having ref subject headings that are locations/places in the Associated Places facet as well.

**Comment by edgartdata** [comment]
RB data showing up in this facet.
