### ISSUE TITLE
new technical description text entry

### ISSUE THREAD

**Issue by yulgit1** [ycba-cia/blacklight-collections2#462]
Request from @edgartdata:

Can you please vend a new/additional LIDO text entry to the test BL? Painting conservation has a GRA who is writing short technical descriptions for the online catalog and I have entered 2 of them in TMS as LIDO-Technical description text entries. One is for B1974.2.74/objectID 11627 and the other is for B1975.1.5/ObjectID 196.
Would it be possible to review them in the test BlackLight next time the online catalog group meets on Thursday 4/27?
 
They would have the same XML structure as the other gallery labels:
 
```
<lido:eventSet>
<lido:displayEvent> This portrait of Elizabeth, Queen of Bohemia is painted in watercolor on vellum that has been adhered to a playing card. The card’s printed club motif is visible on the miniature’s reverse. ---
 
This work has been extensively retouched and reworked. As a result, it is difficult to discuss the artist’s technique. It appears that Oliver modelled Elizabeth’s flesh using soft stippled strokes of red, brown, and blue paint, though much of the blue tone in her skin is the result of later overpainting. Oliver applied a thin wash of light brown paint to form the shape of the hair. He then painted a tight network of curved strokes of darker brown paint and dots of azurite blue to represent Elizabeth’s nest of soft curls. The artist stippled the paint at the hairline to create a gradation between flesh and hair. ---
 
Elizabeth’s ruff was first blocked in with a wash of creamy white modelled with light grey. The artist then used lead white to trace individual threads of lace. The purple dress, which remains in good condition, was painted with a mixture of red lake and azurite pigment. Isaac adorned this dress with patterns painted with shell-silver as well as floral motifs painted in green, orange, and blue. Both the sitter’s pearl necklace and earring are heavily overpainted. There is no evidence of a gold border around the work’s azurite background, but Oliver’s “IO” monogram is painted using shell gold above the sitter’s right shoulder. ---
 
There are losses in the sitter’s lace collar, the jewelry has been re-worked, and there is retouching throughout Elizabeth’s face. --- --- Technical description, 2023 </lido:displayEvent>
<lido:event>
<lido:eventID lido:type="TMS">11627</lido:eventID>
<lido:eventType>
<lido:conceptID lido:source="AAT" lido:type="local">300435429</lido:conceptID>
<lido:term>Technical description</lido:term>
</lido:eventType>
<lido:eventDate>
<lido:displayDate>2023</lido:displayDate>
</lido:eventDate>
</lido:event>
</lido:eventSet>
```
 
Once the technical descriptions are edited and approved, then we can push them to our prod catalog and LUX.

**Comment by yulgit1** [comment]
solr support for new technical description field, added to master branch:
https://git.yale.edu/ermadmix/ycba_xslts/commit/028bd17167d362acb6b46bf1594324984884fe42

master branch deployed on:
10.5.34.110/app/ycba_xslts (prod, transparent until LIDO change)
105.96.187/app/development/ycba_xslts (test)

**Comment by yulgit1** [comment]
blacklight support for new technical description field added to contributors branch:
https://github.com/ycba-cia/blacklight-collections2/commit/8f3485912dd9513f7ace07b456cf1531bd8c5077

pushed contributors branch to origin and heroku github remotes for test.

TODO:
run indexing in development once changes are in LIDO and test here:
https://ycba-collect-contributo-wb4csf.herokuapp.com/

TODO: 
Once tested, make these changes in master branch and deploy.

**Comment by yulgit1** [comment]
Indexed to dev instance, @edgartdata please see technical description in these records:

https://ycba-collect-contributo-wb4csf.herokuapp.com/catalog/tms:196
https://ycba-collect-contributo-wb4csf.herokuapp.com/catalog/tms:11627

Note this instance also has marc contributors indexed in Creator facet, and the latest tweaks to page rank boostings.

**Comment by edgartdata** [comment]
Let's not push this to production until we get a green light from conservation and editor.
