### ISSUE TITLE
Artists honorifics/knighthood in YCBA Creator facet

### ISSUE THREAD

**Issue by edgartdata** [ycba-cia/blacklight-collections2#469]
Result of 10/19/2023 discussion: Curatorial approves the mention of artists' knighthood as part of constituents cataloguing, except whenever the artists themselves have said they don't want the title to appear with their name, such as Rachel Whiteread.

Next steps: 
- Emmanuelle to share a list of all knighted artists represented in the art collection with RBM
- After review by RBM, Emmanuelle to share the list with Eric James to be added to the BlackLight conversion table that drives the Creator facet
- CIA will update the appropriate existing TMS constituents records
- Going forward whoever in P&D and P&S creates new TMS constituents records will be responsible for including "Sir" or "Dame" in the TMS Prefix field (Emmanuelle will be automatically alerted of the record creation)
- For artists who do not want knighthood to be included in their names, their TMS Constituent records 
- Emmanuelle will update the TMS Cataloguing Manual (it is on the [CIA SharePoint page](https://yaleedu.sharepoint.com/sites/YCBA/testsite/SitePages/Collections%20Information%20Access.aspx) along with the YCBA Provenance Style Guide, Credit Line Style Guide, Conservation Studio & Image Upload Platform user manuals)

@flapka @yulgit1 Anything else in terms of next steps?
@EdwardTown1 @mxgold @LaurelOP Do you know of artists who have been knighted but do not want the title in their names?

We will stop including artists' affiliation with Royal Academy (RA, PRA, ARA) and with any other learned or artistic societies in the TMS constituents records.

Next steps:
- Emmanuelle will delete the RA titles from the TMS records
- Emmanuelle will update the TMS Cataloguing Manual

**Comment by mxgold** [comment]
Rachel Whiteread is the only artist I am aware of that has expressed such a preference at this time.


From: Emmanuelle Delmas-Glass ***@***.***>
Sent: Thursday, October 19, 2023 3:37 PM
To: ycba-cia/blacklight-collections2 ***@***.***>
Cc: Fournier, Melissa ***@***.***>; Mention ***@***.***>
Subject: [ycba-cia/blacklight-collections2] Artists honorifics/knighthood in YCBA Creator facet (Issue #469)


Result of 10/19/2023 discussion: Curatorial approves the mention of artists' knighthood as part of constituents cataloguing, except whenever the artists themselves have said they don't want the title to appear with their name, such as Rachel Whiteread.

Next steps:

  *   Emmanuelle to share a list of all knighted artists represented in the art collection with RBM
  *   After review by RBM, Emmanuelle to share the list with Eric James to be added to the BlackLight conversion table that drives the Creator facet
  *   CIA will update the appropriate existing TMS constituents records
  *   Going forward whoever in P&D and P&S creates new TMS constituents records will be responsible for including "Sir" or "Dame" in the TMS Prefix field (Emmanuelle will be automatically alerted of the record creation)
  *   For artists who do not want knighthood to be included in their names, their TMS Constituent records
  *   Emmanuelle will update the TMS Cataloguing Manual (it is on the CIA SharePoint page<https://yaleedu.sharepoint.com/sites/YCBA/testsite/SitePages/Collections%20Information%20Access.aspx> along with the YCBA Provenance Style Guide, Credit Line Style Guide, Conservation Studio & Image Upload Platform user manuals)

@flapka<https://github.com/flapka> @yulgit1<https://github.com/yulgit1> Anything else in terms of next steps?
@EdwardTown1<https://github.com/EdwardTown1> @mxgold<https://github.com/mxgold> @LaurelOP<https://github.com/LaurelOP> Do you know of artists who have been knighted but do not want the title in their names?

We will stop including artists' affiliation with Royal Academy (RA, PRA, ARA) and with any other learned or artistic societies in the TMS constituents records.

Next steps:

  *   Emmanuelle will delete the RA titles from the TMS records
  *   Emmanuelle will update the TMS Cataloguing Manual

-

**Comment by edgartdata** [comment]
Phyllida Barlow has requested that we don't use "Dame" in front of her name.

**Comment by yulgit1** [comment]
Wait, Phyllida Barlow as is doesn't have "Dame", and she apparently died in 2023?

https://collections.britishart.yale.edu/?utf8=%E2%9C%93&search_field=simple_search&q=phyllida

mapping:
Barlow, Phyllida -> Barlow, Phyllida, 1944–2023

**Comment by edgartdata** [comment]
What's your question? We have already worked on her name. See https://collections.britishart.yale.edu/?utf8=%E2%9C%93&search_field=simple_search&q=phyllida

**Comment by yulgit1** [comment]
You said "Phyllida Barlow has requested that we don't use "Dame" in front of her name."

(1) Apparently she's not alive, so I don't understand how she has requested it?
(2) There's nothing to change, the facets don't have "Dame" in it.

**Comment by mxgold** [comment]
(Her estate / gallery made the request.)


On Mar 27, 2024, at 3:22 PM, yulgit1 ***@***.***> wrote:

﻿

You said "Phyllida Barlow has requested that we don't use "Dame" in front of her name."

(1) Apparently she's not alive, so I don't understand how she has requested it?
(2) There's nothing to change, the facets don't have "Dame" in it.

**Comment by edgartdata** [comment]
Thanks Melissa. 
@yulgit1 I was only documenting her estate request here (it's also in TMS) so that we know the lack of 'Dame' before her name is not a mistake.
