### ISSUE TITLE
Make Print tombstone data a bigger font

### ISSUE THREAD

**Issue by yulgit1** [ycba-cia/blacklight-collections2#473]
done:
https://github.com/ycba-cia/blacklight-collections2/commit/efaf57423b5b7ed1d1cb853ef26d9ee0e08a7770

**Comment by edgartdata** [comment]
[Dort-Print-Larger font.pdf](https://github.com/ycba-cia/blacklight-collections2/files/14223481/Dort-Print-Larger.font.pdf)
[Helmingham Bestiary-Print-Larger font.pdf](https://github.com/ycba-cia/blacklight-collections2/files/14223499/Helmingham.Bestiary-Print-Larger.font.pdf)
