### ISSUE TITLE
added large print

### ISSUE THREAD

**Issue by yulgit1** [ycba-cia/blacklight-collections2#475]
in commit:
https://github.com/ycba-cia/blacklight-collections2/commit/b0bdc411e8a549f5ae8f3a50dd10cb6e3550450a

**Comment by edgartdata** [comment]
The scope of the content of a large print label is different from that for an art object versus for a RBM item.
[Dort-Print-Large print label.pdf](https://github.com/ycba-cia/blacklight-collections2/files/14223545/Dort-Print-Large.print.label.pdf)
[Helmingham Bestiary-Print-Large print label.pdf](https://github.com/ycba-cia/blacklight-collections2/files/14223546/Helmingham.Bestiary-Print-Large.print.label.pdf)

Now working on the placement of the Large Print Label button and moving it to near the IIIF button.
