### ISSUE TITLE
credit line facet

### ISSUE THREAD

**Issue by yulgit1** [ycba-cia/blacklight-collections2#48]
work with francis to add for bibliographic collections

**Comment by yulgit1** [comment]
from Emmanuelle's crosswalk doc: 524 $a has a rough equivalent when it's there.

FWIW lido uses: 'lido:rightsWorkWrap/lido:rightsWorkSet/lido:creditLine'

**Comment by flapka** [comment]
524 $a = "Cite as." It contains credit line information, but it's accompanied by non-credit-line data. E.g.: 
"Account of the Last Voyage of Thomas Cavendish. Yale Center for British Art, Paul Mellon Collection."

Also: the 524 (cite as) field is infrequently used. It's in less than .1% of RB records.

More appropriate for the credit line facet would be MARC 541 $a -- which we now use systematically to record gifts. Here it is recorded in proper credit line form.  Adjust mapping?

**Comment by yulgit1** [comment]
action:
xslt add template - credit_line_facet for MARC 541 $a

**Comment by flapka** [comment]
@yulgit1 For MARC records, map as follows for now:

Concatenate "Yale Center for British Art, " & 541 subfield $a

We have few records with credit line info (for now). But for those that we do, the concatenation will results strings like: "Yale Center for British Art, Gift of Ellen and Arthur Liman, Yale JD 1957" for this item: http://10.5.96.187:3000/catalog/orbis:13687471

Conversely, once the above is implemented, we should remove 541 from the fields that map as a note (=description).

**Comment by yulgit1** [comment]
credit line reindexed over weekend ok, but still need to remove from 541 from note

http://10.5.96.187:3000/catalog/orbis:13687471

**Comment by flapka** [comment]
Wonderful. Yes, removing 541 from note is the other big step.

@yulgit1 I realize now (apologetically) that in a small number of cases the data in the 541 field already includes the words "Yale Center for British Art" -- i.e. before concatenation. In those few cases, we end up with a credit line like: "Yale Center for British Art, Yale Center for British Art, acquired with funds from the Bequest of Daniel S. Kalk." See: http://10.5.96.187:3000/catalog/orbis:13557093 

If possible, it would be good to change the mapping to reflect this logic:

If 541 contains "Yale Center", then mapping = 541 subfield $a
else: Concatenate "Yale Center for British Art, " & 541 subfield $a

**Comment by yulgit1** [comment]
remove 541 addressed:
https://git.yale.edu/ermadmix/ycba_xslts/commit/993ba40c6ddf8824383e3f4395c06937bef48e34

concat logic addressed:
https://git.yale.edu/ermadmix/ycba_xslts/commit/b1987ae907f4c2b49962e8b84a587603ad91dd8b

will show up after next indexing
