### ISSUE TITLE
New artists biographies

### ISSUE THREAD

**Issue by yulgit1** [ycba-cia/blacklight-collections2#480]
@edgartdata:
It would be great if we could add to heroku the new biographical line that curatorial is adding in TMS.

For example, currently for Brunias we vend: <lido:displayActorInRole>Agostino Brunias, 1728–1796, Italian, active in Britain (1758–70; 1777-80s)</lido:displayActorInRole>

Going forward, for heroku only, we want to add (but not replace) this new <lido:displayActorInRole>Born in Rome, Italy, 1728; active in Italy, England, Antigua, Barbados, Dominica, Grenada and St Vincent; died in Roseau, Dominica, 1796</lido:displayActorInRole>
This additional biography comes from the TMS Display Bio field ONLY when its associated Bio Remarks field contains "New bio line".

So for this addition to our LIDO XML, this [work by Brunias](https://harvester-bl.britishart.yale.edu/oaicatmuseum/OAIHandler?verb=GetRecord&identifier=oai:tms.ycba.yale.edu:54267&metadataPrefix=lido) (TMS objectID 54267) would lok like this:

<lido:eventActor>
      <lido:displayActorInRole>Agostino Brunias, 1728–1796, Italian, active in Britain (1758–70; 1777-80s)</lido:displayActorInRole>
      <lido:displayActorInRole lido:label="New bio line">Born in Rome, Italy, 1728; active in Italy, England, Antigua, Barbados, Dominica, Grenada and St Vincent; died in Roseau, Dominica, 1796</lido:displayActorInRole>
     
I suppose that for heroku, soon to be Drupal, you would have to add "Born in Rome, Italy, 1728; active in Italy, England, Antigua, Barbados, Dominica, Grenada and St Vincent; died in Roseau, Dominica, 1796" to json. The question is which one?

Also, is "author_sort_s": "brunias agostino, 1728–1796" for the Creator facet? If yes, we want to keep using this primary bio for the Creator facet because the new bio lines are too long for the facet. Is that possible?

**Comment by yulgit1** [comment]
Here's an example of new artists biography as implemented in the test branch/drupal prototype:
https://ycba-collect-artists2-hiwi651p.herokuapp.com/catalog/artists:2

I set up the coboat, and modified xslt to index an "author_bio_ss" field with this info, name to be consistent, to run tonight.

https://github.com/ycba-cia/coboat-github/commit/45fc6c080ac99383d40fc50861ce50750e611a81
https://git.yale.edu/ermadmix/ycba_xslts/commit/0a4540503461741cf2031f61e1799e31cf68fed6

Where do we want it to display in the test branch/drupal prototype?

**Comment by edgartdata** [comment]
As you have it now, i.e. right under the name of the artist is great.
