### ISSUE TITLE
vufind blacklight feature comparison

### ISSUE THREAD

**Issue by yulgit1** [ycba-cia/blacklight-collections2#5]
references: 
- http://collections.britishart.yale.edu/vufind/Record/1669236
- https://localhost:3000/catalog/1669236
- see email “vf bl field comparison”

features missing:
- heatmap (like vufind map view) (solr fields) https://github.com/sul-dlss/blacklight_heatmaps
- vufind lightbox search result has "type" as first metadata field (what is blacklight equivalent?)
- vufind sort has (Collection,title,date,genre,places represented, relevance), blacklight doesn't sort
- vufind has cas authenticate, blacklight just local (local:for non-Yale users)(rights v saved).
- blacklight: no email this search
- blacklight creator facet - author_ss vs auth_author (as in vufind)?
- blacklight slider, add range limit (date,height/width X type) fix lido for measurements type, solr int
- blacklight fix link field from vufind to bl
- vufind has citation Show | Text or SMS | Email, blacklight doesn't
- vufind has export RDF | XML, blacklight doesn't
- vufind has curatorial comment field, blacklight doesn't
- blacklight WIP to use vufind 5 sources for thumbnails

**Comment by mikeapp** [comment]
Issues that you start with:
* blacklight WIP to use vufind 5 sources for thumbnails
* vufind has curatorial comment field, blacklight doesn't  (should be in the index)
* vufind has export RDF | XML, blacklight doesn't
* blacklight fix link field from vufind to bl  (is this index data? if so, we can change there when going live.)
* blacklight creator facet - author_ss vs auth_author (as in vufind)? (yes)

**Comment by yulgit1** [comment]
TODO:
check out range limit gem for range of dates(earliest,latest) (conclusion: just earliest)
see email: catalog fields question
  add language note to show
  add type to facet
  earliest date and latest date should be a facet
  
citations and exports
Fix physical_height/width type in COBOAT
find examples to the add
Add to lido-vufind.xsl:
    Callnumber
    Curatorialcomment,author,date
    rightsURL
    citation
    videosURL
    isbn
add to marc-vufind-ycba.xsl
   form_genre
   marc_contents

Integer fields for range limit
    publishDate_ss
    earliestDate
    latestDate
    physical_heightValue
    physical_widthValue

reindex for language and all above
add all fields to catalog_controller
