### ISSUE TITLE
height width facet

### ISSUE THREAD

**Issue by yulgit1** [ycba-cia/blacklight-collections2#51]
physical_heightValue
physical_widthValue

populate this field with painting dimensions only (not frame dimensions)

**Comment by yulgit1** [comment]
This might be a coboat issue.  See email I sent in July:

"measurement facet in vufind and other things"

**Comment by edgartdata** [comment]
@EdwardTown1 @flapka @KraigBinkowski This seems to work. Can you spot check please?
