### ISSUE TITLE
"on view" facet and show

### ISSUE THREAD

**Issue by yulgit1** [ycba-cia/blacklight-collections2#52]
add this.

how to capture this? where to include this (rake)?

Ask David for TMS field indicating this.

**Comment by edgartdata** [comment]
@yulgit1 Great to see the Currently on view facet come to life in BlackLight!
Looks good. Can you confirm that the data you are working with is refreshed every day? B1974.3.7 was moved on monday from the 4th floor to storage but still appears in the 'on view' group.

**Comment by yulgit1** [comment]
@edgartdata - In production sounds like we should configure a nightly refresh so 'on view' is up to date.  But what we're looking at now is the development instance which is only refreshed when I run it.

**Comment by flapka** [comment]
@edgartdata @yulgit1 @EdwardTown1 

While appreciating the utility of the "currently on view" facet, Elisabeth is concerned that the label "currently on view" may inadvertently contribute to an under-appreciation that certain collections are also viewable in the Study Room. She thinks it'd be preferable to have a label along the lines of "On view in galleries" to make a clearer distinction. 

What do you all think about this suggestion?
