### ISSUE TITLE
form genre - missing subdivisions

### ISSUE THREAD

**Issue by yulgit1** [ycba-cia/blacklight-collections2#57]
In “Form Genre” (MARC 655) subdivision data is missing -- i.e. the data in subfields $x, $y, and $z. 

Example: https://ycba-collections-dev.herokuapp.com/catalog/2038446 

Form Genre

Atlases 
Atlases 
Engravings 
Engravings

should be 

Atlases -- England -- 1579. 
Atlases -- Wales -- 1579. 
Engravings -- 1579. 
Engravings -- Hand-colored -- 1579.

**Comment by yulgit1** [comment]
In index.rake get_marc_field method only returns subfield $a.  Create a new method to construct the subdivisions with $x, $y, $z

**Comment by yulgit1** [comment]
related to #42

**Comment by yulgit1** [comment]
@flapka What order should the subfields be? (for example it looks like 'y' should be last).

What subfields should be used? Looks like there is: a,b,c,v,x,y,z.

Between which terms to apply the " -- "?

**Comment by flapka** [comment]
Subfields b, c, v, though valid, are generally not used in 655 genre headings.

Which leaves these subfields, in this order:  a x z y

**Comment by yulgit1** [comment]
Need to find solution for that works for both art and biblio collections.

**Comment by yulgit1** [comment]
form_genre_ss
marc: custom method in index.rake concatenating subfields of 655
lido: currently not supported

**Comment by yulgit1** [comment]
fixed with https://github.com/ycba-cia/blacklight-collections2/commit/1217b31d18f56fa2049995eccc82d05caa572ed6
