### ISSUE TITLE
Subject terms - modify rendering

### ISSUE THREAD

**Issue by yulgit1** [ycba-cia/blacklight-collections2#58]
People as subjects (MARC 600) -- display of subfields

The “ -- “ symbol should only be generated to mark subfields v, x, y, and z (none of the other subfields ). 

Example: https://ycba-collections-dev.herokuapp.com/catalog/2038446 

Subject Terms

Elizabeth -- I, -- Queen of England, -- 1533-1603 -- Portraits.

[	$a Elizabeth $b I, $c Queen of England, $d 1533-1603 $v Portraits.	]

should render as

Elizabeth I, Queen of England, 1533-1603 -- Portraits.

**Comment by yulgit1** [comment]
for solr field: topic_ss

xslt does a basic concatenation based on:
<xsl:variable name="tags">600 610 611 630 650 651 653 690 692 693</xsl:variable>
<xsl:variable name="codes">abcdefghijklmnopqrstuvwxyz</xsl:variable>

need more sophisticated logic either in the xslt or in the rake task

**Comment by yulgit1** [comment]
fix (if all 6xxs)
```
<xsl:template name="topic">
        <xsl:variable name="tags">600 610 611 630 650 651 653 690 692 693</xsl:variable>
        <xsl:variable name="codes">abcdefghijklmnopqrstuvwxyz</xsl:variable>
        <xsl:variable name="codes_space">abcdefghijklmnopqrstuw</xsl:variable>
        <xsl:variable name="codes_dash">vxyz</xsl:variable>
        <xsl:for-each select="marc:datafield[contains($tags,@tag)]">
            <xsl:element name="topic_facet">
                <xsl:for-each select="marc:subfield[contains($codes,@code)]">
                    <xsl:value-of select="normalize-space(.)"/>
                    <xsl:if test="following-sibling::marc:subfield[position()=1][contains($codes_dash,@code)]">
                        <xsl:text> -- </xsl:text>
                    </xsl:if>
                    <xsl:if test="following-sibling::marc:subfield[position()=1][contains($codes_space,@code)]">
                        <xsl:text> </xsl:text>
                    </xsl:if>
                </xsl:for-each>
            </xsl:element>
            <xsl:element name="topic_t">
                <xsl:for-each select="marc:subfield[contains($codes,@code)]">
                    <xsl:value-of select="normalize-space(.)"/>
                    <xsl:if test="following-sibling::marc:subfield[position()=1][contains($codes_dash,@code)]">
                        <xsl:text> -- </xsl:text>
                    </xsl:if>
                    <xsl:if test="following-sibling::marc:subfield[position()=1][contains($codes_space,@code)]">
                        <xsl:text> </xsl:text>
                    </xsl:if>
                </xsl:for-each>
            </xsl:element>
        </xsl:for-each>
    </xsl:template>
```

**Comment by yulgit1** [comment]
fixed with

https://github.com/yulgit1/ybca_xslts/commit/819ab995825938f69cc30d6285e1b7afca444292

**Comment by edgartdata** [comment]
For the art collections, would it be possible to separate the subject terms with pipes, the way we do in Vufind?

**Comment by yulgit1** [comment]
Addressed in: https://github.com/ycba-cia/blacklight-collections2/commit/84b39219523cdbce27cfafb95bf735343b5d1fb5

**Comment by flapka** [comment]
@yulgit1 @edgartdata These pipes also show up at the end of the line for subject headings from MARC, where they are undesirable and unnecessary (since we already have line breaks). Can we remove them?

Example: http://10.5.96.187:3000/catalog/orbis:12924773

**Comment by flapka** [comment]
@yulgit1 

Currently a number of MARC fields map to "topic": 600 610 611 630 650 651 653 690 692 693

We want all of these to appear in the record display, but we only want some of them to appear in the subject facet. That is I want 600 610 611 630 650 651 653 to appear in the facet, but I don't want the facet to include 690 692 693. Would that be possible?
