### ISSUE TITLE
revise field labels

### ISSUE THREAD

**Issue by yulgit1** [ycba-cia/blacklight-collections2#60]
Field Labels

●	Form Genre: would be better as “Form / Genre”
●	“Imprint”: Not good for MS material. Prefer “published/created” (as in Orbis).
●	“Subject Terms – Current”: Why “- Current”?

**Comment by yulgit1** [comment]
@edgartdata why current?

**Comment by yulgit1** [comment]
@edgartdata more completely, is

Form / Genre v Form Genre
Published/Created v Imprint
Subject Terms v Subject Terms - Current

ok from lido?

**Comment by edgartdata** [comment]
We don't need Current for Subject Terms, I am not sure where this comes from.

**Comment by yulgit1** [comment]
addressed: https://github.com/ycba-cia/blacklight-collections2/commit/591c59acac9fb2ede184bc2f1451d51f09425677
