### ISSUE TITLE
add 264 to publisher field

### ISSUE THREAD

**Issue by yulgit1** [ycba-cia/blacklight-collections2#61]
264 (publication / creation). The data is not mapping to to the publication/creation field. 

Examples:
https://ycba-collections-dev.herokuapp.com/catalog/4172412 
https://ycba-collections-dev.herokuapp.com/catalog/3822506

Publication / creation data will come from either the 260 field or the 264 field. The current mapping grabs data only from the 260 field.

**Comment by yulgit1** [comment]
@flapka All subfields of 264? Or just subfield a? Including punctuation?

<marc:datafield tag="264" ind1=" " ind2="0">
<marc:subfield code="a">England,</marc:subfield>
<marc:subfield code="c">not before 1787.</marc:subfield>
</marc:datafield>

<marc:datafield tag="264" ind1=" " ind2="1">
<marc:subfield code="a">Philadelphia :</marc:subfield>
<marc:subfield code="b">Samuel C. Upham, 310 Chesnut Street, Phila.,</marc:subfield>
<marc:subfield code="c">1861.</marc:subfield>
</marc:datafield>

**Comment by flapka** [comment]
Yes, all subfields of 264 (a, b, and c), retaining punctuation. 

Some records will include multiple 264 fields (with varying indicator fields). In this situation, all the 264 fields should appear too. For example:

264 _1 $a London : $b Penguin, $c 2004.
264 _4 $a Edinburgh : $b Some Printer.

We'd want this to display as:

Imprint:  London : Penguin, 2004.
               Edinburgh : Some Printer.

For some material (unpublished resources), only a date will appear -- which is fine. E.g.:

264 _0 $c 1810.

**Comment by yulgit1** [comment]
addressed:
https://git.yale.edu/ermadmix/ycba_xslts/commit/a6cbb57c455df538cc31ec55398eb0da6f211dc8

**Comment by flapka** [comment]
@yulgit1 
Yes, that's good.

The next step is to make sure that handling of multiple 264 fields (in one record) works properly. Here's an example in Orbis: http://hdl.handle.net/10079/bibid/11915282 

The corresponding record in Test doesn't show the 264 fields yet:
http://10.5.96.187:3000/catalog/orbis:11915282

**Comment by flapka** [comment]
PS. I don't have access to the link you provided earlier (https://git.yale.edu/ermadmix/ycba_xslts/commit/a6cbb57c455df538cc31ec55398eb0da6f211dc8). I get a 404 error.

**Comment by yulgit1** [comment]
@flapka, I've tested only a handful of records that's why you don't see it. Just ran it for 11915282, please see now it looks ok:

http://10.5.96.187:3000/catalog/orbis:11915282

If clear, next step is to reindex everything.

**Comment by yulgit1** [comment]
same issue mentioned in: https://github.com/ycba-cia/blacklight-collections2/issues/87

**Comment by yulgit1** [comment]
The 264c can be added such as the:

"not before 1787."
in
https://libapp.library.yale.edu/OAI_BAC/src/OAIOrbisTool.jsp?verb=GetRecord&identifier=oai:orbis.library.yale.edu:12700818&metadataPrefix=marc21

But we were also going to use this field for a slider facet, requiring 'yyyy' format.  This will break this.  It's definitely necessary to add the 264c to have some kind of publishDate, but the facet has to be a list and not a slider unless this gets normalized.

 @flapka what do you think?

**Comment by flapka** [comment]
On the question of faceting date, see issue #83. This is probably something we should discuss in person to avoid confusion? 

As for display 264 data in the item views: this is close to fixed. One problem: when the date is mapped from 264 subfield $c, it looks like it's showing up twice.
* simple example: http://10.5.96.187:3000/catalog/orbis:13243962
* example with repeating 264 fields: http://10.5.96.187:3000/catalog/orbis:11915282

In that 2nd example (repeating 264), the treatment is correct until the repeated dates. I.e., it should read: "A Paris : Chez Bulla, éditeur, Rue Saint-Jacques, no. 38, 1828. Paris : Imprimerie de A. Belin, rue des Mathurins S.-J., n. 14, [1828]"

@edgartdata The imprint above is an example of an item for which we have a *publication* statement and a *manufacture (printing)* statement. In the original MARC data they are distinguished by an indicator code. For art collections, is there any desire to make such a distinction -- i.e., to separate fields in the YCBA catalog? If not, there's no great harm in the status quo -- lumping it all in as generic publication ("imprint") data.

**Comment by yulgit1** [comment]
@flapka - fixed repeating 264c, ok to close?

**Comment by flapka** [comment]
Almost fixed. One tiny glitch remains: Blacklight displays the word "and" between the repeated 264. 

For example, Blacklight gives: "A Paris : Chez Bulla, éditeur, Rue Saint-Jacques, no. 38, 1828. **and** Paris : Imprimerie de A. Belin, rue des Mathurins S.-J., n. 14, [1828]"

Should be: "A Paris : Chez Bulla, éditeur, Rue Saint-Jacques, no. 38, 1828. Paris : Imprimerie de A. Belin, rue des Mathurins S.-J., n. 14, [1828]"

**Comment by yulgit1** [comment]
Used line separator rather than "and" for Imprint concatenation
Addressed in https://github.com/ycba-cia/blacklight-collections2/commit/82a81883a69d893f6ebe6fe59e3415a8adea9def

@flapka ok to close?

**Comment by flapka** [comment]
Yes, the line separator is the best possible treatment. Looks great!

*But* now we're missing the pubication date (at end of Imprint) when it maps from 260 subfield $c. Two examples:
* http://10.5.96.187:3000/catalog/orbis:9782277
* http://10.5.96.187:3000/catalog/orbis:9854526

Sorry for the thorniness.
