### ISSUE TITLE
missing scale data

### ISSUE THREAD

**Issue by yulgit1** [ycba-cia/blacklight-collections2#62]
Scale data is absent (MARC field 255) -- we need to add it to the mapping (not exactly a Blacklight issue).

Examples: 
https://ycba-collections-dev.herokuapp.com/catalog/2038446 
https://ycba-collections-dev.herokuapp.com/catalog/2038921

**Comment by yulgit1** [comment]
@flapka What should label of this field be?

**Comment by flapka** [comment]
Yes, 'Scale' would be perfect.

**Comment by yulgit1** [comment]
@flapka Are we just capturing scale (subfield 'a'), or other 255 subfields as well (projections, coordinates ,etc).

**Comment by flapka** [comment]
Good catch Eric. I misspoke above. 

Yes, we do want to map all subfields of 255. Though we could map each subfield to a separate field (for scale, projection, coordinates), I think it would be sensible to use a single field for the mapping -- and label it "Cartographic detail" as YUL does in Orbis/Quicksearch.

**Comment by flapka** [comment]
@yulgit1 @edgartdata 

Two possible resolutions:
1. Create a new field in our index for scale information, from MARC 255.
2. Map 255 as another note (=description). 

The 2nd is probably easier, and I think it'd be okay.

**Comment by yulgit1** [comment]
reindexed over weekend, scale added, ok @flapka?

http://10.5.96.187:3000/catalog/orbis:9574422
http://10.5.96.187:3000/catalog/orbis:9579023

**Comment by flapka** [comment]
Very good. *If possible* it would be better for this field to appear high up. Preferred location would be right before the notes field (after the link to the Orbis record).

**Comment by yulgit1** [comment]
@flapka OK, moved Scale to right below Notes

**Comment by flapka** [comment]
@yulgit1 Sorry, just *above* notes.

**Comment by yulgit1** [comment]
@flapka sorry, corrected to _above_
