### ISSUE TITLE
missing marc 351, should be in Notes

### ISSUE THREAD

**Issue by yulgit1** [ycba-cia/blacklight-collections2#63]
MARC field 351 is not mapping. The field is used to record information about how a collection is organized, such as:

The collection is divided into three series: I. Albums and sketchbooks; II. Writings; III. Correspondence.

The collection is arranged into four series: I. Theatre Programs and Clippings; II. Designs By Production; III. Designs By Era; IV. Designs By Subject. Folders are arranged alphabetically by production (Series I and II) or topic (Series III and IV).

Examples (where the data is missing):
https://ycba-collections-dev.herokuapp.com/catalog/3738852
https://ycba-collections-dev.herokuapp.com/catalog/3362408

It would be fine to map 351 data to the field labeled as Notes (I think it’s called “Description” in the index).

https://www.loc.gov/marc/bibliographic/bd351.html

**Comment by yulgit1** [comment]
off: solr field: 'note' doesn't appear in the xslt, where is it coming from?

**Comment by yulgit1** [comment]
From the xslt (we could do something similar to map to 351,as description=note):

    <xsl:template name="description">
        <xsl:variable name="exceptions">505 506 524 540 546</xsl:variable>
        
        
        
        
        <xsl:for-each
            select="marc:datafield[starts-with(@tag,'5')][not(contains($exceptions,@tag))]">
            <xsl:element name="description_t">
                <xsl:for-each select="marc:subfield">
                    <xsl:value-of select="normalize-space(.)"/>
                    <xsl:if test="following-sibling::marc:subfield">
                        <xsl:text> </xsl:text>
                    </xsl:if>
                </xsl:for-each>
            </xsl:element>
        </xsl:for-each>
    </xsl:template>

**Comment by flapka** [comment]
@yulgit1 Yes, it would be perfectly fine to map 351 as another note (=description).

**Comment by yulgit1** [comment]
@flapka any subfield of 351? or just subfield b? or something else?

**Comment by flapka** [comment]
@yulgit1 With the way that we use the 351 field, I believe 100% of the data will be in subfield $a. But there's no harm in mapping from all of the 351 subfields -- so let's go ahead and do so.

**Comment by yulgit1** [comment]
Reindexed over the weekend. Example: http://10.5.96.187:3000/catalog/orbis:9720841

@flapka ok?

**Comment by flapka** [comment]
Yes, looks resolved. Thanks!
