### ISSUE TITLE
image rights not mapped correctly - 506 540

### ISSUE THREAD

**Issue by yulgit1** [ycba-cia/blacklight-collections2#64]
Field 506 (Restrictions on access)

The data is currently (mis-)mapping to a field concerning rights. The data in 506 is more about physical access restrictions. Example data:

Restricted fragile material. Use requires permission of the Curator of Rare Books and Manuscripts.

The collection is open without restriction.

Example records (where the data displays in the right-hand part of the screen, where images would be):

https://ycba-collections-dev.herokuapp.com/catalog/3362408
https://ycba-collections-dev.herokuapp.com/catalog/3738852

**Comment by yulgit1** [comment]
Currently pulling from 506 and 540.  @flapka what should this be?

<xsl:template name="rights">
...
   <xsl:for-each select="marc:datafield[@tag='506']|marc:datafield[@tag='540']"
   <xsl:for-each select="marc:subfield[@code!='0']">

**Comment by flapka** [comment]
Eric, can you tell me what field in the YDC2 index this correspond to? (https://docs.google.com/spreadsheets/d/1bKLmImNZvmQITCAZV9q_sU1T8WdPC8UP4C5D06RT8Aw/edit?ts=56e089a1#gid=1624739779)

*If* it corresponds to image_restrictions, then we don't record this data in MARC (rather, it's in the corresponding Media Manager record). But let me know if we're talking about another YDC2 field.

**Comment by yulgit1** [comment]
Based on the lido xpath, this field maps to “object_copyright_holder”.

**Comment by flapka** [comment]
The image rights issue is complicated.

But I don't want to lose sight of the original concern here -- which is about physical access to objects (in the Study Room), not rights.

The physical access information (MARC 506) can be mapped to description (note).

**Comment by yulgit1** [comment]
action:
map 506 to description (note), not rights

**Comment by flapka** [comment]
@yulgit1 Omit 540 from the description mapping. For the moment we don't use the 540 field. But we *may* eventually use it to map to image_use_uri and image_restrictions -- pending additional discussions with Melissa et al.

**Comment by yulgit1** [comment]
current status of this:

506 mapped to description (note) only
540 unused

@flapka @edgartdata - OK?

**Comment by flapka** [comment]
@yulgit1 Correct. Thanks!
