### ISSUE TITLE
how to handle citations

### ISSUE THREAD

**Issue by yulgit1** [ycba-cia/blacklight-collections2#65]
Field 524 -- an uncommonly used field that records how to cite an item -- appears to be mapping to a field labeled “Publications” in Blacklight.

Example:

https://ycba-collections-dev.herokuapp.com/catalog/2035501 
https://ycba-collections-dev.herokuapp.com/catalog/2038541 

The appropriate label would be “Cite as.” The same data (524) doesn’t display in the YCBA Vufind catalog.

**Comment by yulgit1** [comment]
Can simply change label from "Publications" to "Cite as".  However lido documents use "Publications" for the metadata:

REXML::XPath.each(xml, '//lido:relatedWorkSet/lido:relatedWork/lido:displayObject') { |citation|

@edgartdata Does changing the label break the lido convention?

**Comment by yulgit1** [comment]
Don't think changing "Publications" to "Cite As" works for lido.  For lido "Publications" this field seems to be used to often display a large list of related works, not a citation of the specific item:

http://10.5.96.187:3000/catalog/tms:5005

One suggestion, suppress Marc for this field (as it's uncommon).

Thoughts @flapka @edgartdata @KraigBinkowski ?

**Comment by yulgit1** [comment]
Another suggestion, have a Marc only "Cite As" field mapping to the citation.

**Comment by flapka** [comment]
Two part answer, for two different issues. Part one:

The MARC 524 field is not equivalent to our Blacklight Publications (citations_ss) field, so we should definitely not map it in there. Instead, two options:
1. Create a new MARC-only (?) "Cite as" field, as Eric suggests immediately above, and map it to MARC 524.
2. Don't map the 524 field (not the end of the world).

I prefer option 1.

**Comment by KraigBinkowski** [comment]
I am fine with either option that Francis outlines above.

**Comment by flapka** [comment]
@edgartdata @EdwardTown1 @yulgit1 @KraigBinkowski Issue / answer, part 2. 

MARC records do have data that is roughly equivalent to what art collections map to the Publications field. It's in MARC field 510. Currently, this data is one of many fields that map to the general "Notes" field. 

See for example: http://10.5.96.187:3000/catalog/orbis:9412224

That record has three citations to publications:

- ESTC, T110280
- British Architectural Library. Early printed books, 553
- Lowndes, v. 1, p. 346

You'll notice that the data is quite abbreviated, compared to what we have for art collections. And MARC data we'll never have as many citations as the Miss Prue example referenced above.

It would be logical to map this MARC field to Publications, but I think library stakeholders wouldn't want the data to be masked behind a double-click on-off toggle, as we currently have. 

Should we pose the question to Elisabeth and Matthew on the 9th?

**Comment by KraigBinkowski** [comment]
We also would want to think about a consistent user experience. I'm not sure the data from the MARC field 510 will make much sense to users in the way that the TMS publications module provides a full and clear citation.
