### ISSUE TITLE
map field 542 correctly

### ISSUE THREAD

**Issue by yulgit1** [ycba-cia/blacklight-collections2#66]
Field 542: Copyright status (of the work)

This field should not map to Notes (description). Subfield $l should map to 
object_copyright_status. Subfield $u should map to rights_resource object_copyright_status_url (provided we are still using these fields in our index). Check with Melissa?

Examples:

https://ycba-collections-dev.herokuapp.com/catalog/2035078 
https://ycba-collections-dev.herokuapp.com/catalog/2031741 

(We don’t want the data to display, in this form at least.)

**Comment by yulgit1** [comment]
Again, cannot find the source of the 'note' field, see also: https://github.com/ycba-cia/blacklight-collections2/issues/63

Neither is there an object_copyright_status and object_copyright_status_url for  $I, $u.  Should new fields be created?

**Comment by yulgit1** [comment]
Possibly related, LIDO creates the following fields, for use in the rights (see #64) as displayedon the right hand side of show page:

ort = REXML::XPath.first(xml, '//lido:rightsWorkSet/lido:rightsType/lido:conceptID[@lido:type="object copyright"]')

rightsURL = REXML::XPath.first(xml, '//lido:legalBodyID[@lido:type="URL"]')

As in the helper method:
https://github.com/ycba-cia/blacklight-collections2/blob/master/app/helpers/application_helper.rb#L71

**Comment by yulgit1** [comment]
actions todo (to confirm): 
exclude 542 from description (aka 'notes')
map 542l to rights_txt (see helper method above)
map 542u to rightURL_ss (see helper method above)

**Comment by flapka** [comment]
@yulgit1 @edgartdata 

Here are the mappings that pertain to the 542 field:
https://docs.google.com/spreadsheets/d/1JcsuJJWXyMBXzBcHJ7NKQkelSqbTTzbm9KhSdJbr2H0/edit#gid=652809212

As far as I know, this XSLT will have to be written from scratch. The existing XSLT for the "rights" field -- which I'm copying below -- is *all wrong*. Let me know if you have questions.

    <xsl:template name="rights">
        <xsl:for-each select="marc:datafield[@tag='506']|marc:datafield[@tag='540']">
            <xsl:element name="rights">
                <xsl:attribute name="analyze">false</xsl:attribute>
                <xsl:attribute name="store">true</xsl:attribute>
                <xsl:for-each select="marc:subfield[@code!='0']">
                    <xsl:value-of select="normalize-space(.)"/>
                    <xsl:if test="following-sibling::marc:subfield">
                        <xsl:text> </xsl:text>
                    </xsl:if>
                </xsl:for-each>
            </xsl:element>
        </xsl:for-each>
    </xsl:template>

**Comment by yulgit1** [comment]
current status of this:

1) 'rights' field for 506 and 540 eliminated 
2) 542 excluded from description
3) 542i = ort_ss
4) 542u = rightsURL_ss
5)  542d, 542f not mapped to any Solr field

@flapka @edgartdata - OK?

**Comment by flapka** [comment]
@yulgit1 @edgartdata 

1. rights' field for 506 and 540 eliminated
- Yes, 506 instead maps to description. 540 is in holding pattern

2. 542 excluded from description
- Yes

3. 542i = ort_ss
- Danger of sans-serif fonts. should be 542 L 

4. 542u = rightsURL_ss
- Yes

5. 542d, 542f not mapped to any Solr field
- Does this mean that the Solr fields dont' exist yet, but will at some point?

My Solr field name references are out of date, I think. Could you point me to a list of the current field names?

**Comment by mxgold** [comment]
@flapka can you point us to a couple of RBMS records with images for which the 542 and other fields are populated, which we can refer to for testing purposes?

**Comment by flapka** [comment]
@mxgold @yulgit1 
Short answer: I just updated three records with sample data. They can serve as examples as soon as they are reindexed.

Longer answer:

* Public domain example: http://10.5.96.187:3000/catalog/orbis:9292982 -- Until a moment ago, the 542 for this record said: 542 0_ ‡d public domain ‡l public domain ‡q CtY-BA ‡u http://hdl.handle.net/10079/w6m90dq -- I've just edited this to make more correct (?): 542 0_ ‡f Public Domain ‡l public domain ‡q CtY-BA ‡u http://id.loc.gov/vocabulary/preservation/copyrightStatus/pub

* "Unknown" example: http://10.5.96.187:3000/catalog/orbis:3505631 -- Until a moment ago, this had flawed 542 data too. -- I've just updated it to: 542 0_ ‡f Copyright Unknown ‡l unknown ‡q CtY-BA ‡u http://id.loc.gov/vocabulary/preservation/copyrightStatus/unk

* Copyrighted example: http://10.5.96.187:3000/catalog/orbis:12838319 -- Until a moment ago, this did not have a 542 field. -- I've just added: 542 0_ ‡d St. John Ambulance Association ‡f Copyright St. John Ambulance Association ‡l copyrighted ‡q CtY-BA ‡u http://id.loc.gov/vocabulary/preservation/copyrightStatus/cpr

I recognize that my 542 usage may still be imperfect. And these aren't veritable copyright assessments.

**Comment by yulgit1** [comment]
@flapka - I will reindex soon, but what should be the mappings?

We have 
542l - ort_ss - (below image)
542u - rightsURL_ss (the link when clicking on ort_ss above)

What should be fieldname and display label for 542d 542f: (assuming they'll go in tombstone data?):

**Comment by flapka** [comment]
@yulgit1 @mxgold 

Of these four fields, I believe that only 542 $f should display (below the image) -- where it appears without a label. The three others are invisible. Is that right @mxgold ?

As for field names, I defer again to @mxgold 

For the 542 $u, I assume we don't want to link to id.loc.gov (not user friendly). @mxgold ?

**Comment by yulgit1** [comment]
@flapka - from above seems like your saying ort_ss (below image) to be 542f rather the 542l?

Looking at one sample record however, and it doesn't have 542f:
https://orbis.library.yale.edu/vwebv/staffView?bibId=9049663

Just checking in before moving on this.

Should we just keep using 542l?

**Comment by flapka** [comment]
@yulgit1 @mxgold Sorry, record 9049663 has incomplete data (my doing), so it's a misleading example.

Yes, do map the info that displays from 542 subfield $f.

We also want the the displayed info to become a hyperlink to YCBA pages with rights pages, in the same way that we do with art collections. The destination URL should be determined by the value in 542 subfield $L.

So:
* if $L = "public domain" then use URL http://hdl.handle.net/10079/w6m90dq 
* if $L = "unknown" or "undetermined" then use URL http://hdl.handle.net/10079/c59zwbm
* if $L = "copyrighted" or "in copyright" or "under copyright" then use http://hdl.handle.net/10079/1rn8pss

I'm giving 'or' options above because we're still mulling over the best terminology.

**Comment by yulgit1** [comment]
@flapka 
Currently the URL is coming from $U, you're asking to replace with the above $L mappings instead?

**Comment by flapka** [comment]
Correct. The data in subfield $u currently serves no purpose (but maybe it will down the road).
