### ISSUE TITLE
suppress subfield 5, is displaying in note field 

### ISSUE THREAD

**Issue by yulgit1** [ycba-cia/blacklight-collections2#67]
Subfield $5 (all fields)

Data in subfield $5 (usually a code, like “$5 CtY-BA”) should never display to the public – so probably we shouldn’t map it.

Example: https://ycba-collections-dev.herokuapp.com/catalog/4357062

**Comment by yulgit1** [comment]
#63 #66

Another issue with the 'note' field, the source of which is not in the xslt or ruby indexing.

**Comment by yulgit1** [comment]
From the xslt (we could do something similar to suppress 5):

<xsl:template name="description">
    <xsl:variable name="exceptions">505 506 524 540 546</xsl:variable>
    
    
    
    
    <xsl:for-each
        select="marc:datafield[starts-with(@tag,'5')][not(contains($exceptions,@tag))]">
        <xsl:element name="description_t">
            <xsl:for-each select="marc:subfield">
                <xsl:value-of select="normalize-space(.)"/>
                <xsl:if test="following-sibling::marc:subfield">
                    <xsl:text> </xsl:text>
                </xsl:if>
            </xsl:for-each>
        </xsl:element>
    </xsl:for-each>
</xsl:template>

**Comment by mikeapp** [comment]
Problem exists in Vufind

**Comment by flapka** [comment]
Thanks @yulgit1 .  Is there an easy way to suppress subfield 5 in *all* MARC fields, instead of just the note fields? This would be the desired outcome. 

If there is no easy way to apply the suppression to all fields, I can come up with a list of those that are pertinent (e.g. 655, 700, 710 ...). Let me know.

**Comment by yulgit1** [comment]
Thanks, yes a list would be helpful.

Eric James
Software Engineer
Yale Center for British Art
1080 Chapel Street, PO Box 208280
New Haven, CT  06520-8280
203-432-9411 | britishart.yale.edu<http://britishart.yale.edu/>

Connect on Facebook<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.facebook.com%2FYaleBritishArt%2F&data=02%7C01%7C%7Cb23f54690a84422ff97408d5d077ae34%7Cdd8cbebb21394df8b4114e3e87abeb5c%7C0%7C0%7C636644134820829805&sdata=3b6f7bUzT7uOAQRAbTbVob9umFnn6ot6a2mjD%2Bpa5bI%3D&reserved=0>, Twitter<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Ftwitter.com%2FYaleBritishArt&data=02%7C01%7C%7Cb23f54690a84422ff97408d5d077ae34%7Cdd8cbebb21394df8b4114e3e87abeb5c%7C0%7C0%7C636644134820829805&sdata=XGiW2XUJSkCn6W%2BAzjckD3qTPm6Rc68fX%2FEk23Ki7Ag%3D&reserved=0>, Instagram<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.instagram.com%2Fyalebritishart%2F&data=02%7C01%7C%7Cb23f54690a84422ff97408d5d077ae34%7Cdd8cbebb21394df8b4114e3e87abeb5c%7C0%7C0%7C636644134820829805&sdata=3lugHcpUUutFEA709RhWg6Chs2gnnvJYGuYCEETQvuw%3D&reserved=0>, YouTube<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.youtube.com%2Fyalebritishart&data=02%7C01%7C%7Cb23f54690a84422ff97408d5d077ae34%7Cdd8cbebb21394df8b4114e3e87abeb5c%7C0%7C0%7C636644134820829805&sdata=vokg9vVVT6sRZdxsUfjMgFzfcxyRNX7pPxbaFYPD4JI%3D&reserved=0>, and Snapchat @yalebritishart #YCBA

ON VIEW
Before the Deluge: Apocalyptic Floodscapes from John Martin to John Goto, 1789 to Now<https://britishart.yale.edu/exhibitions/deluge-apocalyptic-floodscapes-john-martin-john-goto-1789-now>
December 18, 2018–March 24, 2019
Instruction and Delight: Children’s Games from the Ellen and Arthur Liman Collection<https://britishart.yale.edu/exhibitions/instruction-and-delight-childrens-games-ellen-and-arthur-liman-collection>
January 17–May 23, 2019
Victorian Idyll<https://britishart.yale.edu/exhibitions/victorian-idyll>
January 24–April 21, 2019
UP NEXT
William Hunter and the Anatomy of the Modern Museum<https://britishart.yale.edu/exhibitions/william-hunter-and-anatomy-modern-museum>
February 14–May 20, 2019

**Comment by yulgit1** [comment]
@flapka - suppressed subfield 5 in description and author_additional, genre includes only subfields abvxyz so no change is needed there

**Comment by flapka** [comment]
Great.

**Comment by flapka** [comment]
Looks fixed! Can close.
