### ISSUE TITLE
suppress 856 when it is the current blacklight record (itself)

### ISSUE THREAD

**Issue by yulgit1** [ycba-cia/blacklight-collections2#68]
Field 856: Electronic links

The current mapping isn’t strictly wrong, but we would like to modify it. We would like to exclude links of this variety (which are intended to take people from Orbis to the YCBA’s catalog):

View a digitized version of this item in the Yale Center for British Art's online catalog

Example:
https://ycba-collections-dev.herokuapp.com/catalog/2038962 

Obviously it doesn’t make sense for that link to display when the user is already looking at the record in the YCBA catalog. Perhaps we could apply a code to this variety of 856 that would tell the mapping to exclude the field.

**Comment by yulgit1** [comment]
We could use string manipulation to suppress like this.  However, in looking at the example above, the link is to the current dev host (ycba-collections-dev), however the link is actually still vufind if you look from the record itself.  Is this a separate issue to reindex the 856s?

**Comment by mikeapp** [comment]
It's odd that when I hit that ID in production it's a broken detail page and not a 'not found'. 
Handles would work but we'd need a system to keep them in sync.

**Comment by yulgit1** [comment]
Maybe the 856 for this one is just wrong.  Also I get no hits on 'Vinters in Kent' in vufind.

**Comment by flapka** [comment]
RB colleagues and I have noticed that certain items have recently gone missing from our Vufind catalog. Could it be that the presence of the 856 data has something to do with it? For example, records for the following are now missing in Vufind (there are probably others too?):

Vinters in Kent ...: https://ycba-collections-dev.herokuapp.com/catalog/2038962 

Helmingham herbal ...: https://ycba-collections-dev.herokuapp.com/catalog/2038220

Record books (Roberts):  https://ycba-collections-dev.herokuapp.com/catalog/2038554

Album of drawings of English moths:  https://ycba-collections-dev.herokuapp.com/catalog/2037865

**Comment by yulgit1** [comment]
opened ticket #71 for missing records

**Comment by yulgit1** [comment]
this ticket resolved by
https://github.com/ycba-cia/blacklight-collections2/commit/bb0bacfeec2b6109d970845e2bb141ced72ec25f

**Comment by flapka** [comment]
@yulgit1 Can we modify the XSLT to omit (not map) any 856 field that contains the following string in 856 subfield $y: 

View a selection of digital images in the Yale Center for British Art's online catalog

Here's an example:
http://ycba-collections-dev.herokuapp.com/catalog/orbis:9452785

This kind of 856 serves to point researchers from Orbis/Quicksearch to the YCBA catalog. When a researcher is already in the YCBA catalog, the link is circular. 

Thanks!

**Comment by yulgit1** [comment]
@flapka As the xslt is now, it is pulling either 856 subfields $y OR $3 OR $z as a label, and subfield $u as the link. So if $y is suppressed I assume exclude the $u as well? (leaving $3 OR $z paired to be paired with $u).  Or should the entire 856 not be indexed?

**Comment by flapka** [comment]
@yulgit1 The latter: when the 856 contains that string, omit that 856 instance altogether (all subfields). Thanks.

**Comment by yulgit1** [comment]
addressed:
https://github.com/ycba-cia/blacklight-collections2/commit/825f0f2be97e9fa9f5536eac00a80508141011b8

**Comment by flapka** [comment]
@yulgit1 Based on review of a small sample size, this issue looks fixed. Thanks!
