### ISSUE TITLE
translate fabrique look and feel to blacklight

### ISSUE THREAD

**Issue by yulgit1** [ycba-cia/blacklight-collections2#75]

**Comment by miriamschroers** [comment]
Header- remove search, modify menu to link back to main site, keep logo which links back to main site
Footer- translate footer as is design

**Comment by miriamschroers** [comment]
// Base colors

$color-black: #000;

$color-white: #fff;

$color-grey: #d7d6d8;

$color-grey-darker: #474747;

$color-grey-lighter: #e6e6e6;

 

// New activity colors

$color-activities: (

  exhibition: #9cd3ff, // blue

  talk: #b094ff, // purple

  conference: #ff76ad, // pink

  tour: #ffb968, // orange

  film: #ffd506, // yellow

  performance: #ff6b5e, // red

);

 

// Warm greys (brown)

$color-warm-lightest: #faf8f5;

$color-warm-lighter: #f9f1e7;

$color-warm-light: #f4e3cb;

$color-warm-dark: #e1ba8b;

$color-warm-darker: #7c5420;

$color-warm-darkest: #3d2502;

 

// Cool greys (blue)

$color-cool-lightest: #f9f9fc;

$color-cool-lighter: #e7eaec;

$color-cool-light: #c9ced1;

$color-cool-dark: #8e9397;

$color-cool-darker: #454b52;

$color-cool-darkest: #272c30;

**Comment by miriamschroers** [comment]
Miriam will show design the Fabrique and YCBA web team next week (March 4/5)

**Comment by edgartdata** [comment]
Eric to check if the header padding could be smaller on the vertical
