### ISSUE TITLE
Distinguish between the 2 credit lines for art collections/LIDO

### ISSUE THREAD

**Issue by edgartdata** [ycba-cia/blacklight-collections2#79]
Object ownership credit line:
lido:rightsWorkSet[lido:rightsType/lido:conceptID/@lido:type='object ownership’]/lido:creditLine
Goes to the credit line field in the tombstone info

Object copyright:
lido:rightsWorkSet[lido:rightsType/lido:conceptID/@lido:type='object copyright']/lido:creditLine
Displays beneath the image and links to one of 3 rights handles

**Comment by flapka** [comment]
@edgartdata 
Seem straight forward.

For object ownership credit line, this means something like: "Yale Center for British Art, Paul Mellon Collection" -- which maps to credit_line_facet, credit_line_ss, and credit_line_txt (?). For library material, this has no direct equivalent yet, though we could explore mapping it from MARC 541 $a.

For object copyright, we have example values such as "Public Domain" or "Estate of ..." -- and this field hasn't been implemented in Blacklight yet (not here at least: https://docs.google.com/spreadsheets/d/1GfXyerqmOWY1SRfH6QJRCISUfXWuIHw67FC4gg8co8Q/edit#gid=1042493725)? In our Vufind table, we proposed it as "object_copyright_notice". For library material the equivalent is MARC 542 $f -- though we haven't recorded such data so far.

Is this all correct?

**Comment by yulgit1** [comment]
lido:
object ownership credit line -> credit_line_ss (tombstone)
object copyright credit line -> ort_ss (below images)
object copyright term - > rights_ss (facets)

marc:
(not implemented, 541a) -> credit_line_ss (tombstone)
542l ->ort_ss (below images) (almost all unknown)
542l ->rights_ss (facets) (almost all unknown)

**Comment by mxgold** [comment]
@yulgit1 @flapka from my examination, issues resolved.  I have a closely related display question which requires group feedback - should I loop it into this issue before closing, or close this issue and open a new one? (github newbie!)

**Comment by yulgit1** [comment]
@mxgold - I'll close this one now.  
Yes, open a new issue and add it to the milestone batch 1, thanks.
