### ISSUE TITLE
Weighing search results

### ISSUE THREAD

**Issue by edgartdata** [ycba-cia/blacklight-collections2#80]
Decide which metadata schema fields to take into consideration to weigh search results

Go through the SOLR index, check that we have all the fields necessary, 

Need to indicate what needs to be a facet versus what needs to be shown in a record.

**Comment by edgartdata** [comment]
I know there are several questions (above) to take into consideration for this issue, but overall the search results need to be sorted the same way as the Collection facet:
- P&S
- P&D
- Rare Books & Manuscripts
- Reference Library
- Frames

**Comment by edgartdata** [comment]
@yulgit1 Same as #97 Sorry!

**Comment by flapka** [comment]
@edgartdata @yulgit1 

Library colleagues agree with this sort order. By July 1, however, we may also have Institutional Archives records in Blacklight. In that case, we propose this order:

* P&S
* P&D
* Rare Books & Manuscripts
* Institutional Archives
* Reference Library
* Frames

**Comment by flapka** [comment]
@edgartdata @yulgit1 

The above sort order is desirable assuming that we modify the Blacklight search functionality so that an implied AND Boolean operator is inserted on searches of multiple terms -- which is what we have had in our Vufind catalog.

Currently our Blacklight search uses an implied OR Boolean operator, with search results sorted by records that match the most terms. If we were to maintain the implied OR -- which YCBA libraries find undesirable -- then the collection order preference described above would be have to be subordinate to the number of search terms matched.

**Comment by edgartdata** [comment]
@flapka @EdwardTown1 I agree that the default Boolean operator when using more than one search criteria (2 subject tags for example).

**Comment by edgartdata** [comment]
@flapka Great to hear that our Institutional Archives are on track to join the YCBA cross-collection catalog!

**Comment by yulgit1** [comment]
For ordering of collections, it should be possible to boost rankings based on field value:
https://www.programcreek.com/java-api-examples/?class=org.apache.solr.common.SolrInputDocument&method=setDocumentBoost

For search operator, the solr query parser has a mm function that if set to 100% will ensure all search terms must be present (equivalent to boolean AND):

https://lucene.apache.org/solr/guide/6_6/the-dismax-query-parser.html

**Comment by edgartdata** [comment]
Weighing search results criteria:
- collection (see above)
- imaged records 
- fully attributed works first (and works after, studio of, in the style of... later at the end)

@flapka Any preferences from your collection?

**Comment by flapka** [comment]
Good questions. After the requirements mentioned above, RB would probably like to give base ordering on where the terms appear in a record. That is, prioritize by matches in these fields, in this order:
* auth_author
* title
* topic
* contributor
* anywhere else

If it's feasible to implement such a preference, I'd like to discuss this more with library colleagues for their thoughts.

**Comment by edgartdata** [comment]
I think the same would work well for the art collections, at least for the 3 first elements:

- creator
- title
- topic

**Comment by yulgit1** [comment]
for current config (assuming ongoing tweaking):

https://github.com/ycba-cia/blacklight-collections2/wiki/blacklight-collections2-solr-config-notes

**Comment by edgartdata** [comment]
This sorting on departments should take precedent over all other sorting logic:
P&S
P&D
Rare Books & Manuscripts
Reference Library
Frames

**Comment by KraigBinkowski** [comment]
I would also include Institutional Archives in the departmental sort


P&S
P&D
Rare Books & Manuscripts
Institutional Archives
Reference Library
Frames
Kraig

**Comment by flapka** [comment]
I agree with @KraigBinkowski on the position of IA in the search results ordering. This order is the same as what we've agreed upon already for preferred order in the Collection facet.

**Comment by edgartdata** [comment]
Meeting with @EdwardTown1 @yulgit1 @flapka @KraigBinkowski @edgartdata on 4/16 from 3-5pm.

**Comment by edgartdata** [comment]
Additional field to sort by department:

A; P&S
B: P&D
C; Rare Books & Manuscripts
D: Institutional archives 
E: Reference Library
F: Frames

This is the first boost factor before anything else.

**Comment by edgartdata** [comment]
In addition to the boosting per department, add 3 sort options:
- Date (ascending order)
- Title  (ascending order)
- Relevance (default)

**Comment by edgartdata** [comment]
Eric implemented the 3 sort options mentioned above.
