### ISSUE TITLE
Download display

### ISSUE THREAD

**Issue by edgartdata** [ycba-cia/blacklight-collections2#81]
Do we want to keep the download pop-up menu as it is in Vufind?
If not, what are  our options?

**Comment by edgartdata** [comment]
Would love to see all the calls to action (`download jpeg, tiff, iiif, requeast for photography, and image technical metadata) moved to the right below the image.

**Comment by edgartdata** [comment]
@EdwardTown1 What would be your preferences here?

**Comment by yulgit1** [comment]
@edgartdata - looking at vufind download functionality, for ex:
https://collections.britishart.yale.edu/vufind/Record/1669236

there is image metadata like:
image/tiff, 2468 x 3000 px, 300dpi, 8-bit color, 21.24MB

If it's not necessary, I can omit it, but if it is, where is this coming from? It is not in CDS (other than filesize in bytes):

http://deliver.odai.yale.edu/info/repository/YCBA/object/1000/type/2

**Comment by edgartdata** [comment]
Image technical metadata (dpi, color, size) not necessary.

**Comment by yulgit1** [comment]
resolved as of https://github.com/ycba-cia/blacklight-collections2/commits/solr_from_camel
@edgartdata ok to close?

**Comment by edgartdata** [comment]
@EdwardTown1 @mxgold We talked about replacing the paragraph of text that appears for non public domain with a link to the appropriate URL. Also unknown will point to its own URL and so will Public Domain.
@EdwardTown1 Would you like to preface the URL link with a brief note about how users can use our images?

**Comment by mxgold** [comment]
@yulgit1 

https://britishart.yale.edu/using-images-works-public-domain
https://britishart.yale.edu/terms-use-photographic-images-works-under-copyright
https://britishart.yale.edu/terms-use-photographic-images-works-requiring-further-research
 
above are the urls corresponding to the information pages for public domain, copyright and unknown.
 
Would you prefer the handles / persistent identifiers for the above?  I know the service is still working since I use them, but I don’t know who maintains it or the commitment to maintain into the future.

**Comment by yulgit1** [comment]
If readily available, the handles would be probably be better, NBD.  I assume these pages will get ported over to the new website?

**Comment by mxgold** [comment]
handle for unknown: http://hdl.handle.net/10079/c59zwbm
handle for public domain: http://hdl.handle.net/10079/w6m90dq
handle for copyrighted: http://hdl.handle.net/10079/rfj6qd5

**Comment by yulgit1** [comment]
per Ed:
more space around citations
closer image info to tabs
put jpeg above tiff

**Comment by yulgit1** [comment]
@mxgold, @EdwardTown1 OK?

http://10.5.96.187:3000/catalog/tms:7408 (copyright)
http://10.5.96.187:3000/catalog/tms:728 (public domain)
http://10.5.96.187:3000/catalog/orbis:3388920 (unknown)

**Comment by EdwardTown1** [comment]
Hi Eric,

What you showed me earlier today looked great. But these links aren't
working for me in Chrome. Am I doing something stupid?

E T
