### ISSUE TITLE
Publication Year facet title

### ISSUE THREAD

**Issue by edgartdata** [ycba-cia/blacklight-collections2#83]
@flapka Rename Publication Year facet to be just Date?

**Comment by flapka** [comment]
@edgartdata Yes, that'd be good.

**Comment by yulgit1** [comment]
Review to close

**Comment by flapka** [comment]
@edgartdata @yulgit1 The label is now correct. But (with apologies for being difficult) I wonder if this facet in its current form is of any use? Our goal is a single date range slider (a single facet for dates), as described in issue no. 38: https://github.com/ycba-cia/blacklight-collections2/issues/38 

Maybe until we have such a slider I'd prefer to have the earliest date and latest date facet -- although they too are a bit confusing (with the range options in each) -- but not this "Date" facet.

**Comment by flapka** [comment]
@yulgit1 @edgartdata Probably easiest to discuss in person, in one of our meetings?

**Comment by edgartdata** [comment]
I agree! @flapka @yulgit1 I don't see a BlackLight meeting next week except for the Friday morning one. If that's true, do you think it would be helpful to meet before friday next week?

**Comment by flapka** [comment]
@flapka @yulgit1  There's also the Blacklight meeting with Miriam on Tuesday (2-2:45). I don't mind meeting more -- if others want to too. My Outlook calendar is current.

**Comment by edgartdata** [comment]
Tuesday and Friday are probably enough for now.

**Comment by edgartdata** [comment]
@flapka For the art collections, we are okay if the Date facet gets replaced with a slider. 
We would rather want to privilege the Period facet, and move the Period facet to just before the slider.
It looks like the Date facet is dynamic, and works in tandem with the Period facet, which is great!

**Comment by flapka** [comment]
@edgartdata I think I agree with your first 3 paragraphs (though we may want to discuss as a group to make sure we're all on the same page). 

@yulgit1 As for the Period facet: I don't think it's useful/good to map library data to this field. It's not really a common concept in library cataloging (the current MARC mapping leads to bad data). I could open a new issue to recommend this change, if that's useful.

**Comment by edgartdata** [comment]
@flapka About the use of the Period facet by the library data: would it be possible to do some pre-processing of library data to produce century values? I am thinking that it is probably "easier" to harmonize the fewer century values than the year values? I am suggesting this because I do think a high level century based date access point could be helpful for users. @EdwardTown1 what do you think?

**Comment by flapka** [comment]
@edgartdata @EdwardTown1  I have no objections to @edgartdata 's suggestion. It would be relatively easy to derive from Earliest Date field (e.g., if value is between 1801 and 1900, then Period = "19th century"). Some records have a Latest Date field too; a small subset of items would span multiple centuries.

**Comment by edgartdata** [comment]
@flapka yeah! Let's check with @EdwardTown1 if that's something that jives with his vision for the catalog but I think it would be a helpful access point.

**Comment by edgartdata** [comment]
@flapka @yulgit1 Ed and I have discussed this and it is okay to go ahead to add date after the names of the creators, separated with a coma, on the same line.

**Comment by miriamschroers** [comment]
Replicate what we have in vufind

**Comment by yulgit1** [comment]
Date field now a slider, removed earliest date and latest date.

OK to close?

**Comment by flapka** [comment]
This is a big step in the right direction, but there are still issues I'd like to discuss with the group (perhaps on Friday?). Of most concern is how we deal with the "unknown" dates. 

For library material, the publication date (which the slider queries, I believe) isn't ideal for use in this slider. It would be better to query the earliest and latest date values, because those are normalized with machine-readable values -- so they'd give us fewer "unknown" values.

**Comment by edgartdata** [comment]
I agree with @flapka: the slider should query the indexed/machine readable earliest and latest date values, and not the display/human readable dates.
The reason is that it happens that we need to estimate the dates of creation. For example, when we don't know what year a known artist worked on a painting, we would say in the display/human readable date that it is 'undated', but the indexed/machine readable earliest date value would be the birth year of the artist (+ 15 years because we don't have artists who produced works before they were 15) and the indexed/machine readable latest date value would be his death date.

**Comment by yulgit1** [comment]
@flapka @edgartdata 
So re-add the earliest/latest date facets?

As for the Date facet, do you still want the slider (w/ the 'unknown' indication), or should that go back to listing year by year?

**Comment by edgartdata** [comment]
No the Earliest-Latest Dates facet should not come back.

But the Date facet should query the earliest and latest dates with the slider. 

Will unknowns still come up when the Date facet queries the earliest and latest dates?

**Comment by flapka** [comment]
+1 to @edgartdata 's instructions.

**Comment by yulgit1** [comment]
@edgartdata - not sure I understand, how can the 1 Date facet query 2 fields?

**Comment by edgartdata** [comment]
Can the slider's first box query the earliest dates and the second box query the latest dates? So in essence this facet would search on date ranges. I believe that is what the Vufind date slider does.

**Comment by yulgit1** [comment]
@edgartdata - Vufind is just looking at the earliest dates in that facet, for example, the URL ends up being:

https://collections.britishart.yale.edu/vufind/Search/Results?daterange[]=earliestDate&earliestDatefrom=1800&earliestDateto=1900

That can be replicated if you want.

**Comment by edgartdata** [comment]
@yulgit1 Let's take an example. If we want to search on all items created/published between 1904 and 1928, we mean that the earliest date could be between 1904 and 1928 AND the latest date could be between 1904 and 1929 as well.

Is that something possible in the Date facet?

If not, let's do what you suggest and use the earliestDate only.

**Comment by yulgit1** [comment]
@edgartdata - yes if understand correctly that earliest/latest date defines the range in which the asset was published, but it's a moot point as that can't be specified in 1 facet, so will go with the earliestDate like vufind.
