### ISSUE TITLE
language facet: data is missing

### ISSUE THREAD

**Issue by flapka** [ycba-cia/blacklight-collections2#84]
The language facet shows only 109 items with a language value. Between the Ref and RB collections, there should be at least 70,000 or so. At a glance, the XSLT (for MARC) looks correct, so the problem cause is unclear.

**Comment by yulgit1** [comment]
https://www.loc.gov/marc/bibliographic/bd008.html
The above source says language is in character positions 35-37

And the xslt was created as such:
substring(marc:controlfield[@tag='008'],36,3)

However that doesn't appear to be the case:

https://libapp.library.yale.edu/OAI_BAC/src/OAIOrbisTool.jsp?verb=GetRecord&identifier=oai:orbis.library.yale.edu:9049663&metadataPrefix=marc21
position 25-27

https://libapp.library.yale.edu/OAI_BAC/src/OAIOrbisTool.jsp?verb=GetRecord&identifier=oai:orbis.library.yale.edu:13200683&metadataPrefix=marc21
position 24-27

https://libapp.library.yale.edu/OAI_BAC/src/OAIOrbisTool.jsp?verb=GetRecord&identifier=oai:orbis.library.yale.edu:9720841&metadataPrefix=marc21
position 19-21

But it does seem though the language code is always 4 back from the end.  So I changed the xslt to reflect that and got the language code for these three.

@flapka Is this length-4 solution adequate?

**Comment by flapka** [comment]
@yulgit1 Yes, quite adequate. Your method seems to be the only way to go about it, based on the actual data. Thanks!

**Comment by flapka** [comment]
@yulgit1 Sorry, looking at the data again, I think we need to tweak the xslt just a bit. My hypothesis is that we need to look for the language code one position to the right of where it is currently looking -- but I'm not sure about this.

In the language facet, you'll notice we get a lot of hits for "Bengali" (code = "ben") and "Slave" (code = "den"). In these instances it's picking up codes that immediately precede the language code -- 'b' and 'd' reflect presence of language content -- + the first two letters for the language code 'eng'.

I do worry, that language code may not be consistently 4 back from the end (sometimes it may be 3). Could we test and find out? If there is the inconsistency when counting from the end, I'm not sure how best to precede.

**Comment by yulgit1** [comment]
Unfortunately it is inconsistent. Here are 3 different examples that I think should find "eng".  Is there another field that can be used instead?  Or is it possible to fix the 008 to strictly enforce the 35-37 language rule?

0012970333
00520110310173123.0
008901008s1989 stka b 00110beng

0017655833
00520110303200648.0
008060815s2006 enka 0|1 |deng d

0018167533
00520110329172738.0
008080401s2007 bcca b 000 0deng

**Comment by flapka** [comment]
It's not ideal, but maybe we should cheat by querying the oai_dc version of the record to grab the language code. We have to do the same thing to get callnumber data.

In the oai_dc version of each record, the proper language code is nicely parsed already in the <dc:language> tag, as in this example:

https://libapp.library.yale.edu/OAI_BAC/src/OAIOrbisTool.jsp?verb=GetRecord&identifier=oai:orbis.library.yale.edu:12838319&metadataPrefix=oai_dc

Sorry I didn't think of this earlier.

**Comment by yulgit1** [comment]
@flapka re-indexed using dc language, how's the facet look, ok to close?

**Comment by flapka** [comment]
@yulgit1 Very nice. Yes, okay to close. Thanks!

**Comment by yulgit1** [comment]
Root cause of initial problem. The fieldhand OAI-PMH client causing these problems uses an XML parsing library.  When OX, the library, parses XML it strips multiple spaces to one.  Here is a test of that I tried on the command line:
 
doc2 = Ox.parse("<b>some     stuff</b>")
 => #<Ox::Element:0x00007fe8ee939b88 @value="b", @nodes=["some stuff"]>
