### ISSUE TITLE
Call number problems

### ISSUE THREAD

**Issue by flapka** [ycba-cia/blacklight-collections2#86]
The call number data is erroneous: all (or many?) records show the same value (AM145 L65 1967 (LC)).

Call number data is mildly complicated. Keen in mind:
* the value is repeatable: RB, for example, may have multiple copies of an item, each with a different call number, as here: http://10.5.96.187:3000/catalog/orbis:6258017 
* RB and REF occasionally have copies of the same book. We want the display to indicate which call number applies to the RB copy and which to REF. Here's an example: http://10.5.96.187:3000/catalog/orbis:3652867
* We often share records with Beinecke (and others). We want to exclude the Beinecke call numbers (see again the first example, 6258017)

**Comment by yulgit1** [comment]
Erroneous because bug - all ended up with the same call number.  Currently reindexing, when done will explore the exceptions (repeats, which RB/REF?, exclude beinecke).

example:
https://libapp.library.yale.edu/OAI_BAC/src/OAIOrbisTool.jsp?verb=GetRecord&identifier=oai:orbis.library.yale.edu:1609&metadataPrefix=oai_dc

**Comment by flapka** [comment]
@yulgit1 Thanks, the biggest bug (same call numbers) now looks fixed.

Which leaves:

* Cases of repeated call numbers for multiple copies (in RB, for example): The data is there in the OAI, for example: https://libapp.library.yale.edu/OAI_BAC/src/OAIOrbisTool.jsp?verb=GetRecord&identifier=oai:orbis.library.yale.edu:6258017&metadataPrefix=oai_dc 

* Cases when RB and REF have copies of the same book, as in record 3652867. This problem looks challenging, because the call number data (for the RB copy) is not served in OAI. I'm not sure how to overcome. See: https://libapp.library.yale.edu/OAI_BAC/src/OAIOrbisTool.jsp?verb=GetRecord&identifier=oai:orbis.library.yale.edu:3652867&metadataPrefix=oai_dc
