### ISSUE TITLE
Download object caption

### ISSUE THREAD

**Issue by edgartdata** [ycba-cia/blacklight-collections2#90]
Would it be possible to add accession numbers to the text file that can be downloaded with an image?

Example of current downloadable object caption:
Canaletto, 1697–1768, Venetian, active in Britain (1746–55), Old Walton Bridge, 1755, Oil on canvas, Yale Center for British Art, Paul Mellon Collection

Just adding the accession number at the end of the caption would be helpful.

**Comment by yulgit1** [comment]
@edgartdata - yes the accession number can be added, but where is the existing caption (as in vufind) coming from?  Melissa mentioned there might be a lido field for this?

**Comment by yulgit1** [comment]
resolved as of https://github.com/ycba-cia/blacklight-collections2/commits/solr_from_camel
@edgartdata ok to close?
