### ISSUE TITLE
Object/image rights information appears even when images are not available

### ISSUE THREAD

**Issue by mxgold** [ycba-cia/blacklight-collections2#91]
In the current online collection, if no images are available for a record, the object/image rights info and link is suppressed (Public Domain / (c) 2018 Famous Artist, etc.)  In the Blacklight Test, it is visible regardless.
Discuss / decide if OK?
<img width="942" alt="screen shot 2019-02-14 at 11 27 42 am" src="https://user-images.githubusercontent.com/36539808/52801688-7203a500-304c-11e9-9f8e-509631660d7c.png">

**Comment by flapka** [comment]
Seems undesirable. FWIW, I anticipate that MARC records will have the object rights data only when we are providing images for it.

**Comment by yulgit1** [comment]
example: http://10.5.96.187:3000/catalog/tms:32081
