### ISSUE TITLE
Orbis "Related content" field

### ISSUE THREAD

**Issue by mxgold** [ycba-cia/blacklight-collections2#92]
The appearance of this field in the online record refers the viewer to the record they are already viewing.  Is it possible/desirable to suppress it?
<img width="961" alt="screen shot 2019-02-14 at 11 55 08 am" src="https://user-images.githubusercontent.com/36539808/52803253-adec3980-304f-11e9-9437-82243ecfca0d.png">

**Comment by flapka** [comment]
Strong +1. 

The date is from the 856 field, in this form: 

856 41 |3 View a digitized version of this item in the online catalog of the Yale Center for British Art  |u http://collections.britishart.yale.edu/vufind/Record/2031741

Could we cut out this field at the point of ingest -- i.e., exclude all 856 data if it includes the text "View a digitized version of this item in the online catalog of the Yale Center for British Art "?  I wouldn't specify a subfield (at times it has been in subfield $3, at other times it could be in subfield $y).

**Comment by yulgit1** [comment]
test example:
http://10.5.96.187:3000/catalog/orbis:4190566

addressed in: https://github.com/ycba-cia/blacklight-collections2/commit/1a76f0607ffd5a247ba70b2003b1ffd148cf3ef7 and https://github.com/ycba-cia/blacklight-collections2/commit/a1605bc02934ae81ba37de9ba5cbcdfe53f0da3c

@flapka @mxgold ok to close?

**Comment by flapka** [comment]
Yes, looks good. Thanks @yulgit1
