### ISSUE TITLE
Color of headings for 'Collection' and 'Currently On View' facets in Chrome browser for Mac

### ISSUE THREAD

**Issue by EdwardTown1** [ycba-cia/blacklight-collections2#93]
Hi @yulgit1 - not a big deal but I wondered whether the green color which appears once you click on a value within the facet is in step with Fabrique's overall design? If it were possible, perhaps we could work with a grey rather than green. Please forgive me fussing over this.

**Comment by yulgit1** [comment]
@EdwardTown1 - does this grey look ok?

<img width="325" alt="image" src="https://user-images.githubusercontent.com/2125400/53348336-db0ad880-38e8-11e9-8853-150e620d6c1b.png">

**Comment by EdwardTown1** [comment]
Looks nice!

Thanks so much.
E T
