### ISSUE TITLE
Center the metadata in object records?

### ISSUE THREAD

**Issue by edgartdata** [ycba-cia/blacklight-collections2#95]
Question to the group @flapka @EdwardTown1 @KraigBinkowski: do we feel like centering the metadata under the main image in the detailed object records would be a good design decision? Does this impact the responsiveness of the design on different devices?

**Comment by yulgit1** [comment]
centered metadata

@flapka @EdwardTown1 @KraigBinkowski @edgartdata OK to close?

**Comment by KraigBinkowski** [comment]
I don’t know – to be honest – this looks a little awkward to me:

[cid:image001.jpg@01D4CA9A.FAAAF830]


The old arrangement of images and text (while the main image should be bigger) seemed much more elegant.

[cid:image002.jpg@01D4CA9A.FAAAF830]

**Comment by flapka** [comment]
No opinion. I defer to others.
