### ISSUE TITLE
Sorting of search results

### ISSUE THREAD

**Issue by edgartdata** [ycba-cia/blacklight-collections2#97]
As per our current sort order, search results should be appear in the following order: P&S, P&D, RB, Reference Library, and frames.

**Comment by yulgit1** [comment]
order boosts as per:
https://gist.github.com/yulgit1/5f5e887f08270149746376417f42a1ac

ongoing search ranking issues tracked here
https://github.com/ycba-cia/blacklight-collections2/issues/80
