### ISSUE TITLE
Size of thumbnails in light box view mode

### ISSUE THREAD

**Issue by edgartdata** [ycba-cia/blacklight-collections2#99]
Would it be possible to half the padding/space between each image box, vertically and horizontally, to make the images larger? Could we maybe look at a test design for that?

**Comment by yulgit1** [comment]
@edgartdata  Adjusted left/right padding.  Tried the selectors for top/bottom, didn't have any effect.  

Definately an improvement so committed the change.
https://github.com/ycba-cia/blacklight-collections2/commit/7e399b6978c5cef6e5b30795dadf2d8b87fb13af

Example:
http://10.5.96.187:3000/?f[collection_ss][]=Paintings+and+Sculpture
